# -*- coding: utf-8 -*-
"""Sections 3 and 4 of The Copper Beeches, part two: 191 to 194, and 195 to 198.

The hair in the drawer and the barricaded door. The reading stops mid-sentence
on 198, with Miss Hunter deciding to send for Holmes; nothing here goes near
199, where he answers her.
"""
from beech2_q12 import V, item


# ====================================================================== 3
S3 = [

    item("hair", ["a great coil at the bottom of my trunk",
                  "the lower one locked", "It was my coil of hair",
                  "they were identical"],
         V("What had Miss Hunter done with the hair she cut off in London?",
           ["Sold it before she left",
            "Thrown it away at her lodging",
            "Packed it in a coil at the bottom of her trunk",
            "Given it away to Miss Stoper at the agency"],
           2,
           "She kept it — and kept it at the bottom of a trunk in her own room, which is what makes the next few minutes impossible rather than merely odd."),
         V("How does she come to open the locked drawer?",
           ["She finds the key left in the lock",
            "She needs the space, and one of her own keys fits",
            "Mrs. Rucastle asks her to empty it out",
            "The drawer had been left standing open by mistake"],
           1,
           "Two drawers full, more to pack, and a third locked. She assumes it was fastened by mistake and tries her own keys — “the very first key fit to perfection.” She is not snooping; she is unpacking."),
         V("What is in the drawer?",
           ["A photograph of a young woman",
            "A coil of hair exactly like her own",
            "The large black linen bag",
            "A bundle of letters, tied with tape"],
           1,
           "One thing only. The same peculiar chestnut tint, the same thickness — and her own coil is still at the bottom of her trunk where she left it."),
         V("How does she check that it is not her own hair?",
           ["She counts the pins that were in it",
            "She asks Toller’s wife whose it is",
            "She fetches her own from the trunk and lays them together",
            "She looks for the ribbon that she had tied her own with"],
           2,
           "She does not guess and she does not panic. She goes and gets the other one and puts them side by side — “I assure you they were identical.” That is an experiment."),
         V("Why does she say nothing to the Rucastles about it?",
           ["She was afraid of the mastiff",
            "She thought they would not believe her",
            "She felt she had put herself in the wrong by opening a locked drawer",
            "She had promised the servants that she would keep it all quiet"],
           2,
           "Scrupulous, even here. She has found something frightening and her first thought is that she had no business in that drawer. It costs her — she now has to carry it alone."),
         ),

    item("wing", ["one wing, however, that appeared not to be inhabited",
                  "a very different person from the jovial man",
                  "the veins stood out at his temples",
                  "The fourth was shuttered up"],
         V("What does Miss Hunter say about her own habits of mind?",
           ["That she is too curious for her own good",
            "That she is naturally observant",
            "That she is slow to take alarm",
            "That she forgets names and faces easily"],
           1,
           "“I am naturally observant, Mr. Holmes, and I soon had a pretty good plan of the whole house in my head.” She says it as a plain fact about herself, and the reading keeps proving it."),
         V("What does she notice about one wing of the house?",
           ["It has been newly painted",
            "It is not lived in, and its door is always locked",
            "It is where the Tollers sleep",
            "It can only be reached from the garden on the outside"],
           1,
           "A door opposite the Tollers’ quarters, always locked. In a house with two servants and empty rooms everywhere, one wing is locked — and the lock is the interesting part."),
         V("How does Mr. Rucastle look when she meets him coming out of that door?",
           ["Exactly as jovial as always",
            "Tired, as though he had been working hard",
            "Red-faced and furious, quite unlike himself",
            "Frightened, and in a great hurry"],
           2,
           "Cheeks red, brow crinkled with anger, veins standing out at his temples — “a very different person from the jovial man to whom I was accustomed.” It is the first time she sees what is under the laughing."),
         V("What does he do when he passes her on the stair?",
           ["Explains what he had been doing",
            "Locks the door and hurries past without a word or a look",
            "Asks her what she is doing upstairs",
            "Drops his keys on the stair, and she picks them up for him"],
           1,
           "He locks it first. Even in a rage, the door gets locked — and he cannot manage a word to her, which from this man is as loud as shouting."),
         V("What does she see when she goes round to look at that wing’s windows?",
           ["All four boarded over",
            "Lights burning in two of the four windows",
            "Three simply dirty, the fourth shuttered up",
            "Bars across every one"],
           2,
           "Three dirty windows say nobody lives there. One shuttered window says somebody has gone to trouble over that room in particular — and she will meet the inside of it two pages later."),
         ),

    item("darkroom", ["Photography is one of my hobbies",
                      "there was no jest in his eyes",
                      "a feeling of duty",
                      "a large black linen bag"],
         V("What does Mr. Rucastle say the shuttered room is for?",
           ["Storing furniture",
            "A darkroom for his photography",
            "A nursery, no longer in use",
            "He refuses to say at all"],
           1,
           "Photography, he says — and a darkroom does need a shuttered window, so the explanation fits the one fact she has mentioned. It does not fit the bar from an iron bed, which she has not seen yet."),
         V("What does Miss Hunter notice about the way he says it?",
           ["He stammered over the word darkroom",
            "He would not look at her at all",
            "He spoke jokingly, but there was no jest in his eyes",
            "He laughed so hard that he could not finish it"],
           2,
           "“I read suspicion there, and annoyance, but no jest.” She separates the tone from the eyes. That is a skill, and it is the same one that catches the voice being “a little too coaxing” later."),
         V("What does Miss Hunter say her wish to see the rooms is, if it is not curiosity?",
           ["A wish to prove Holmes right",
            "A feeling of duty — that some good might come of it",
            "A hope of finding something worth money",
            "Fear of being blamed later if something happened"],
           1,
           "“It was not mere curiosity. It was more a feeling of duty — a feeling that some good might come from my penetrating to this place.” She is not sure where the feeling comes from and says so honestly."),
         V("What has she seen Mr. Rucastle carry through the forbidden door?",
           ["A tray of food",
            "A lamp and a bundle of candles",
            "A large black linen bag",
            "The coil of hair from the drawer"],
           2,
           "One detail, dropped in among others. She reports it without saying what she thinks it means — which is the right way round, and makes it worth more."),
         V("What finally gives her the chance to go in?",
           ["Mrs. Rucastle takes the child away for a day",
            "She finds a spare key in the drawer",
            "Toller gets very drunk, and the key is left in the door",
            "The Tollers both go into Winchester for the evening"],
           2,
           "Everything at once: Toller drunk, the key in the door, both Rucastles downstairs with the child. The chance is made by the one servant who can be relied on being unreliable."),
         ),
]


# ====================================================================== 4
S4 = [

    item("barricade", ["three doors in a line",
                       "one of the broad bars of an iron bed",
                       "Evidently a skylight let in light from above",
                       "saw a shadow pass back and forth"],
         V("What does Miss Hunter find round the corner of the passage?",
           ["A staircase leading down to the cellar",
            "Three doors in a line, two of them open",
            "A single door, standing wide",
            "A corridor of locked bedrooms"],
           1,
           "The first and third lead into empty rooms, dusty and cheerless. Only the middle one is shut — and the two open ones are there so that you notice the shut one."),
         V("How is the middle door fastened?",
           ["With a padlock and chain through the handle",
            "Nailed shut from the outside",
            "With a bar from an iron bed, padlocked and corded across it",
            "Only locked, in the same way as every other door up there"],
           2,
           "Padlocked to a ring in the wall at one end, tied with heavy cord at the other, and the door locked as well. That is not how you secure a darkroom. It is how you secure a person."),
         V("What tells her the room beyond is not dark?",
           ["A lamp burning under the door",
            "A glimmer under the door, from a skylight above",
            "The shutter had been opened",
            "She can hear somebody striking a match in there"],
           1,
           "Light from above, which the shuttered window cannot explain. The one room they have blacked out from outside has light coming into it from the roof — so the shutter is not there to keep light out."),
         V("What does she hear and see while she stands there?",
           ["Nothing at all, which is why she left",
            "Someone calling out to her through the door",
            "Steps inside, and a shadow passing back and forth",
            "Toller coming up the stairs behind her"],
           2,
           "Somebody is walking up and down in that room. That is the moment the house stops being strange and becomes something worse, and she says so: “a mad, unreasoning terror rose up in me.”"),
         V("Put the bar, the skylight and the footsteps together. What has she found?",
           ["A darkroom in use",
            "A storeroom nobody has opened in years",
            "A room with somebody shut inside it",
            "An empty room the Rucastles are afraid of"],
           2,
           "Barred from the outside, lit from above, and with somebody walking about inside. Every one of those three facts is in front of her, and the conclusion needs nothing else."),
         ),

    item("coaxing", ["I thought it must be when I saw the door open",
                     "just a little too coaxing", "He overdid it",
                     "to keep people out who have no business there"],
         V("Who is waiting outside the door when she runs out?",
           ["Toller’s wife",
            "Mr. Rucastle",
            "Mrs. Rucastle, with the child",
            "Nobody — she gets back to her room unseen"],
           1,
           "She runs straight into his arms. He had seen the door open and worked out who it must be — so he was waiting, and he let her go all the way in first."),
         V("How does Mr. Rucastle speak to her at first?",
           ["Angrily, demanding an explanation",
            "Coldly, saying nothing at all",
            "In a caressing, soothing manner",
            "He laughs and makes a joke of it"],
           2,
           "“My dear young lady! my dear young lady!” It is kindness turned up as far as it will go, applied to a woman he has just caught in the one place he forbade."),
         V("What does Miss Hunter make of that manner?",
           ["That he was genuinely concerned for her",
            "That it was a little too coaxing — he overdid it",
            "That he had not understood where she had been",
            "That he was about to dismiss her"],
           1,
           "“He overdid it. I was keenly on my guard against him.” She reads the excess rather than the warmth, which is the second time this reading that she catches him acting."),
         V("What does she tell him, and what does she keep back?",
           ["Everything, including the footsteps",
            "That she went into the empty wing and the stillness frightened her",
            "Nothing at all — she refuses to answer him so much as a word",
            "That she was looking for the child"],
           1,
           "True, and not the whole truth. She says nothing about the barred door or the shadow — and his “Only that?” shows he is testing exactly that gap."),
         V("What reason does he give for locking the door?",
           ["That the floor is unsafe up there",
            "That his photographs would all be spoiled",
            "To keep people out who have no business there",
            "That his wife asked him to"],
           2,
           "Said “still smiling in the most amiable manner.” It explains nothing — every locked door keeps people out — and it is the last thing he says before the smile goes."),
         ),

    item("mastiff", ["the smile hardened into a grin of rage",
                     "I’ll throw you to the mastiff",
                     "even of the child",
                     "my curiosity was almost as strong as my fears"],
         V("What does Mr. Rucastle say if she goes through that door again?",
           ["That she will be dismissed at once",
            "That he will write to Miss Stoper",
            "That he will throw her to the mastiff",
            "That he will lock her in her room"],
           2,
           "And the smile “hardened into a grin of rage” as he said it. A dog kept hungry on purpose, and a man who has just named it as a punishment for her."),
         V("What happens to his manner as he says it?",
           ["He keeps smiling throughout",
            "He turns away so she cannot see his face",
            "The smile hardens into a grin of rage",
            "He begins to laugh, as at a joke"],
           2,
           "The jovial man and the furious one are the same face, and she watches it change in a single sentence. It is the clearest look at him in the whole reading."),
         V("Who is Miss Hunter frightened of by the end?",
           ["Only Mr. Rucastle",
            "Mr. Rucastle and Toller",
            "The house, the man, the woman, the servants, even the child",
            "Nobody at all — she says that her nerve had quite returned"],
           2,
           "She lists them, and the list ends “even of the child.” The whole house has become frightening, not one person in it."),
         V("Why does she not simply run away?",
           ["She has nowhere to go and no money",
            "She had promised to stay the quarter",
            "Her curiosity was almost as strong as her fears",
            "The mastiff is loose on the lawn at night"],
           2,
           "“Of course I might have fled, but my curiosity was almost as strong as my fears.” Almost — she is honest that the fear is the bigger of the two, and she stays anyway."),
         V("What does she decide to do instead?",
           ["Confront Mr. Rucastle about the room",
            "Send for Sherlock Holmes",
            "Ask the servants what is behind the door",
            "Take the child and leave in the night"],
           1,
           "“Then I thought of you, Mr. Holmes. I could not live there longer without some advice.” It is why she is sitting in the Black Swan telling him all this, and where tonight’s reading stops."),
         ),
]
