# -*- coding: utf-8 -*-
"""Sections 5 and 6 of The Copper Beeches: pages 175 to 179, and 180 to 183.

Section 6 has four questions rather than three. The last of them is the
character-traits summary the class is working towards: it asks what Violet
Hunter is like across the whole reading rather than on any one page, and it is
anchored on the sentence where she insists on being fair to people who frighten
her.

The reading stops mid-sentence on 183. Nothing here reaches into 184.
"""
from beech_q12 import V, item


# ====================================================================== 5
S5 = [

    item("letter2", ["thirty pounds a quarter", "inconvenience our fads may cause you",
                     "a particular shade of electric blue",
                     "my dear daughter Alice (now in Philadelphia)"],
         V("What does the second letter offer her?",
           ["The same hundred pounds, and no conditions",
            "£120 a year, to recompense her for the fads",
            "Her old salary of four pounds a month",
            "A trial month before anything is decided"],
           1,
           "Thirty pounds a quarter — £120 a year. He has raised it again without being asked, and he says plainly what the extra is for: “to recompense you for any inconvenience our fads may cause you.”"),
         V("What does the letter say about the dress?",
           ["That she must buy one for herself in London before she comes down",
            "That his wife likes electric blue, and they already have such a dress",
            "That she may wear whatever she pleases indoors",
            "That the dress is to be worn only for visitors"],
           1,
           "A particular shade of electric blue, to be worn indoors in the morning — and she need not buy one, because they have one already. A dress waiting in the house before the governess has agreed to come."),
         V("Whose dress is it?",
           ["Mrs. Rucastle’s own",
            "One bought for the last governess they had",
            "His daughter Alice’s, now in Philadelphia",
            "The letter does not say"],
           2,
           "Alice Rucastle’s, “now in Philadelphia” — the first time anyone mentions a daughter. A dress belonging to a young woman who has gone away, and it is expected to fit Miss Hunter."),
         V("What does the letter not give way on?",
           ["The salary",
            "The dress",
            "Where she is to sit",
            "Her hair"],
           3,
           "“I am afraid that I must remain firm upon this point.” He pays more, he supplies the dress, he calls the duties light — and the one thing he will not move on is the haircut."),
         V("Who is the letter signed by?",
           ["Miss Stoper",
            "Jephro Rucastle",
            "Colonel Spence Munro",
            "Alice Rucastle"],
           1,
           "Jephro Rucastle — the first time the stout man is given a name, several pages after we met him. Until this letter he has simply been the gentleman in Miss Stoper’s office."),
         ),

    item("uneasy", ["a sister of mine", "I have no facts. I cannot tell",
                    "his wife is a lunatic", "the pay is good – too good"],
         V("What does Holmes say when she asks whether she should refuse?",
           ["That she must certainly refuse",
            "That it is not a place he would like a sister of his to apply for",
            "That the decision is hers alone, and he will not comment on it",
            "That the family sound perfectly respectable"],
           1,
           "“I confess that it is not the situation that I should like to see a sister of mine apply for.” As strong a warning as he can give without facts — and he still does not tell her what to do."),
         V("When she asks what it all means, what does Holmes answer?",
           ["That the wife is certainly mad",
            "That Mr. Rucastle is plainly a criminal",
            "That he has no facts, and cannot tell",
            "That the dress is the key to the whole thing"],
           2,
           "“Ah, I have no facts. I cannot tell.” The same answer he gave about Horner. He will say what he knows and no more, which is why it is worth something when he does say a thing."),
         V("What is Miss Hunter’s own explanation?",
           ["That the family want her for her hair",
            "That Mr. Rucastle’s wife is mad, and he is humouring her",
            "That they mean to rob her of the advance",
            "That the child is dangerous and the parents both know it"],
           1,
           "A wife he keeps from an asylum by giving in to her fancies. Holmes calls it “the most probable one” as matters stand — and she finds out herself, when she gets there, that it is wrong."),
         V("What is the one thing that makes Holmes uneasy?",
           ["That the house is far from London",
            "That nobody has met the wife",
            "That the pay is too good",
            "That Miss Stoper was annoyed"],
           2,
           "“Why should they give £120 a year, when they could have their pick for £40?” Everybody else is pleased about the money. Holmes asks what is being bought with it, which is not the same question."),
         V("Why is “the pay is good – too good” a piece of reasoning rather than a feeling?",
           ["Because Holmes has met Mr. Rucastle before",
            "Because the market price of the work is known, and this is triple it",
            "Because Miss Hunter had already said very much the same thing herself",
            "Because the advance was paid in cash"],
           1,
           "Governesses could be had for £40. Paying three times the going rate means paying for something besides the work — he does not yet know what, and he says so, but the gap itself is the evidence."),
         ),

    item("telegram", ["the most interesting that has come my way",
                      "It would cease to be a danger if we could define it",
                      "She rose briskly from her chair",
                      "able to take care of herself"],
         V("What does Holmes now say about her problem?",
           ["That it is too slight to be worth his time",
            "That it is the most interesting to come his way in months",
            "That he will take it only if she is paid in advance",
            "That the police should be told at once"],
           1,
           "The man who called her letter his zero point. Watson was right on page 167, and this is the sentence that proves it."),
         V("When she asks what danger he foresees, what does he say?",
           ["That the child is the danger",
            "That he fears for her hair, and for nothing else at all",
            "That it would cease to be a danger if they could define it",
            "That there is no danger at all"],
           2,
           "A danger you can name is one you can guard against. He cannot name this one, which is exactly why it worries him — and it is the most honest thing he could have said."),
         V("What does he promise her?",
           ["To come down if she telegraphs, day or night",
            "To write to Mr. Rucastle on her behalf",
            "To send Watson with her to Hampshire",
            "To find her another position if this fails"],
           0,
           "“At any time, day or night, a telegram would bring me down to your help.” It is the whole of what he can offer, and it turns out to be enough — she leaves with the anxiety swept from her face."),
         V("What does she say she will do that night?",
           ["Write to Colonel Spence Munro",
            "Go back to Miss Stoper",
            "Sacrifice her hair",
            "Think it over once more"],
           2,
           "“I shall write to Mr. Rucastle at once, sacrifice my hair tonight, and start for Winchester tomorrow.” Decided, and then done the same evening. The word sacrifice says what it costs her and she does it anyway."),
         V("Watson says she can take care of herself. What does Holmes reply, and what does it mean?",
           ["“And she would need to be” — he expects her to need it",
            "That she is braver than she is sensible",
            "That she will not last a single week in that house",
            "That Watson is too easily impressed"],
           0,
           "“And she would need to be,” said Holmes gravely. It is agreement and a warning in five words — and the reading breaks on it, so you are left holding it for two weeks of story time."),
         ),
]


# ====================================================================== 6
S6 = [

    item("summons", ["I can’t make bricks without clay", "Just look up the trains",
                     "the Black Swan Hotel at Winchester",
                     "I am at my wits’ end"],
         V("What does Holmes say when Watson raises the case during the two weeks of waiting?",
           ["That he has already solved it",
            "“Facts! facts! facts! I can’t make bricks without clay”",
            "That he has forgotten all about Miss Hunter",
            "That they should go down to Hampshire without being asked"],
           1,
           "He sits for half an hour at a time with knitted brows and then waves the subject away. He is not ignoring it — he is refusing to guess, which is a different thing and harder."),
         V("When does the telegram arrive?",
           ["The morning after she leaves",
            "Two weeks later, late at night",
            "A month later, by the first post",
            "It never arrives; they go down unasked"],
           1,
           "Two weeks, late one night, just as Watson was thinking of turning in. Long enough for the reader to wonder, which is what the two weeks are for."),
         V("What does the telegram ask?",
           ["That Holmes write to Mr. Rucastle at once",
            "That he send a doctor to the house",
            "That he be at the Black Swan at Winchester at midday",
            "That he come down to the Copper Beeches after dark"],
           2,
           "“Please be at the Black Swan Hotel at Winchester at midday tomorrow. Do come! I am at my wits’ end.” Twenty words, and two of them — “Do come!” — are not the brisk woman who left Baker Street."),
         V("How does Holmes react to it?",
           ["He telegraphs back for more detail",
            "He says “Just look up the trains” and returns to his work",
            "He refuses to go until morning",
            "He wakes Watson and leaves for Hampshire immediately"],
           1,
           "No surprise and no discussion. He had said a telegram would bring him down day or night, and when it comes he treats going as settled and gets back to what he was doing."),
         V("She uses the phrase “at my wits’ end” twice in this story. When was the first time?",
           ["When she refused to cut her hair",
            "When her savings ran out and she had no work",
            "When she first caught sight of the Copper Beeches",
            "When Miss Stoper struck the gong"],
           1,
           "On page 168, about being out of work and nearly out of money. The same five words, and the second time she is not short of money at all — which tells you how much worse this is."),
         ),

    item("freedom", ["not personally threatened", "She has her freedom",
                     "seven separate explanations",
                     "he didn’t know the purpose"],
         V("What does Holmes conclude from the fact that she can meet them in Winchester?",
           ["That she is not in any real trouble",
            "That she is not personally threatened, and has her freedom",
            "That the Rucastles must already have dismissed her from the house",
            "That she has left the house for good"],
           1,
           "A prisoner cannot catch a train. It narrows the problem a great deal without solving any of it — whatever is wrong at that house, it is not being done to her."),
         V("How many explanations has Holmes worked out on the way down?",
           ["None — he still has no facts",
            "One, which he is sure of",
            "Three, and he favours the first",
            "Seven, each of which fits the facts"],
           3,
           "“Seven separate explanations, each of which would cover the facts as far as we know them.” Not one theory defended — seven held loosely, waiting for the fact that will kill six of them."),
         V("Why is Miss Hunter in a hurry at the Black Swan?",
           ["She has a train to catch back to London",
            "She has promised Mr. Rucastle to be back before three",
            "She is afraid of being followed",
            "The inn is about to close up its dining room for the day"],
           1,
           "She asked permission to come into town and has to be back by three. She is keeping her word to a man she has telegraphed Sherlock Holmes about, which is very like her."),
         V("What has she not told Mr. Rucastle?",
           ["That she went into Winchester at all",
            "That she has written to Holmes before",
            "The purpose of her visit to town",
            "That she means to leave the position"],
           2,
           "“I got his permission to come into town this morning, though he didn’t know the purpose.” She asks rather than sneaks, and keeps back only the one thing she must. Careful, not deceitful."),
         V("What does Holmes mean by “Let us have everything in its due order”?",
           ["That she should tell only what she thinks important",
            "That she should start at the beginning and leave nothing out",
            "That she should write it down instead of speaking",
            "That he will ask the questions, and she should only answer"],
           1,
           "He stretches his legs to the fire and composes himself to listen. He wants the whole thing in sequence, because he does not yet know which part matters — the same reason he says later that he is glad of all details."),
         ),

    item("house", ["no actual ill treatment", "stained and streaked with damp weather",
                   "A clump of copper beeches in front of the hall door",
                   "Mrs. Rucastle is not mad"],
         V("What is the first thing Miss Hunter says about the Rucastles?",
           ["That they have treated her cruelly",
            "That she has had no actual ill treatment from them",
            "That she is frightened of both of them",
            "That she has barely seen them since she arrived"],
           1,
           "“I have met with no actual ill treatment from Mr. and Mrs. Rucastle. It is only fair to say that.” She has telegraphed for a detective and she still opens by being fair to them."),
         V("What is the house itself like?",
           ["Small and neat, newly built",
            "A ruin, with half its roof gone",
            "A large square block, stained and streaked with damp",
            "A pretty cottage standing among the woods on three sides"],
           2,
           "“Beautifully situated, but it is not beautiful in itself.” Woods on three sides and a field sloping to the road on the fourth — lovely country, and an ugly damp-stained house sitting in the middle of it."),
         V("Where does the house get its name?",
           ["From the Rucastle family motto",
            "From a village of that name nearby",
            "From a clump of copper beeches in front of the hall door",
            "From the colour of the stone that the walls are built of"],
           2,
           "A clump of copper beeches by the front door. The trees give the story its title, and they are the first thing you see when you arrive and the last thing between the house and the road."),
         V("What had Miss Hunter and Holmes both guessed wrong?",
           ["That the child would be difficult",
            "That the salary would not be paid",
            "That Mrs. Rucastle was mad",
            "That the house would be far from Winchester"],
           2,
           "“There was no truth, Mr. Holmes, in our conjecture. Mrs. Rucastle is not mad.” The most probable solution, held by both of them, and the first fact she brings knocks it down — which is what facts are for."),
         V("What does “It is only fair to say that” tell you about the way she gives evidence?",
           ["She is afraid of being overheard",
            "She is trying to protect her employers",
            "She separates what frightens her from what she can prove",
            "She does not really believe that anything is wrong there"],
           2,
           "She is frightened enough to send a telegram and careful enough not to let the fright do her reporting for her. That is why Holmes can use what she tells him."),
         ),

    item("house", ["no actual ill treatment", "It is only fair to say that",
                   "But I cannot understand their reasons for their conduct"],
         V("Across the whole reading, which set of traits best describes Violet Hunter?",
           ["Timid, obedient, and easily frightened",
            "Clever but dishonest, and out for the money",
            "Independent, honest about herself, and firm when it matters",
            "Proud, stubborn, and quite unwilling to take any advice"],
           2,
           "She keeps herself, she asks for help when she needs it, she admits she nearly changed her mind for the money, she refuses the one thing she will not do — and then she does it when she has decided to go. All four show up in the pages you have just read."),
         V("Which moment shows her courage most clearly?",
           ["Refusing to cut her hair when she was almost penniless",
            "Writing to Sherlock Holmes for advice",
            "Travelling to Winchester to meet Holmes",
            "Telling Mr. Rucastle she would take the position"],
           0,
           "Two bills on the table, an empty cupboard, and four times her old salary on the other side of it. Courage is not the absence of need — it is a limit that holds when the need is real."),
         V("She first refuses to cut her hair and later sacrifices it. Is that a change of character?",
           ["Yes — she gives in as soon as the money is raised",
            "No — refusing an order is not the same as choosing",
            "Yes — she had always meant to accept",
            "No — she never cuts it at all"],
           1,
           "The first time it was a condition pressed on her in a room by a stranger, and she said no. The second time she had weighed it, decided to go, and did it herself that night. Same person, different question."),
         V("What does Miss Hunter do that Mr. Rucastle never does?",
           ["Keep a promise she has made",
            "Say plainly what she thinks of someone",
            "Admit when she has been wrong or uncertain",
            "Ask for advice from a friend"],
           2,
           "She tells Holmes she was startled, that she nearly went back, that she cannot understand the Rucastles, and that they have not ill-treated her. Rucastle is certain about everything, flatters, laughs, and never gives a reason that is really his."),
         V("Holmes said she would need to be able to take care of herself. What in this reading suggests she can?",
           ["That she took the highest salary that she had ever been offered",
            "That she told the Rucastles nothing about Holmes",
            "That she asked leave to go to town, went, and will be back by three",
            "That she travelled to Hampshire alone"],
           2,
           "She got out, got advice, and is going back — without lying, without panicking, and inside the time she promised. She is managing a frightening house rather than running from it or ignoring it."),
         ),
]
