# -*- coding: utf-8 -*-
"""Sections 1 and 2 of The Copper Beeches, part two: pages 185 to 186, 188 to 190.

Twelve questions over the reading, three to a section, five versions of each.

This stretch is Violet Hunter noticing things, so the questions mostly ask what
she noticed and what it is evidence of. Where a version asks for a conclusion,
the conclusion is one the text supports on its own -- nothing here needs the
solution, which is pages away.
"""


def V(q, opts, a, why):
    return {"q": q, "opts": opts, "a": a, "why": why}


def item(p, hi, *vs):
    return {"type": "pick", "p": p, "hi": hi, "vs": list(vs)}


# ====================================================================== 1
S1 = [

    item("servants", ["There are only two, a man and his wife",
                      "a perpetual smell of drink",
                      "Mr. Rucastle seemed to take no notice of it",
                      "a tall and strong woman with a sour face"],
         V("How many servants are there at the Copper Beeches?",
           ["A full household of eight or nine",
            "Four, counting the gardener",
            "Only two, a man and his wife",
            "None at all; Mrs. Rucastle keeps the house herself"],
           2,
           "Two servants for a large country house. That is remarkably few, and it is the first thing about the place that strikes her as unpleasant — a house with almost nobody in it."),
         V("What is Toller like?",
           ["Quiet, neat and very correct",
            "Young, and quite new to the household here",
            "Cheerful, and fond of the child",
            "Rough and uncouth, and always smelling of drink"],
           3,
           "Grizzled hair and whiskers and “a perpetual smell of drink.” Perpetual — not now and then. He is drunk twice in the few weeks she is there, and that is only what she sees."),
         V("What does Mr. Rucastle do about Toller’s drinking?",
           ["He dismisses him on the spot",
            "He takes no notice of it",
            "He locks the drink away",
            "He has his wife keep him out of sight"],
           1,
           "“Twice since I have been with them he has been drunk, and yet Mr. Rucastle seemed to take no notice of it.” A master who ignores that is a master who needs this particular servant more than he needs him sober."),
         V("What is Toller’s wife like?",
           ["Kind, and glad of another woman in the house",
            "Talkative, and full of the family’s history",
            "Tall and strong, with a sour face, and silent",
            "Frail, and seldom seen downstairs"],
           2,
           "“As silent as Mrs. Rucastle, and much less amiable.” Two silent women in one house, and Miss Hunter notices that both of them are silent rather than only one."),
         V("Why does it matter that the household is so small?",
           ["It explains why the salary is so high",
            "It shows the Rucastles cannot afford to keep more",
            "Fewer people means fewer who could see or tell anything",
            "It means Miss Hunter must do the cooking"],
           2,
           "A big house, a locked wing, a dog loose at night, and two servants — one of them usually drunk and the other sour and silent. Whatever is being kept quiet here is being kept quiet by a very short list of people."),
         ),

    item("dress", ["laid upon the bed in your room",
                   "signs of having been worn before",
                   "a better fit if I had been measured for it",
                   "with its back turned towards it"],
         V("What is Miss Hunter asked to do on her third day?",
           ["Take the child out to the lawn",
            "Clean the rooms in the empty wing",
            "Put on the electric blue dress",
            "Read to Mrs. Rucastle in the drawing room"],
           2,
           "The dress is already laid out on her bed when she is asked — the request and the preparation arrive together, which is how everything at this house works."),
         V("What does she notice about the dress itself?",
           ["It was far too large for her",
            "It had plainly been worn before, and fitted her perfectly",
            "It was brand new, and still had the shop label on it",
            "It was the wrong shade of blue entirely"],
           1,
           "Both at once. Somebody else wore this dress, and it fits Miss Hunter as though she had been measured for it — which is a thing to hold on to when you remember that she was chosen on sight."),
         V("How is the chair arranged in the drawing room?",
           ["Facing the fire, away from the door",
            "Close to the central window, with its back to it",
            "In the middle of the room, facing the door",
            "Beside Mrs. Rucastle, at the far end"],
           1,
           "Back to the window. She cannot see out, and anyone outside can see her. Everything that follows — the mirror, the man on the road — comes from that one arrangement."),
         V("What is Mrs. Rucastle doing while her husband tells his funny stories?",
           ["Laughing harder than anybody",
            "Reading quietly by the fire",
            "Sitting with her hands in her lap, looking sad",
            "Out of the room altogether, on some errand"],
           2,
           "He is working hard to make Miss Hunter laugh; his wife sits through it “with a sad, anxious look upon her face” and never smiles once. One of these two people is pretending and the other cannot."),
         V("Put the three together — the borrowed dress, the chair at the window, the laughing. What is the performance for?",
           ["To cheer Mrs. Rucastle up",
            "To test whether Miss Hunter is good company",
            "To be seen from outside the house",
            "To keep the child amused in the next room"],
           2,
           "She is dressed in another woman’s clothes, placed where the window frames her, and made to laugh. Nothing about it is for the people in the room — and Miss Hunter works that out herself two pages later."),
         ),

    item("reading", ["this same performance was gone through",
                     "begged me to read aloud to him",
                     "I read for about ten minutes",
                     "ordered me to cease and change my dress"],
         V("How often does the window performance happen?",
           ["Once only, on her third day",
            "Every morning without fail",
            "Twice — and then it stops",
            "Every evening after the child is in bed"],
           2,
           "The third day, then two days later, and after the man on the road is waved away it never happens again. Two performances, and then the blind comes down for good."),
         V("What does Mr. Rucastle add the second time?",
           ["He asks her to sing",
            "He hands her a novel and asks her to read aloud",
            "He brings the child in to sit beside her chair",
            "He moves the chair to face the window"],
           1,
           "He gives her a book and moves her chair a little sideways. The sideways move is the detail: he is adjusting the picture, not the reading."),
         V("How long does the reading last?",
           ["All afternoon",
            "About an hour",
            "About ten minutes",
            "Until the child woke from his nap"],
           2,
           "Ten minutes, and then he orders her to stop and change. Nobody who wanted a novel read to them stops after ten minutes — the reading is a way of keeping her sitting there, nothing more."),
         V("What word does Miss Hunter use for what Mr. Rucastle does when the reading is over?",
           ["He asked her to change",
            "He suggested that she change",
            "He ordered her to cease and change",
            "He thanked her and left the room"],
           2,
           "Ordered. Everywhere else he is jovial and coaxing; here the mask slips for a word. She reports the exact verb, which is what makes her a good witness."),
         V("Why does Miss Hunter call it a “performance”?",
           ["Because the stories were so well told",
            "Because Mrs. Rucastle treated it as a joke",
            "Because it was staged, and repeated the same way",
            "Because the child watched from the doorway"],
           2,
           "Same dress, same chair, same window, same laughter, done twice “under exactly similar circumstances.” A thing arranged and run through again is a performance, and she names it correctly before she knows why."),
         ),
]


# ====================================================================== 2
S2 = [

    item("mirror", ["turn my face away from the window",
                    "My hand mirror had been broken",
                    "There was nothing",
                    "a small bearded man in a grey suit"],
         V("What does Miss Hunter want to know, and why can she not simply look?",
           ["What is in the locked drawer; it is locked",
            "What is behind her; they always turn her face from the window",
            "What is in the empty wing; the door is barred",
            "Who the child is so frightened of; the boy will not say"],
           1,
           "“They were always careful to turn my face away from the window.” Being carefully prevented from looking is itself a piece of information, and it is what makes her determined to see."),
         V("How does she manage to see behind her?",
           ["She moves the chair when nobody is watching",
            "She asks the child to tell her what is outside",
            "She hides a piece of broken mirror in her handkerchief",
            "She watches the reflection in the window glass instead"],
           2,
           "Her hand mirror had broken, so she keeps a sliver of it in her handkerchief and raises the handkerchief to her eyes in the middle of her laughter. She improvises, and she hides it inside something she is already doing."),
         V("What does she see the first time she looks?",
           ["A man on the road",
            "The mastiff loose on the lawn",
            "Nothing",
            "Toller watching from the kitchen door"],
           2,
           "“There was nothing.” The story lets the trick fail first. It is only at the second glance that she picks the man out — which is what looking properly is like."),
         V("Who is in the road?",
           ["Toller, walking back from the village",
            "A small bearded man in a grey suit",
            "A policeman from Winchester",
            "The child’s former nurse"],
           1,
           "A small bearded man in a grey suit, leaning on the railings and looking earnestly. The road is a busy highway, so a man on it is ordinary — a man stopped and staring at one window is not."),
         V("What makes this man different from anyone else who passes on that road?",
           ["He is dressed a good deal better than the local people",
            "He is standing still, and looking earnestly at her window",
            "He is carrying something under his arm",
            "He waves as soon as he sees her"],
           1,
           "“The road is an important highway, and there are usually people there.” She rules out the ordinary explanation herself before drawing any conclusion, which is exactly how Holmes would have done it."),
         ),

    item("blind", ["her eyes fixed upon me with a searching gaze",
                   "there is a fellow upon the road who stares up at Miss Hunter",
                   "Kindly turn round and motion him to go away",
                   "drew down the blind"],
         V("What does Miss Hunter notice when she lowers the handkerchief?",
           ["That the man in the road had gone",
            "That Mr. Rucastle had stopped telling his funny story",
            "That Mrs. Rucastle’s eyes were fixed on her, searching",
            "That the child had come into the room"],
           2,
           "She catches Mrs. Rucastle watching her at the exact moment she is doing something she should not. The watcher is being watched, and both of them know it."),
         V("What does Mrs. Rucastle say to her husband?",
           ["That Miss Hunter has a mirror",
            "That a fellow on the road is staring up at Miss Hunter",
            "That the blind ought to be drawn",
            "That the blue dress does not suit Miss Hunter at all"],
           1,
           "Notice what she does not say. She has just worked out that Miss Hunter has seen the road, and she reports the man rather than the mirror — she gets the window shut without admitting what she knows."),
         V("What is Miss Hunter told to do about the man?",
           ["To ignore him and go on reading",
            "To go out and ask him his business",
            "To turn round and wave him away",
            "To draw the blind herself"],
           2,
           "And she objects first: “Surely it would be better to take no notice?” She is told again, and does it. The gesture has to come from her, in that dress, at that window."),
         V("What changes after that day?",
           ["She is moved to a different room",
            "The man in the grey suit comes back again every afternoon",
            "She never sits in the window or wears the dress again",
            "Mr. Rucastle stops speaking to her"],
           2,
           "All three at once, and she lists them in one breath. Whatever the performance was for, it was finished the moment that man was waved away."),
         V("Why would waving him away be the point of the whole performance?",
           ["It proves to him that she is happy there",
            "It tells him, in her person, that he should stop coming",
            "It gives Mrs. Rucastle an excuse to shut the blind",
            "It shows the Rucastles that she will obey them"],
           1,
           "A man waits by the railings to see a particular woman at that window. He is shown a woman in her dress, laughing, who turns and waves him off — and he does not come back. He has been answered by someone he thinks is somebody else."),
         ),

    item("carlo", ["the rattling of a chain", "so that he is always keen",
                   "Toller lets him loose every night",
                   "a giant dog, as large as a calf"],
         V("What is kept in the outbuilding near the kitchen door?",
           ["The Rucastles’ carriage horse",
            "Carlo, a mastiff",
            "The photographic equipment",
            "Firewood and garden tools"],
           1,
           "She hears a chain rattling and something large moving before she is shown anything. The dog is introduced by sound first, which is how it is remembered."),
         V("Who is the only person who can handle the dog?",
           ["Mr. Rucastle, who calls him his own",
            "Mrs. Rucastle",
            "Old Toller",
            "Nobody — he is left alone entirely"],
           2,
           "“I call him mine, but really old Toller is the only man who can do anything with him.” Which is worth putting beside the fact that Toller is drunk a good deal of the time."),
         V("Why is the dog fed only once a day, and not much then?",
           ["So that he stays thin enough to run",
            "Because food is short in the house",
            "So that he is always keen",
            "Because he will take food from nobody else"],
           2,
           "Keen means hungry and ready. The dog is kept hungry on purpose, which turns an animal into a thing with a job — and the job is announced in the next sentence."),
         V("What is Miss Hunter warned never to do?",
           ["Go into the empty wing",
            "Open the locked drawer",
            "Set foot outside at night",
            "Speak to anyone on the road"],
           2,
           "“For goodness’ sake don’t ever set your foot over the threshold at night.” Said as kindly advice. It is also, exactly, a way of making sure she cannot leave the house after dark."),
         V("What does she see from her bedroom window two nights later?",
           ["Mr. Rucastle crossing the lawn with a lamp",
            "The man in the grey suit at the railings",
            "A giant dog, as large as a calf, crossing the moonlit lawn",
            "Toller letting somebody in quietly at the kitchen door"],
           2,
           "“That dreadful sight sent a chill to my heart, which I do not think any burglar could have done.” She had been told; seeing it is different, and she says so plainly."),
         ),
]
