# -*- coding: utf-8 -*-
"""Sections 1 and 2 of The Copper Beeches: pages 165 to 167, and 167 to 169.

Nineteen questions over the reading, five versions of each. A version is the
whole question -- its wording, its own four options, its own explanation -- so a
rerun comes at the same fact from a different side.

Class is working on character traits this term, so the traits are asked for by
name where the text supports it, and the last question of the last section is a
summary of Violet Hunter across the whole reading.
"""


def V(q, opts, a, why):
    return {"q": q, "opts": opts, "a": a, "why": why}


def item(p, hi, *vs):
    return {"type": "pick", "p": p, "hi": hi, "vs": list(vs)}


# ====================================================================== 1
S1 = [

    item("dull", ["emerged in an ill temper", "the days of the great cases are past",
                  "recovering lost pencils", "I have touched bottom at last"],
         V("What sort of mood is Holmes in at the start of the story?",
           ["Cheerful, because a new case has arrived",
            "Thoughtful, and working quietly on an old problem of his own",
            "Out of temper, because nothing interesting is happening",
            "Anxious about a client he is expecting"],
           2,
           "He has spent the whole morning in the advertisement columns and found nothing, and “emerged in an ill temper.” The story opens on a bored man, which is worth remembering when he says later that this problem is the most interesting in months."),
         V("What complaint does Holmes make about criminals?",
           ["That the police catch them too easily now",
            "That they have lost all enterprise and originality",
            "That they have grown far more dangerous",
            "That there are simply fewer of them than there were"],
           1,
           "“Man, or at least criminal man, has lost all enterprise and originality.” It is a complaint about being bored, dressed up as a complaint about the world — and it tells you what Holmes actually wants from his work."),
         V("How does Holmes describe what his practice has come down to?",
           ["Work he is too proud to take on at all",
            "A business that no longer pays its way",
            "An agency for lost pencils and advice to schoolgirls",
            "A series of cases the police have already solved"],
           2,
           "“An agency for recovering lost pencils and giving advice to young ladies from boarding-schools.” Keep the second half of that in mind: a young lady is about to walk in asking for advice, and he has just called it the bottom."),
         V("Which trait of Holmes does this opening page show most clearly?",
           ["He is generous with his time",
            "He is restless, and needs a problem to work on",
            "He is suspicious of almost everyone he meets",
            "He is careless about money"],
           1,
           "Silent all morning, searching the papers, then sour when he finds nothing. The interest is not in the money or the danger — it is in having something to think about, and he is miserable without one."),
         V("Why does the story bother to show Holmes bored before the case begins?",
           ["To explain why he charges Miss Hunter nothing",
            "To show that he is not as clever as he was",
            "So that his interest later means something",
            "To suggest he will refuse to take the case"],
           2,
           "A man who calls this note his “zero point” and then says the problem is the most interesting to come his way in months has moved a long way. The boredom is there so you can measure the change."),
         ),

    item("zero", ["marks my zero point", "a crumpled letter",
                  "a situation that has been offered to me as governess",
                  "half-past ten"],
         V("What does Holmes call the note he received that morning?",
           ["His zero point",
            "A case worth taking at once",
            "The strangest letter he has read",
            "A note he intends not to answer"],
           0,
           "“This note I had this morning marks my zero point, I fancy.” The lowest his work has sunk — and he tosses it across to Watson crumpled, which says what he thought of it."),
         V("What is the writer of the letter asking Holmes to help with?",
           ["Finding a relative who has disappeared",
            "Recovering money she is owed",
            "Whether to accept a job as a governess",
            "A theft from the house where she works"],
           2,
           "“Whether I should or should not accept a situation that has been offered to me as governess.” No crime, no mystery — a woman asking advice about a job offer, which is exactly the work Holmes has just finished sneering at."),
         V("When does the writer say she will call?",
           ["That evening, after dark",
            "At half-past ten the next morning",
            "At noon on the following day",
            "She asks Holmes to write to her instead"],
           1,
           "Half-past ten — and it is half-past ten as Watson reads the letter. She arrives on the minute, which is the first thing the story tells you about her without saying it."),
         V("What does the way she writes tell you about her?",
           ["She is used to giving orders",
            "She writes as somebody who expects to be refused",
            "She is direct, polite, and does not waste words",
            "She is too frightened to say what is wrong"],
           2,
           "Four lines: what she wants, when she will come, and an apology for the trouble. “If I do not inconvenience you.” She states her business and stops, which matches the brisk woman who walks in a page later."),
         V("Holmes calls this note the worst thing in his morning’s post. What is the reader meant to notice?",
           ["That Holmes greatly dislikes writing letters",
            "That he has misjudged it, and will find out",
            "That the letter is badly written",
            "That he has met the writer before"],
           1,
           "He says so on a page that also reminds you how the blue carbuncle began. The story is telling you plainly that his first judgement is wrong, and then letting him find out."),
         ),

    item("whim", ["appeared to be a mere whim at first",
                  "developed into a serious investigation",
                  "It may be so in this case also"],
         V("Which earlier case does Watson bring up?",
           ["The Engineer’s Thumb",
            "The affair of the blue carbuncle",
            "The Red-Headed League, and the pawnbroker",
            "The Speckled Band"],
           1,
           "The blue carbuncle — the goose, the hat and the stone. Watson has learned something from it, and the thing he has learned is the point of mentioning it here."),
         V("What is Watson’s point in mentioning it?",
           ["That Holmes was wrong about the carbuncle too",
            "That the carbuncle case made Holmes famous",
            "That a case which looks like a whim can turn serious",
            "That the police were no help in that case either"],
           2,
           "“Which appeared to be a mere whim at first, developed into a serious investigation. It may be so in this case also.” A hat on a chair became a man facing seven years. Watson is arguing from experience."),
         V("What does this exchange show about how the two men work together?",
           ["Watson usually sees further than Holmes does",
            "Watson pushes back, and Holmes listens",
            "Holmes refuses to discuss cases with Watson",
            "They agree on almost everything"],
           1,
           "Holmes has written the letter off; Watson says wait. It is the same job Watson did over the hat, when he called the whole thing a waste of energy — he is the one who makes Holmes say out loud why he thinks what he thinks."),
         V("Who turns out to be right, Holmes or Watson?",
           ["Holmes — the case stays trivial throughout",
            "Watson — Holmes calls it the most interesting case in months",
            "Neither — the case is never solved",
            "Holmes — he refuses to take the case, and is proved right"],
           1,
           "Ten pages later Holmes tells Miss Hunter her problem “promises to be the most interesting that has come my way for some months.” Watson said it would be, and it was."),
         V("What is a reader meant to do with this reminder of an earlier case?",
           ["Skip ahead to see how this one ends",
            "Expect the two cases to have the same solution",
            "Take the small, odd details in this one seriously",
            "Assume Miss Hunter is not telling the truth"],
           2,
           "In the carbuncle it was a hat nobody wanted. Here it will be a dress, a chair, and a haircut. The story is teaching you how to read it: the trivial detail is where the case is."),
         ),
]


# ====================================================================== 2
S2 = [

    item("violet", ["plainly but neatly dressed",
                    "make her own way in the world",
                    "no relations from whom I could ask advice",
                    "favorably impressed"],
         V("How is Miss Hunter described when she comes in?",
           ["Expensively dressed, and sure of herself",
            "Plainly but neatly dressed, with a bright, quick face",
            "Pale and frightened, hardly able to speak",
            "Older than Holmes had expected her, and very grave"],
           1,
           "Plain and neat, bright and quick, freckled. Not a rich client and not a helpless one — Watson's description tells you her situation and her character in one sentence."),
         V("What does Watson mean by “the brisk manner of a woman who has had to make her own way in the world”?",
           ["That she is rude to people she does not know",
            "That she has supported herself, and it shows",
            "That she walks very quickly",
            "That she has travelled a great deal"],
           1,
           "Nobody has done it for her. The briskness is what five years of earning her own living has made of her, and Watson can see it before she has said twenty words."),
         V("Why has she come to a stranger for advice?",
           ["Her employer told her to consult Holmes",
            "She suspects a crime has been committed",
            "She has no relations she could ask",
            "She has read about Holmes in the newspapers"],
           2,
           "“As I have no relations from whom I could ask advice.” She is entirely alone, which is the thing that makes the rest of the story possible — and which she states plainly rather than complaining about."),
         V("How does Holmes receive her?",
           ["Coldly, since he had called her letter his zero point",
            "He is favorably impressed by her manner",
            "He keeps her waiting while he finishes the papers",
            "He tells her at once that he cannot help"],
           1,
           "“I could see that Holmes was favorably impressed by the manner of his new client.” The man who was sour about schoolgirls asking advice rises to greet her and offers her a chair. The person, not the letter, changes his mind."),
         V("Which two traits does this first description give Miss Hunter?",
           ["Wealth and confidence",
            "Nervousness and suspicion",
            "Independence and good sense",
            "Pride and bad temper"],
           2,
           "She makes her own living and she knows when to ask for help — and she asks the right person. Watch how those two hold up through the rest of the reading, because they are tested on every page."),
         ),

    item("situation", ["a governess for five years", "Colonel Spence Munro",
                       "without a situation", "at my wits’ end"],
         V("How long had Miss Hunter been a governess, and for whom?",
           ["Two years, for Mr. Rucastle",
            "Five years, for Colonel Spence Munro",
            "Ten years, for several families",
            "One year, in her first position"],
           1,
           "Five years with one family. She is experienced and she stayed, which tells you she was good at it and that they wanted to keep her."),
         V("Why did she lose her position?",
           ["She was dismissed after a disagreement",
            "She left to care for a relative",
            "The Colonel took a post in Nova Scotia and took the children",
            "The family could no longer afford to keep a governess at all"],
           2,
           "Nothing to do with her. The family went to America and the job went with them, which is worth noticing — the story is careful that her trouble is bad luck rather than any fault of hers."),
         V("What had she done about finding another position?",
           ["Waited for the family to send for her",
            "Advertised, without success",
            "Written to every family she knew",
            "Nothing — she had savings to live on"],
           1,
           "“I advertised, but without success.” She tried the obvious thing first and it failed. The agency and then the interview are what she does next, which is the shape of the whole first half of her story."),
         V("What state were her finances in by the time she reached Westaway’s?",
           ["Comfortable, with a year’s savings",
            "She had enough to last the winter",
            "Her savings were running short and she was at her wits’ end",
            "She was still being supported by Colonel Spence Munro"],
           2,
           "Her savings running out and no work. Remember it: every strange condition she is about to be offered has to be weighed against an empty cupboard, and the story makes sure you know that first."),
         V("Why does the story give her money troubles before the offer is made?",
           ["To show she is bad with money",
            "To explain why she accepted the job",
            "To make the reader doubt her account",
            "To explain why she cannot pay Holmes"],
           1,
           "A hundred pounds a year means nothing until you know she has two bills on the table and little in the cupboard. Her decision looks foolish without that and reasonable with it, and Doyle puts it first on purpose."),
         ),

    item("agency", ["a well-known agency for governesses called Westaway’s",
                    "it is really managed by Miss Stoper",
                    "A very stout man with a smiling face, and a heavy chin",
                    "I could not ask for anything better"],
         V("What is Westaway’s?",
           ["The house where she had been a governess",
            "An agency that finds positions for governesses",
            "The firm that employed Colonel Spence Munro",
            "The newspaper where she placed her advertisement"],
           1,
           "An agency, called after its founder but run by Miss Stoper. Governesses waited in an outer room to be shown in one at a time — which is how a stranger comes to be sitting there watching them arrive."),
         V("Who was sitting at Miss Stoper’s elbow when Miss Hunter was shown in?",
           ["Another governess, waiting her turn to be seen",
            "Mr. Westaway, the founder",
            "A clerk writing in the ledgers",
            "A very stout man with a heavy chin and glasses"],
           3,
           "A stranger, in the office where the employer should not be, “looking very earnestly at the ladies who entered.” He is inspecting them as they come in, one by one."),
         V("What did the stout man do the moment she came in?",
           ["He rose and introduced himself politely",
            "He gave a jump in his chair and said “That will do”",
            "He asked Miss Stoper to show him all of her ledgers",
            "He looked away and said nothing at all"],
           1,
           "“That will do; I could not ask for anything better. Capital!” Before a word has passed between them. He has decided on sight, which means he was looking for something he could see."),
         V("What is odd about his deciding before she has spoken?",
           ["It means he had met her somewhere before",
            "It means Miss Stoper had recommended her",
            "It means he wants something about her appearance",
            "It means that he was in a great hurry to leave"],
           2,
           "An employer hiring a governess asks about teaching. This one jumps in his chair at the sight of her and asks about salary. Everything he later insists on — the dress, the chair, the hair — is about how she looks."),
         V("Which detail of this scene turns out to matter most later?",
           ["That the agency is named after its founder",
            "That the ladies waited in an outside room",
            "That Miss Stoper consults her ledgers",
            "That he chose her by looking at her"],
           3,
           "He is not hiring a teacher. He is choosing someone who will do for a purpose he has not mentioned, and the choosing is done with his eyes before she has opened her mouth."),
         ),
]
