# -*- coding: utf-8 -*-
"""Sections 3 and 4 of The Copper Beeches: pages 170 to 172, and 173 to 174.

The offer and the refusal. These two sections are where the character work is
thickest: a man who keeps raising the price every time she hesitates, and a
woman who turns down four times her old salary over a haircut and then has to
live with it in a room with nothing in the cupboard.
"""
from beech_q12 import V, item


# ====================================================================== 3
S3 = [

    item("salary", ["four pounds a month", "so pitiful a sum",
                    "the bearing and deportment of a lady",
                    "a hundred pounds a year"],
         V("What had Miss Hunter been paid in her last position?",
           ["Rather more than most governesses got",
            "Thirty pounds a quarter",
            "Four pounds a month",
            "She does not say what it was"],
           2,
           "Four pounds a month — about forty-eight pounds a year. Hold the number: everything the stranger offers has to be measured against it."),
         V("How does the stout man react to that figure?",
           ["He says it is a fair wage for the work",
            "He calls it a pitiful sum and throws his hands in the air",
            "He says that he can offer her only a little more than that",
            "He asks what her duties had been for it"],
           1,
           "“How could anyone offer so pitiful a sum to a lady with such attractions and accomplishments?” He is insulting her last employer to flatter her, and she has not asked him for anything."),
         V("What does he say is the real question about a governess?",
           ["What she can teach, and how well",
            "How long she stayed in her last position",
            "Whether she has the bearing and deportment of a lady",
            "Whether she is willing to live far from London"],
           2,
           "“Have you or have you not the bearing and deportment of a lady? There it is in a nutshell.” Bearing and deportment — how she carries herself. Not one word about lessons, in the whole interview."),
         V("What salary does he finally name?",
           ["Forty pounds a year",
            "Four pounds a month, as before",
            "A hundred pounds a year",
            "Thirty pounds a quarter"],
           2,
           "A hundred a year — more than double what she had. She says later that few governesses in England get it, and she is right, which is exactly what should have worried her."),
         V("When Miss Hunter says her accomplishments may be less than he imagines, what does he do?",
           ["Asks her to list them in detail",
            "Waves it aside as beside the question",
            "Lowers the salary he had offered",
            "Says he will test her on them"],
           1,
           "“Tut, tut! This is all quite beside the question.” She is being honest about what she can do and he does not want to hear it — because her accomplishments are not what he is buying."),
         ),

    item("advance", ["destitute as I was", "opened a wallet and took out a note",
                     "half their salary beforehand",
                     "something unnatural about the whole transaction"],
         V("What does the stout man offer when he sees her look of disbelief?",
           ["To put the offer in writing",
            "To let her meet the child first",
            "Half her salary in advance",
            "To pay her travelling costs himself"],
           2,
           "He opens a wallet and takes out a note. “It is also my custom to advance to my young ladies half their salary beforehand.” Fifty pounds, to a woman who has nothing, for work she has not begun."),
         V("What reason does he give for the advance?",
           ["That he always pays before work is done",
            "So she can meet the expenses of her journey and her wardrobe",
            "That the bank is a very long way away from the house itself",
            "To make up for the loss of her hair"],
           1,
           "Journey and wardrobe. Notice the second one: he is already paying for what she will wear, several minutes before he mentions that his wife chooses her dresses."),
         V("What was Miss Hunter’s first reaction to the advance?",
           ["That she had never met so thoughtful a man",
            "That it proved he could not be trusted",
            "That it was less than she had hoped for",
            "That she should ask for the rest as well"],
           0,
           "“It seemed to me that I had never met so thoughtful a man.” She is in debt and somebody has just solved it. The story lets her be grateful before it lets her be suspicious."),
         V("And what did she think on top of that?",
           ["That she would accept at once",
            "That the money would clear every one of her debts entirely",
            "That there was something unnatural about the whole transaction",
            "That he had mistaken her for someone else"],
           2,
           "Both things at once — grateful and uneasy. “Something unnatural about the whole transaction that made me wish to know a little more before I quite committed myself.” That instinct is the best thing about her."),
         V("What trait is she showing by asking more questions when the money is already on the table?",
           ["Greed — she wants a better offer",
            "Caution — she will not be bought past her own judgement",
            "Rudeness — she does not trust a stranger with money",
            "Fear — she expects to be cheated"],
           1,
           "A woman in debt with fifty pounds in front of her keeps asking. It would have been so much easier to take it and stop talking, and she does not."),
         ),

    item("child", ["five miles on the far side of Winchester",
                   "killing cockroaches with a slipper",
                   "startled at the nature of the child’s amusement",
                   "obey any little commands that my wife might give"],
         V("Where is the house, and what is it called?",
           ["Montague Place, in London",
            "The Copper Beeches, five miles beyond Winchester",
            "Westaway’s, near the agency",
            "Nova Scotia, with the Spence Munro family and the children"],
           1,
           "The Copper Beeches, in Hampshire, five miles on the far side of Winchester. The name comes from a clump of trees by the front door, as she finds out when she gets there."),
         V("How does the father describe his six-year-old son?",
           ["As a quiet child who reads a great deal and gives no trouble",
            "As delicate, and often ill",
            "As a dear little romper who kills cockroaches with a slipper",
            "As too young yet to need a governess"],
           2,
           "“Smack! smack! smack! Three gone before you could wink!” He tells it as a joke about his own child, laughing, to a woman he is trying to hire."),
         V("How does Miss Hunter take that description?",
           ["She laughs along with the father",
            "She is startled, but thinks he may be joking",
            "She refuses the position on the spot",
            "She asks to meet the child before deciding"],
           1,
           "“I was a little startled at the nature of the child’s amusement, but the father’s laughter made me think that perhaps he was joking.” She notices and then explains it away — which is what people do when they need the work."),
         V("What does he say her duties will be, besides the child?",
           ["Teaching French and music",
            "Keeping all of the household accounts in order",
            "Obeying any little commands his wife might give",
            "Nothing else at all"],
           2,
           "“Provided always that they were such as a lady might with propriety obey.” The qualification sounds reassuring and is not: he is telling her in advance that she will be asked to do things that need a promise attached."),
         V("Three things in this exchange should worry a reader. Which is NOT one of them?",
           ["A child whose amusement is killing things",
            "Duties that are deliberately left vague",
            "A house in the country five miles from a town",
            "A father who laughs at his son’s cruelty"],
           2,
           "Living in the country is ordinary; a governess post almost always meant living in. The other three are not ordinary, and all three are offered cheerfully, which is what makes them hard to object to."),
         ),
]


# ====================================================================== 4
S4 = [

    item("faddy", ["We are faddy people", "wear any dress that we might give you",
                   "Or to sit here, or sit there",
                   "cut your hair quite short before you come to us"],
         V("What word does the stout man use for his family’s odd requests?",
           ["Rules",
            "Fads — they are faddy people",
            "Traditions",
            "Conditions of employment"],
           1,
           "“We are faddy people, you know – faddy, but kindhearted.” A fad is a harmless little preference. The word is doing a great deal of work, and it is the word he keeps coming back to."),
         V("What three things does he ask her to agree to?",
           ["To teach only in the mornings, to live in, and to travel with them",
            "To wear a dress they give her, to sit where she is told, to cut her hair",
            "To keep accounts, to answer the door, to cut her hair",
            "To wear black, to rise early, to stay indoors"],
           1,
           "Dress, position, hair. Each is asked separately and each sounds smaller than the one before — and together they amount to controlling exactly how she looks and where she can be seen."),
         V("Why does he put the requests in that order?",
           ["He is working through them as he thinks of them",
            "He asks the costly ones first to get them over with",
            "Each small yes makes the next one easier to give",
            "His wife had written the order down for him"],
           2,
           "A dress, then a chair, then her hair. She says yes, yes — and then he asks for the thing he actually came for. By then she has already agreed twice."),
         V("What does “faddy, but kindhearted” do for him?",
           ["It explains why the salary is so high",
            "It makes strange demands sound harmless",
            "It warns her that the family is difficult",
            "It is a joke at his wife’s expense"],
           1,
           "Nobody argues with kindhearted. He is giving her the words to explain the demands away with, and she uses them: she talks herself round twice in the next two pages."),
         V("Which demand is the one he really wants?",
           ["The dress",
            "Where she sits",
            "Her hair",
            "All three equally"],
           2,
           "It is the only one he will not drop. When she refuses, the interview ends — and when he writes again he gives way on nothing else and stays “firm upon this point.”"),
         ),

    item("hair", ["my hair is luxuriant, and of a peculiar tint of chestnut",
                  "quite impossible", "a shadow pass over his face",
                  "I answered firmly"],
         V("What is Miss Hunter’s hair like?",
           ["Cut short already",
            "Fair, and always worn pinned up in a long plait",
            "Luxuriant, and of a peculiar tint of chestnut",
            "Grey before its time"],
           2,
           "Luxuriant and a peculiar chestnut. Peculiar means unusual. It is the one thing about her anyone would describe first — which is the whole reason it is being asked for."),
         V("How does she answer the request to cut it?",
           ["She says she will think it over",
            "She says it is quite impossible, and then firmly refuses",
            "She agrees, since the salary is so high",
            "She asks whether a wig would not do just as well instead"],
           1,
           "“I am afraid that that is quite impossible… No, sir, I really could not,” I answered firmly. Twice, and the second time with no softening at all."),
         V("What does Miss Hunter notice on his face as she refuses?",
           ["A smile he was trying to hide",
            "Nothing — he did not react at all",
            "A shadow passing over it",
            "That he had stopped listening"],
           2,
           "“He had been watching me eagerly, and I could see a shadow pass over his face.” Watching eagerly, before she answers. This matters more to him than anything he has said aloud."),
         V("Whose idea is the haircut supposed to be?",
           ["His own",
            "A little fancy of his wife’s",
            "His daughter Alice’s own",
            "Miss Stoper’s"],
           1,
           "“It is a little fancy of my wife’s, and ladies’ fancies, you know, madam, must be consulted.” He puts it on somebody who is not in the room, which means it cannot be argued with and he need not defend it."),
         V("What does refusing show about her, given what we know of her situation?",
           ["That she does not really need the money",
            "That she is vain about her appearance",
            "That there is a line she will not cross for money",
            "That she did not believe the offer was real"],
           2,
           "She has two bills on her table and almost nothing saved, and she is being offered four times her old salary. She says no anyway, firmly, and then has to go home and live with it."),
         ),

    item("stoper", ["lost a handsome commission", "it seems rather useless",
                    "She struck a gong", "what use was my hair to me"],
         V("How does Miss Stoper behave after the refusal?",
           ["She takes Miss Hunter’s side against the gentleman",
            "She is annoyed, and says it is useless keeping her name",
            "She offers to find her another position at once",
            "She says nothing at all about it"],
           1,
           "She glances up “with such annoyance on her face” that Miss Hunter suspects she has lost a handsome commission. The agency is paid when a place is filled, so the refusal costs her money."),
         V("How does the interview end?",
           ["Miss Stoper strikes a gong and Miss Hunter is shown out",
            "The gentleman apologises and leaves",
            "Miss Hunter changes her mind and accepts",
            "Miss Stoper agrees to go on looking for something else"],
           0,
           "A gong, and out. Nothing is said about finding her anything else — in fact she is told she can hardly expect them to exert themselves. She has made an enemy of the agency by having a limit."),
         V("What does Miss Hunter find when she gets back to her lodging?",
           ["A letter from Colonel Spence Munro",
            "Little in the cupboard and two or three bills on the table",
            "A note from Mr. Rucastle already waiting on the table",
            "That her rent had been paid for her"],
           1,
           "An empty cupboard and bills. The story puts this straight after the refusal on purpose: it shows you exactly what the principle cost, in the same hour she paid it."),
         V("How does she come to feel about her refusal over the next two days?",
           ["More certain than ever that she was right",
            "That she had done a very foolish thing",
            "That she should report the man to the police",
            "That the offer had never been serious"],
           1,
           "By the next day she was inclined to think she had made a mistake, “and by the day after I was sure of it.” Hunger is an argument, and she says so honestly instead of pretending she was brave all through."),
         V("“Besides, what use was my hair to me?” What is she doing in that sentence?",
           ["Telling Holmes she never liked her hair",
            "Explaining why the first refusal was right",
            "Talking herself out of her own objection",
            "Repeating something Miss Stoper had said"],
           2,
           "She is arguing herself round, and she knows it well enough to repeat the argument to Holmes. The honesty of telling him how she changed her mind is what makes her worth believing about everything else."),
         ),
]
