# -*- coding: utf-8 -*-
"""Chapters 1 and 2 of The Blue Carbuncle: pages 126 to 130, and 131 to 132.

Five versions of every question, as in the last section. The five are five
angles on one fact rather than five rewordings of one sentence -- what happened,
what it rests on, what it shows about the person, what would follow if it had
gone the other way.

This story is nearly all conversation between two men about an object, so the
character questions are the point rather than a garnish: what Holmes thinks is
worth his time, what Watson can and cannot do, and how much of a stranger can be
read off a hat he has never worn.
"""


def V(q, opts, a, why):
    return {"q": q, "opts": opts, "a": a, "why": why}


def item(p, hi, *vs):
    return {"type": "pick", "p": p, "hi": hi, "vs": list(vs)}


# ====================================================================== 1
CH1 = [

    item("calling", ["the second morning after Christmas", "a purple dressing gown",
                     "a very seedy felt hat", "studying the hat"],
         V("When does Watson call on Holmes, and why?",
           ["On Christmas morning, having been sent for",
            "On the second morning after Christmas, to wish him the season’s compliments",
            "On Boxing Day, to bring him a case of his own",
            "On the second morning after Christmas, to have a wounded hand dressed"],
           1,
           "A social call, not a case. That matters: nobody has hired Holmes, nobody has reported a crime, and he has spent the morning on a hat anyway."),
         V("What is Holmes doing when Watson arrives?",
           ["Writing up the notes of an old case",
            "Reading the morning papers at his desk",
            "Lounging on the sofa, apparently studying a battered hat",
            "Out, with the hat left behind on the chair for Watson to see"],
           2,
           "Purple dressing gown, crumpled papers, and objects laid out on the chair beside a seedy felt hat. Watson works out what Holmes has been doing before Holmes says a word — he is better at this than he gives himself credit for."),
         V("What is hanging on the wooden chair beside the couch?",
           ["A goose, wrapped in paper",
            "Holmes’s own hat and stick",
            "A parcel that has only just been delivered",
            "A very seedy felt hat, much the worse for wear"],
           3,
           "“Much the worse for wear.” The whole story comes out of this one shabby object, and the reader is shown it in the second sentence, before anybody explains it."),
         V("Watson says, “You are engaged; perhaps I interrupt you.” What does Holmes’s answer tell you about the two of them?",
           ["That he would rather be left alone to think",
            "That he is glad of someone to talk his results through with",
            "That he has been waiting all morning for Watson to arrive",
            "That he does not think the problem worth discussing"],
           1,
           "“I am glad to have a friend with whom I can discuss my results.” Holmes does not need help; he needs an audience to reason at. That is the job Watson does in almost every one of these stories."),
         V("From the very first page, what is the difference between what Watson notices and what Holmes has been doing?",
           ["Watson notices nothing until Holmes points it out",
            "Watson sees the room clearly; Holmes has been reading the hat",
            "Watson has already guessed the owner of the hat",
            "Watson is interested in the goose and Holmes in the hat"],
           1,
           "Watson is an excellent observer — the gown, the papers, the chair, the objects on the seat. What he does not do is turn what he sees into conclusions, and Holmes tells him so outright a few pages later."),
         ),

    item("nocrime", ["No crime", "whimsical little incidents",
                     "four million human beings", "an intellectual problem"],
         V("Watson supposes the hat will lead to the solving of a mystery and the punishment of a crime. What does Holmes say?",
           ["That the crime is a small one, and hardly worth pursuing",
            "That there is no crime in it at all",
            "That the crime will not be known for some days yet",
            "That a crime has been committed but nobody has reported it"],
           1,
           "“No, no. No crime,” said Sherlock Holmes, laughing. Remember that he says this, and remember when the door flies open at the end of the reading."),
         V("What does Holmes call the business of the hat and the goose?",
           ["A trifle beneath his notice",
            "A case he has taken on for a fee",
            "One of those whimsical little incidents of a crowded city",
            "A puzzle sent to him by the police at Scotland Yard"],
           2,
           "“Only one of those whimsical little incidents that will happen when you have four million human beings all jostling each other within the space of a few square miles.” Four million people bumping into each other: the city itself is what produces the problem."),
         V("A billycock, as the reader’s glossary has it, is what?",
           ["A walking stick with a curved handle",
            "A man’s felt hat",
            "A uniformed doorman or messenger",
            "A card tied to a parcel"],
           1,
           "A man’s felt hat. Holmes uses the word to put the object down and then picks it straight back up: not a battered billycock, but an intellectual problem — the same thing, looked at differently."),
         V("“Look upon it, not as a battered billycock, but as an intellectual problem.” What is Holmes asking Watson to do?",
           ["To find out who made the hat",
            "To stop thinking about the goose",
            "To treat a worthless object as worth reasoning about",
            "To guess the owner’s name from the initials inside"],
           2,
           "Nothing about the hat changes. What Holmes is asking Watson to change is his own attention — which is the whole argument of this chapter, and the thing Watson keeps failing to do."),
         V("Holmes says there is no crime, and spends the morning on it anyway. What does that tell you about him?",
           ["He has no other work at present",
            "He takes on small problems to keep himself amused between real cases",
            "A problem interests him because it is a problem, not because it is a crime",
            "He is hoping a crime will turn up in it later"],
           2,
           "He calls it trivial in the same breath as interesting and even instructive. Later in the reading Watson complains it is a waste of energy; by then Holmes has drawn a portrait of a stranger from a hat, which is exactly the return he was after."),
         ),

    item("street", ["four o’clock on Christmas morning", "Tottenham Court Road",
                    "carrying a white goose slung over his shoulder",
                    "smashed the shop window behind him"],
         V("Who is Peterson, and where was he at four o’clock on Christmas morning?",
           ["A policeman, on his beat in Goodge Street",
            "A shopkeeper, closing up on Tottenham Court Road",
            "A commissionaire, walking home from a small party",
            "A cab driver, waiting at the corner for a fare"],
           2,
           "A commissionaire — a uniformed doorman or messenger — whom Holmes calls a very honest fellow, on his way home down Tottenham Court Road. His uniform is about to matter a great deal."),
         V("What did Peterson see in front of him in the street?",
           ["Two men fighting over a parcel",
            "A tallish man carrying a white goose over his shoulder",
            "A group of thugs breaking a shop window",
            "A man running away down the street with a hat in his hand"],
           1,
           "A tallish man, walking with a slight stagger, with a goose slung over his shoulder. The stagger is worth holding on to — Holmes later reasons his way to drink from the hat alone, without having seen the man at all."),
         V("What started the row at the corner of Goodge Street?",
           ["The stranger struck one of the thugs with his stick",
            "The stranger tried to sell the goose to them",
            "Peterson called out to the stranger to stop",
            "A group of thugs set on the stranger"],
           3,
           "“A row broke out between this stranger and a group of thugs.” One of them knocked his hat off, and only then did he raise his stick — the order of events matters if you are deciding who was at fault."),
         V("How did the shop window come to be smashed?",
           ["A thug threw the stranger’s hat through it",
            "The stranger swung his stick over his head and struck it",
            "Peterson was pushed against it in the struggle",
            "The thugs broke it as they ran off down the street"],
           1,
           "He raised his stick to defend himself and, swinging it over his head, smashed the window behind him. He is unlucky rather than violent — and now he has a broken window to answer for as well."),
         V("Why is it useful to the story that all of this happens at four o’clock on Christmas morning?",
           ["The shops would all have been shut at that hour",
            "It explains why nobody else saw what happened",
            "It gives the man a reason for carrying a goose home",
            "It proves that the man had been at a party too"],
           2,
           "A man carrying a goose through the streets before dawn on Christmas Day is carrying home the Christmas dinner. That is what makes the card on its leg, and later the peace-offering to his wife, fit together."),
         ),

    item("fled", ["shocked at seeing an official-looking person in uniform",
                  "dropped his goose, took to his heels",
                  "the spoils of victory", "There lies the problem"],
         V("Why did the stranger run away from Peterson?",
           ["He had recognised Peterson from somewhere",
            "He took him for a policeman coming for him",
            "He was afraid the thugs would follow him",
            "He had no money to pay for the broken window"],
           1,
           "“Shocked at seeing an official-looking person in uniform rushing towards him.” Peterson was running to help. A man who bolts from a uniform is a man who does not want to be asked questions — and he had just broken a window."),
         V("What did the stranger leave behind him?",
           ["His hat and his walking stick",
            "The goose and the card tied to its leg",
            "His hat and the goose",
            "Nothing — he took the goose and dropped only his hat"],
           2,
           "The hat had already been knocked off; then “dropped his goose, took to his heels.” Everything Holmes reasons from for the next five pages was left in the street by a man in a hurry."),
         V("Holmes calls the hat and the goose “the spoils of victory.” Why is that phrase a joke?",
           ["Peterson had not fought anybody for them",
            "The goose was not worth very much",
            "Peterson had to give them both back at once",
            "The hat was too battered to be worth keeping"],
           0,
           "Everyone ran — the stranger and the thugs alike — and Peterson was left standing in the street with a hat and a goose he did not want. He won a battle nobody fought."),
         V("Watson asks whether Peterson restored the hat and goose to their owner. What is Holmes’s answer?",
           ["That the owner refused to take them back",
            "That there lies the problem",
            "That Peterson could not be troubled to try",
            "That he advertised for the owner and got no reply"],
           1,
           "“There lies the problem.” An honest man cannot return lost property to a man he cannot name — and finding the name is the intellectual problem Holmes has set himself."),
         V("Three people run away in this scene. What does the story get out of that?",
           ["It shows how dangerous the streets were at night",
            "It leaves an honest man holding clues nobody claims",
            "It shows that Peterson was braver than the others",
            "It explains why the police were never called"],
           1,
           "If the stranger had stayed, there would be no story: he would have picked up his hat and gone home. The whole case exists because the only person who did not run was the one person with no interest in any of it."),
         ),

    item("baker", ["For Mrs. Henry Baker", "the initials ‘H.B.’",
                   "thousands of Bakers and hundreds of Henry Bakers",
                   "eaten without delay"],
         V("What was printed on the card tied to the goose’s leg?",
           ["“For Mrs. Henry Baker”",
            "“H.B., Tottenham Court Road”",
            "“A Merry Christmas from H.B.”",
            "“For Mr. Henry Baker, with thanks”"],
           0,
           "For Mrs. Henry Baker — his wife, not himself. Holmes uses that card twice: once to explain why the goose cannot be returned, and once to prove the man is not a bachelor."),
         V("What is written inside the hat?",
           ["A maker’s name and a London address",
            "The initials “H.B.”",
            "The single word “Baker”",
            "Nothing at all that can be read"],
           1,
           "The initials H.B., legible on the lining. Two clues that agree with each other — and together they are still not enough to find one man."),
         V("Why can Holmes not simply return the property to Henry Baker?",
           ["Because the card gives no address to send it to",
            "Because the initials in the hat might belong to anyone",
            "Because there are hundreds of Henry Bakers in London",
            "Because Peterson has already eaten the goose"],
           2,
           "“Thousands of Bakers and hundreds of Henry Bakers in this city.” A name is not an identification in a city of four million — which is why the hat, and not the card, is the interesting object."),
         V("What became of the goose?",
           ["It is still waiting at Baker Street for its owner",
            "Peterson took it home to be eaten before it spoiled",
            "It was given away to a neighbour on Christmas Day",
            "Holmes sent it back to the shop it came from"],
           1,
           "“The goose we retained until there were signs that it should be eaten without delay.” A small practical detail, and the story turns on it: Mrs. Peterson is about to prepare that bird."),
         V("Holmes keeps the hat and lets the goose go. What does that choice say about how he works?",
           ["The goose was of no value to anybody",
            "He expected the owner to come back for the hat",
            "A worn object carries more about its owner than a new one",
            "He had already learned all that he could from the goose"],
           2,
           "A goose is a goose. A hat has been worn by one man for three years and has taken the marks of everything he has done in that time — so it is the hat he keeps, and the hat that fills the next four pages."),
         ),
]


# ====================================================================== 2
CH2 = [

    item("lens", ["Only as much as we can deduce", "Here is my lens",
                  "You know my methods", "this old battered felt"],
         V("Did Henry Baker advertise for his lost hat and goose?",
           ["Yes, in all the morning papers",
            "No",
            "Yes, but only after Christmas had passed",
            "He advertised for the goose but not the hat"],
           1,
           "A flat no. He lost his Christmas dinner and did not ask for it back — which, once the reading is over, is worth thinking about as hard as anything in the hat."),
         V("With no advertisement, what has Holmes got to work from?",
           ["Only as much as can be deduced from the hat",
            "The card on the goose and nothing else",
            "Peterson’s description of the man in the street",
            "The newspapers piled up beside his couch"],
           0,
           "“Only as much as we can deduce.” No witness worth questioning, no name worth tracing. Everything from here to the end of the chapter comes out of one object."),
         V("Holmes hands Watson the lens and says, “You know my methods.” What is he doing?",
           ["Testing whether Watson has been paying attention",
            "Admitting he can make nothing of the hat himself",
            "Asking Watson to check a conclusion he has reached",
            "Giving Watson a chance to try the method himself"],
           3,
           "It is an invitation, not a trap — he hands over the lens and the hat both. Watson gets the same evidence and the same tool as Holmes, and that is what makes the next page a fair comparison."),
         V("Watson asks, “What can you gather from this old battered felt?” What does the question show?",
           ["That he is certain there is nothing in it",
            "That he has already noticed the ink stains",
            "That he thinks Holmes is teasing him",
            "That he wants the hat returned to its owner"],
           2,
           "“But you are joking.” Watson does not disbelieve in the method; he disbelieves in this hat. He has seen Holmes do it before and still cannot credit that a battered felt will do."),
         V("What exactly does Holmes ask Watson to gather from the hat?",
           ["The name and address of its owner",
            "The individuality of the man who has worn it",
            "The shop in London where it was bought",
            "How long ago the man lost it in the street"],
           1,
           "“The individuality of the man who has worn this article.” Not his name — his character. That is a much stranger thing to claim you can read off a hat, and it is what Holmes proceeds to do."),
         ),

    item("describe", ["very ordinary black hat", "lining had been of red silk",
                      "pierced in the brim for a hat securer",
                      "smearing them with ink"],
         V("How does Watson describe the shape and condition of the hat?",
           ["A tall silk hat, carefully kept",
            "A soft brown hat, almost new",
            "An ordinary black hat of the usual round shape, much worn",
            "A hat so damaged that its shape could not be made out"],
           2,
           "Ordinary, round, hard, much the worse for wear. Every word of Watson’s description is accurate — and every word of it is also one of Holmes’s clues, which is the joke of the whole chapter."),
         V("What does Watson notice about the lining?",
           ["It had been red silk, and was discoloured",
            "It carried the maker’s name in gold",
            "It had been torn out and replaced",
            "It was stained with lime-cream and hair oil"],
           0,
           "Red silk, gone discoloured. Watson records it and stops there; Holmes takes the same lining, puts the lens on its lower part, and gets a barber, a hair cream and a middle-aged man out of it."),
         V("What is missing from the brim?",
           ["The maker’s stamp",
            "A band of ribbon",
            "The elastic of a hat securer",
            "A row of stitching along the edge"],
           2,
           "“Pierced in the brim for a hat securer, but the elastic was missing.” Watson sees a hole and a missing elastic. Holmes sees a man who once took trouble and has stopped taking it."),
         V("Somebody has smeared ink on the hat. Why?",
           ["To write the initials H.B. on the lining",
            "To mark the hat as belonging to Henry Baker",
            "To hide the discoloured patches on the felt",
            "By accident, while carrying it under his arm"],
           2,
           "“Some attempt to hide the discolored patches by smearing them with ink.” Watson reports the attempt; Holmes reads it as a man who still minds how he looks, which is the kindest thing anyone says about Henry Baker."),
         V("Watson’s description of the hat is completely accurate. Why is it still no use to him?",
           ["He has left out the dust and the wax stains entirely",
            "He describes the hat without asking what each thing means",
            "He has not used the lens Holmes gave him",
            "He is describing the wrong part of the hat"],
           1,
           "He lists: round, hard, worn, red silk, no maker, initials, pierced brim, no elastic, cracked, dusty, spotted, inked. It is a complete inventory of the evidence and he ends it by saying “I can see nothing.”"),
         ),

    item("reason", ["I can see nothing", "you can see everything",
                    "You fail, however, to reason from what you see",
                    "a few inferences that are very distinct"],
         V("What does Watson say when he hands the hat back?",
           ["That he can see nothing",
            "That he can see only the initials",
            "That the hat tells him its owner was poor",
            "That he would rather hear Holmes’s conclusions"],
           0,
           "“I can see nothing,” said I, handing it back — immediately after describing the hat in eleven separate particulars. He does not realise he has just read out the answer."),
         V("What is Holmes’s reply, and what does it mean?",
           ["That Watson is not looking closely enough",
            "That Watson needs the lens to see properly",
            "That Watson sees everything but does not reason from it",
            "That there is genuinely nothing at all there to see"],
           2,
           "“On the contrary, Watson, you can see everything. You fail, however, to reason from what you see.” It is the sentence the whole story is built on, and it is a compliment and a correction at once."),
         V("What is the difference Holmes is pointing at?",
           ["Between looking at a thing and looking for a thing",
            "Between seeing a thing and working out what it means",
            "Between using a lens and using the naked eye",
            "Between guessing at a thing and proving it"],
           1,
           "Observation and inference are two separate jobs. Watson is good at the first and does not attempt the second; Holmes does both and only the second one looks like magic."),
         V("How careful is Holmes about how certain his conclusions are?",
           ["He presents every one of them as proved",
            "He says the hat can prove almost nothing",
            "He separates the distinct inferences from the merely probable",
            "He refuses to say anything at all until Watson has tried"],
           2,
           "“A few inferences that are very distinct, and a few others that are at least probable.” He grades his own conclusions before he gives them. Notice which ones he later hedges: the drink, and the wife."),
         V("Holmes says the hat is “less suggestive than it might have been.” Why say so before starting?",
           ["To lower what Watson expects of him",
            "Because he has not finished examining it",
            "Because the hat has been handled by far too many people",
            "Because the evidence is honestly thinner than he would like"],
           3,
           "It would be easy to oversell the hat, and he does the opposite. A man who tells you the evidence is not as good as it might be is a man worth believing about what it does show."),
         ),

    item("list1", ["highly intellectual", "fallen upon evil days",
                   "probably drink", "his wife has ceased to love him"],
         V("What does Holmes say is “of course obvious” about the man?",
           ["That he is a Londoner",
            "That he is highly intellectual",
            "That he is out of work",
            "That he is no longer young"],
           1,
           "Highly intellectual — and the reason turns out to be a great deal funnier and simpler than the word suggests. Hold the question until page 133."),
         V("What does Holmes say about the man’s money?",
           ["That he has never had very much of it",
            "That he was well-to-do three years ago and has since fallen on evil days",
            "That he has come into money in the last three years",
            "That he has always spent everything he earns on keeping up appearances"],
           1,
           "Well-to-do within the last three years, now fallen upon evil days. Two facts in one sentence: he had money, and he has lost it. The hat supplies both."),
         V("What does Holmes think is at work on the man, and how sure is he?",
           ["Illness, and he is certain of it",
            "Some evil influence, probably drink — probable, not certain",
            "Gambling, which he says the hat proves outright",
            "Nothing at all — the man has simply been rather unlucky"],
           1,
           "“Some evil influence, probably drink, at work upon him.” Probably. This is one of the guesses he warned Watson about, reached from a declining fortune and a slipping character together."),
         V("What does Holmes say about the man’s wife, and how does Watson react?",
           ["That she has left him; Watson agrees at once",
            "That she has ceased to love him; Watson protests",
            "That she is dead; Watson asks how he knows",
            "That she manages the household money; Watson says nothing"],
           1,
           "“The obvious fact that his wife has ceased to love him.” “My dear Holmes!” Watson’s protest is the reader’s: that is not the sort of thing a hat can possibly tell you. Two pages later it does."),
         V("Holmes has never met this man. What is remarkable about the list he gives?",
           ["It is all about the man’s appearance",
            "It is all guesswork and he admits as much",
            "It describes the man’s mind, money and marriage from an object",
            "It contradicts what Peterson had actually seen in the street"],
           2,
           "Brains, money, character, marriage — a whole life, from a hat found in the road. Whether you believe it depends entirely on the next two pages, which is exactly where the story puts them."),
         ),

    item("list2", ["retained some degree of self-respect", "leads a sedentary life",
                   "anoints with lime-cream", "unlikely that he has gas in his house"],
         V("What good thing does Holmes still say about the man?",
           ["That he has kept some degree of self-respect",
            "That he is generous with what little he has",
            "That he has never been in trouble with the police",
            "That he is kind to his wife despite everything"],
           0,
           "“He has, however, retained some degree of self-respect.” The word however is doing the work: after the drink and the marriage, Holmes goes out of his way to find something creditable in the man."),
         V("How does Holmes describe the way the man lives?",
           ["A hard worker, out in all weathers",
            "A traveller, rarely at home",
            "A sedentary life, going out little and out of shape entirely",
            "A restless man who can never manage to sit still for long"],
           2,
           "Sedentary, goes out little, out of shape entirely. Notice that this comes from the same hat as the man’s intellect — a hat that has spent most of its life hanging up indoors."),
         V("What does Holmes say about the man’s hair?",
           ["That it is thinning at the crown",
            "That he wears it long and untidy",
            "That it is grizzled, recently cut, and dressed with lime-cream",
            "That it has been dyed in order to hide the grey coming through"],
           2,
           "Grizzled, cut within the last few days, anointed with lime-cream. Three separate facts about a man’s head, from the lower part of a lining — and he explains all three on page 134."),
         V("What is the last thing on Holmes’s list, and why is it the strangest?",
           ["That the man is middle-aged, which anyone might guess",
            "That the man has no gas in his house, which is not about him at all",
            "That the man goes out very little, which the dust had already shown",
            "That the man has grizzled hair, which the lining showed"],
           1,
           "“It is extremely unlikely that he has gas in his house.” Everything else on the list is about the man; this is about his staircase. Holmes throws it in as an afterthought — “also, by the way” — and it is the one Watson cannot let pass."),
         V("“You are certainly joking, Holmes.” “Not in the least.” What does this exchange set up?",
           ["An argument the two of them never settle",
            "Holmes proving each conclusion in turn",
            "Watson going off to find Henry Baker himself",
            "Holmes admitting that he has gone too far"],
           1,
           "Watson has stopped believing, so Holmes stops asserting and starts explaining. Everything in the next two pages is an answer to this one line of doubt, taken in the order Watson asks for it."),
         ),
]
