# -*- coding: utf-8 -*-
"""Sections 3 and 4: pages 151 to 153, and 155 to 156.

Section 3 is Holmes explaining his own trick and then being handed a piece of
luck; section 4 is the turn the whole story has been walking towards. The
questions on section 4 lean on something he read two nights ago: the name James
Ryder was in the newspaper report, and the man standing in the sitting room is
the witness whose account put Horner in the dock.

The reading stops on the brandy. Nothing here goes near page 157, which is where
Ryder is told how the robbery was arranged and who helped him.
"""
from carb3_q12 import V, item


# ====================================================================== 3
S3 = [

    item("wager", ["looked deeply disappointed", "stopped under a lamp and laughed",
                   "a hundred pounds", "beating me on a wager"],
         V("What does Holmes do when the books prove him wrong?",
           ["Argues that the entry must be a mistake",
            "Pays the sovereign and walks off looking disgusted",
            "Asks to look at the rest of the ledger",
            "Admits at once that he had been pretending all along"],
           1,
           "He throws the coin down “with the air of a man whose disgust is too deep for words.” The performance runs to the last second, because the salesman is still watching."),
         V("What does Holmes do a few yards away from the stall?",
           ["Writes down the address in his notebook",
            "Sends Watson back to buy a goose",
            "Stops under a lamp and laughs",
            "Hails a cab for Brixton Road at once"],
           2,
           "He stops under a lamp and laughs — the first moment he is out of sight. The sovereign was the cheapest thing he bought all day."),
         V("What does Holmes say about offering money instead?",
           ["A hundred pounds would have bought the whole ledger outright",
            "A hundred pounds would not have got him as much as the bet did",
            "He had no money with him to offer",
            "Offering money would have been dishonest"],
           1,
           "“If I had put a hundred pounds down in front of him he would not have given me such complete information as was drawn from him by the idea that he was beating me on a wager.” Being paid makes a man careful. Winning makes him talk."),
         V("Why would paying the salesman have worked less well?",
           ["He would have asked for more than a hundred pounds",
            "He would have told the other inquirers as well",
            "A paid man gives you only what you asked for",
            "He would have gone straight to the police"],
           2,
           "Money buys an answer to the question you put. The bet made him produce two books and read out an address nobody had asked him for — complete information, as Holmes calls it."),
         V("What does Holmes conclude from the way the salesman behaved?",
           ["That the salesman had something to hide",
            "That others besides themselves are anxious about the geese",
            "That the geese must after all have come from the country",
            "That the ledger entry had been altered"],
           1,
           "“It is clear from what that surly fellow said that others besides ourselves are anxious about the matter.” He is weighing whether to go to Brixton Road tonight when the answer walks up to the stall behind him."),
         ),

    item("hubbub", ["a little rat-faced fellow", "I’ll set the dog at you",
                    "one of them was mine all the same", "She told me to ask you"],
         V("What interrupts Holmes in the middle of deciding what to do next?",
           ["A policeman asking their business",
            "A row breaking out at the stall they have just left",
            "The salesman calling them back",
            "A carriage that nearly ran the two of them down"],
           1,
           "“His remarks were suddenly cut short by a loud hubbub.” He was about to choose between tonight and tomorrow, and the choice is made for him."),
         V("Who is at the centre of the row?",
           ["A boy who had dropped a crate of birds",
            "A little rat-faced fellow being shouted at",
            "Mrs. Oakshott, come to collect her money",
            "Another salesman from a rival stall"],
           1,
           "A cringing little man under the swinging lamp, with Breckinridge shaking his fists at him. Everything about how he is described — rat-faced, cringing, whining — is doing work."),
         V("What does the little man want?",
           ["To be paid for geese he had delivered",
            "To buy a goose before the stall shut",
            "To get back one goose, which he says was his",
            "To know who had bought the Alpha’s birds"],
           2,
           "“No, but one of them was mine all the same.” One particular bird, out of two dozen — which is a very odd thing to want, and exactly what Holmes has been chasing."),
         V("Why does Breckinridge refuse to deal with him?",
           ["He had never sold the man anything",
            "He had not bought the geese from him",
            "He had already answered him twice",
            "He did not believe the goose was his"],
           1,
           "“Did I buy the geese off you?” He bought them from Mrs. Oakshott and will answer to her. It is a reasonable position, delivered with the offer to set a dog on him."),
         V("What does the little man say when told to ask Mrs. Oakshott?",
           ["That she will not speak to him",
            "That he has not been able to find her",
            "That she told him to ask here",
            "That she has already sold the goose on"],
           2,
           "“She told me to ask you.” He has been sent from one to the other, which is why he has been pestering the stall — and why Breckinridge has been losing his temper with strangers all week."),
         ),

    item("overtake", ["save us a visit to Brixton Road",
                      "all the color had been driven from his face",
                      "a quavering voice",
                      "It is my business to know what other people don’t know"],
         V("Why does Holmes go after the little man?",
           ["To warn him that Breckinridge means to do him harm",
            "Because the man may save them a visit to Brixton Road",
            "Because he recognised him from the hotel",
            "To ask him who Mrs. Oakshott is"],
           1,
           "“Ha, this may save us a visit to Brixton Road.” He was deciding whether to make that journey tonight. The man who has just been thrown out of the stall is a shorter road to the same place."),
         V("How does the little man react when his shoulder is touched?",
           ["He turns white and asks who they are",
            "He shouts for the police at once",
            "He tries to run back towards the stall",
            "He refuses to speak to them at all"],
           0,
           "“All the color had been driven from his face,” and he asks in a quavering voice. He is terrified before a word is said to him — which is not how an honest man behaves about a goose."),
         V("How does Holmes explain himself?",
           ["He says he is acting on behalf of the Countess of Morcar",
            "He says he overheard the questions and may be able to help",
            "He says he is from the police",
            "He says he is a fowl fancier like the salesman"],
           1,
           "Perfectly true, perfectly bland, and it offers the man exactly what he wants. Holmes does not tell a single lie in this conversation — which is worth noticing after the business of the fiver."),
         V("What does Holmes say his business is?",
           ["To find things that other people have lost",
            "To know what other people don’t know",
            "To put right what the police have got wrong",
            "To ask the questions nobody else will ask"],
           1,
           "“My name is Sherlock Holmes. It is my business to know what other people don’t know.” It is a boast, and in the next breath he proves it by reciting the whole chain of the geese."),
         V("What is the effect of Holmes reciting the chain from Mrs. Oakshott to Henry Baker?",
           ["It warns the man that he is suspected",
            "It shows the man that Holmes is already ahead of him",
            "It tells the man something he did not know",
            "It proves Holmes had been following him all evening"],
           1,
           "The man has spent days being sent from one person to another and getting nowhere. Holmes lays the whole route out from memory, and the man’s next words are that he is the very man he has longed to meet."),
         ),
]


# ====================================================================== 4
S4 = [

    item("alias", ["the very man whom I have longed to meet", "My name is John Robinson",
                   "doing business with an alias", "Head attendant at the Hotel Cosmopolitan"],
         V("How does the little man take Holmes’s offer of help?",
           ["He refuses it and hurries away",
            "He asks what it is going to cost him",
            "He says Holmes is the very man he has longed to meet",
            "He pretends not to have understood the question at all"],
           2,
           "Relief, not suspicion — and it is the relief of a man who has been stuck for days. He is so glad to be helped that he gets into a cab with two strangers."),
         V("What name does he give first?",
           ["James Ryder",
            "John Robinson",
            "John Horner",
            "He refuses to give any name"],
           1,
           "“My name is John Robinson,” he answers, “with a sidelong glance.” The glance is the tell, and Holmes does not even pause over it."),
         V("How does Holmes get the real name?",
           ["By saying it is awkward to do business with an alias",
            "By telling him the police already know it",
            "By asking Watson to look through the man’s papers",
            "By naming the hotel he works at"],
           0,
           "“No, the real name,” said Holmes sweetly. No threat and no evidence — he simply declines to accept it, and a blush does the rest."),
         V("Who is the little man?",
           ["Mr. Windigate, host of the Alpha Inn",
            "John Horner, the plumber, out on bail",
            "James Ryder, head attendant at the Hotel Cosmopolitan",
            "A clerk sent round by the Countess of Morcar herself"],
           2,
           "James Ryder. Think back to the newspaper report: Ryder is the man who showed Horner up to the room, was called away, came back and raised the alarm. The witness has turned up chasing a goose."),
         V("Why is it so important that the little man turns out to work at the Hotel Cosmopolitan?",
           ["It explains how he could afford to join a goose club",
            "It means he knew Henry Baker already",
            "It ties the goose to the place the stone was stolen",
            "It shows he had been sent by the Countess"],
           2,
           "Until this moment the chain ran from a stone to a goose to a market. The man hunting that goose works in the building the stone was taken from — and Holmes names his job before Ryder can explain anything."),
         ),

    item("bird", ["take the basket chair", "of that goose",
                  "white, with a black bar across the tail", "quivered with emotion"],
         V("How does Holmes treat Ryder when they reach Baker Street?",
           ["He locks the door and stands over him",
            "He sits him by the fire and offers him a chair",
            "He sends Watson out for a policeman",
            "He accuses him the moment they are inside"],
           1,
           "“You look cold, Mr. Ryder. Pray take the basket chair.” Cheerful, warm, hospitable — and a question about geese. Nothing in the room tells Ryder what is coming."),
         V("Holmes corrects himself: not those geese, but — what?",
           ["Not the geese at all, but the stone",
            "That goose. One particular bird",
            "The goose club at the Alpha",
            "The two dozen sold on December 22"],
           1,
           "“Or rather, I fancy, of that goose.” One word changed, and Ryder learns that Holmes knows he wants a single bird out of twenty-four. That is when he starts to quiver."),
         V("How does Holmes describe the bird?",
           ["Fat, and heavier than the rest",
            "White, with a black bar across the tail",
            "The largest bird in the whole lot",
            "Grey, with one wing clipped"],
           1,
           "A detail Ryder has never given him. Holmes has had the bird in the house, and can describe the one goose in two dozen that Ryder has been hunting across London."),
         V("How does Ryder react to being described his own goose?",
           ["He denies all knowledge of any bird",
            "He asks how Holmes could possibly know",
            "He quivers with emotion and asks where it went",
            "He laughs and says that Holmes has it wrong"],
           2,
           "“Oh, sir, can you tell me where it went to?” He is too far gone in wanting the bird to notice what it means that Holmes can describe it."),
         V("Holmes asks about geese and says nothing about a stone. Why?",
           ["He is not yet certain Ryder is the man",
            "He wants Ryder to give himself away first",
            "He is waiting for Watson to fetch help",
            "He has promised the Countess to keep it quiet"],
           1,
           "Compare the test on Henry Baker two nights ago: Holmes puts an object in front of a man and watches. Baker took the fresh goose. Ryder asks where that one particular bird went."),
         ),

    item("egg", ["It laid an egg after it was dead", "my museum",
                 "shone like a star", "The game’s up, Ryder"],
         V("What does Holmes say the goose did after it was dead?",
           ["Changed hands four times in a week",
            "Laid the prettiest little blue egg that ever was seen",
            "Went to the Alpha Inn and back again",
            "Made a great deal of trouble for everyone who owned it"],
           1,
           "“It laid an egg after it was dead — the prettiest little blue egg that ever was seen.” A joke, and a complete statement of the case. Ryder understands it immediately."),
         V("What does Holmes do next?",
           ["Sends for Inspector Bradstreet",
            "Reads out the newspaper report of the robbery",
            "Unlocks his strong-box and holds up the stone",
            "Asks Ryder to turn out his pockets"],
           2,
           "No accusation and no question — he opens the box and holds the thing up, and it “shone like a star.” The evidence does the talking."),
         V("How does Ryder stand when the stone is held up?",
           ["Quite still, and saying nothing at all to anybody",
            "Glaring, unsure whether to claim it or deny it",
            "With his hands over his face",
            "Pointing at it and crying out"],
           1,
           "“Uncertain whether to claim or disown it.” In that half-second he is still trying to work out which story to tell — which is itself the answer to the question of whether he is guilty."),
         V("What does Holmes say to him?",
           ["“You are under arrest, Ryder.”",
            "“I know everything of it, Ryder.”",
            "“The game’s up, Ryder.”",
            "“Did you take it, Ryder?”"],
           2,
           "“The game’s up, Ryder,” said Holmes quietly — quietly, and then straight on to catching him before he falls in the fire and getting brandy into him. Not triumph; just the end of it."),
         V("What has the reading established by the time the brandy is poured?",
           ["How the stone came to be inside the goose",
            "That Horner has been released from jail",
            "That Ryder is the man behind the whole business",
            "That the Countess has paid out her reward"],
           2,
           "The chain is complete and the man at the end of it is standing in the room. How the stone got into the bird, and what becomes of Horner, is where the story goes next."),
         ),
]
