# -*- coding: utf-8 -*-
"""Sections 1 and 2: pages 147 to 148, and 149 to 150.

Twelve questions over the reading, three to a section, five versions of each.

This part of the story is almost entirely one long piece of handling: Holmes
wants something out of a man who has decided not to give it, and gets it by
making him want to win. So the questions keep coming back to method -- what was
tried, why it failed, what was tried instead, and why that worked.
"""


def V(q, opts, a, why):
    return {"q": q, "opts": opts, "a": a, "why": why}


def item(p, hi, *vs):
    return {"type": "pick", "p": p, "hi": hi, "vs": list(vs)}


# ====================================================================== 1
S1 = [

    item("alpha", ["them’s not our geese", "a salesman in Covent Garden",
                   "Breckinridge is his name"],
         V("What does the landlord of the Alpha say when Holmes praises his geese?",
           ["That he raises them himself behind the inn",
            "That they are not his geese at all",
            "That the goose club was his own idea",
            "That he sold them all before Christmas Eve"],
           1,
           "“But, sir, them’s not our geese.” One sentence, and the goose club stops being the answer and becomes one more link in the chain."),
         V("Where does the landlord get his birds?",
           ["From a farm out beyond Brixton",
            "From a salesman in Covent Garden",
            "From a poultry market near the museum",
            "From a supplier who calls at the inn"],
           1,
           "Two dozen from a salesman in Covent Garden — and he gives the name without being pressed, which is worth comparing with how the next man behaves."),
         V("What is the salesman’s name?",
           ["Windigate",
            "Oakshott",
            "Breckinridge",
            "Robinson"],
           2,
           "Breckinridge. Windigate is the landlord of the Alpha; the other two names belong further along. Keeping them straight is most of the work in this part of the story."),
         V("How much did Holmes have to do to get this out of the landlord?",
           ["He had to pay him for the information",
            "He had to buy beer and admire his geese",
            "He had to say he was working for the police",
            "He had to come back a second time"],
           1,
           "Two glasses of beer and a compliment: “Your beer should be excellent, if it is as good as your geese.” Holmes gets what he wants by letting a man talk about his own business."),
         V("Why does the landlord’s answer send Holmes further on rather than ending the inquiry?",
           ["Because the goose club list had been lost",
            "Because the landlord could not remember Baker",
            "Because the birds came from somewhere else again",
            "Because the landlord refused to say any more"],
           2,
           "Holmes is following the goose backwards: Baker, the club, the inn — and now the inn turns out to be a stop on the road rather than the start of it."),
         ),

    item("stakes", ["seven years in jail", "may but confirm his guilt",
                   "missed by the police", "follow it out to the bitter end"],
         V("What does Holmes say is at the other end of the chain from the goose?",
           ["A stone worth more than twenty thousand pounds",
            "A thief who has got clean away with it",
            "A man who will get seven years in jail",
            "A countess who will pay a thousand pounds"],
           2,
           "“A man who will get seven years in jail, unless we can establish his innocence.” He puts the goose and the sentence in the same sentence on purpose. That is what the chain is for."),
         V("Does Holmes claim the inquiry will clear Horner?",
           ["Yes — he is already certain Horner is innocent",
            "No — he says it may well confirm his guilt instead",
            "Yes — he says the police have got the wrong man",
            "No — he says the question cannot be answered at all"],
           1,
           "“It is possible that our inquiry may but confirm his guilt.” He is following the evidence rather than a side, and he says so before he starts, which is the honest way round."),
         V("What does Holmes say they have that the police have not?",
           ["A witness the police never found",
            "The stone itself, locked in his strong-box",
            "A line of investigation the police missed",
            "The name of the man who sold the goose"],
           2,
           "“A line of investigation that has been missed by the police, and which luck has placed in our hands.” Luck — he does not pretend he was clever to get it. The cleverness is in what he does with it."),
         V("What does Holmes mean by “follow it out to the bitter end”?",
           ["That they will keep going even if it harms Horner",
            "That they will go on until the police stop them",
            "That the work will be unpleasant but brief",
            "That he expects the answer to be a bitter one"],
           0,
           "He has just said the inquiry might confirm Horner’s guilt. Following it to the bitter end means taking the answer whichever way it falls, which is a different promise from promising to save the man."),
         V("What is the first thing the reader is told about Covent Garden Market?",
           ["That it was shut up for the night",
            "That they reached it through a zigzag of slums",
            "That it was crowded even at that hour",
            "That the stalls were all lit by hanging gas flares"],
           1,
           "“We passed through a zigzag of slums to Covent Garden Market.” The story keeps noting what the city is like on the way: frosty air, slums, a boy putting up shutters. It is a cold night and everything is closing."),
         ),

    item("anger", ["I was recommended to you", "Where did you get them from",
                   "a burst of anger", "I shan’t tell you"],
         V("How does Holmes open the conversation with the salesman?",
           ["By saying he had been recommended to him",
            "By telling him he is investigating a robbery",
            "By offering to buy five hundred geese",
            "By asking straight out about Mrs. Oakshott"],
           0,
           "He starts with the weather, then with being recommended by the Alpha’s landlord — a reason to be standing there that has nothing to do with what he wants."),
         V("Which question sets the salesman off?",
           ["Whether he had sold out of geese",
            "Who had recommended him",
            "Where he got the birds from",
            "How many he had sent to the Alpha"],
           2,
           "“Where did you get them from?” Everything before it is answered easily. The one question Holmes actually came to ask is the one that provokes “a burst of anger” — which is itself a piece of information."),
         V("What does the salesman say when Holmes asks plainly who sold him the geese?",
           ["That he cannot remember after so long",
            "That he will not tell him",
            "That he will tell him for a price",
            "That the books have already been put away"],
           1,
           "“Well, then, I shan’t tell you. So now!” Flat refusal. Asking straight has failed, and the next page is Holmes finding another way in."),
         V("Holmes says, “I don’t know why you should be so upset over such a trifle.” What is he doing?",
           ["Apologising for having annoyed him",
            "Pretending the question hardly matters to him",
            "Warning the man that he will go to the police",
            "Admitting that he has come about the robbery"],
           1,
           "He makes the question sound small, so that refusing it looks unreasonable rather than careful. The man takes the bait and starts explaining why he is upset — which is the first thing Holmes learns."),
         V("What has Holmes already learned from the salesman’s temper, before learning anything else?",
           ["That the man is hiding where the geese came from",
            "That somebody else has been asking the same question",
            "That the geese were not sold to the Alpha at all",
            "That the man knows about the stolen stone"],
           1,
           "An honest trader does not lose his temper over where his stock came from — unless he has been asked about it over and over. Holmes says as much a page later: others besides ourselves are anxious about the matter."),
         ),
]


# ====================================================================== 2
S2 = [

    item("pestered", ["as pestered as I am", "there should be an end of the business",
                      "the only geese in the world", "no connection with any other people"],
         V("What reason does the salesman give for being so short-tempered?",
           ["He has been cheated over a delivery",
            "He has been pestered with questions about those geese",
            "He has been working since before dawn",
            "He has sold out of geese and can make no more money"],
           1,
           "“You’d be as upset, maybe, if you were as pestered as I am.” He is not protecting anybody. He is sick of being asked — which tells Holmes that other people want to know too."),
         V("What sort of questions says he has been asked over and over?",
           ["Whether the geese were fresh, and what he paid",
            "Where the geese are, who he sold them to, what he will take for them",
            "Who raised the geese, and whether they were town bred or country",
            "Why the geese cost so much this year"],
           1,
           "Three questions, quoted. Put them beside the little man who turns up at the stall a page later and you can work out who has been doing the asking."),
         V("What does the salesman mean by “one would think they were the only geese in the world”?",
           ["That his geese were the best in the market",
            "That he had sold more geese than anyone",
            "That the fuss over this one lot makes no sense to him",
            "That nobody had asked about any of his other stock"],
           2,
           "To him it is a batch of birds he paid good money for and sold on. He has no idea why anyone should care, and that is exactly why he is useful: he is not hiding anything, he is just annoyed."),
         V("Why does Holmes say he has no connection with the other people who have been asking?",
           ["To make the salesman trust him and talk",
            "Because it is the truth and he says so",
            "To find out who the other people were",
            "To warn him that those people were not honest"],
           0,
           "He is separating himself from whoever has been making the man’s life a misery, so that his own question can start again from nothing. It is true, as it happens, and it is also useful."),
         V("What has Holmes learned that the salesman does not realise he has given away?",
           ["Where the geese came from",
            "That somebody else is hunting the same geese",
            "That the geese were town bred",
            "That the landlord of the Alpha had lied to him"],
           1,
           "The refusal gave him nothing; the complaint gave him a rival. By the end of the scene Holmes says plainly that others besides themselves are anxious about the matter — and within minutes one of them walks up to the stall."),
         ),

    item("bet", ["I have a fiver on it", "country bred", "it’s town bred",
                 "I’ll bet you a sovereign"],
         V("What does Holmes claim to have a bet on?",
           ["That the goose came from Covent Garden",
            "That the bird he ate was country bred",
            "That the salesman could not name his supplier",
            "That the birds were sold before Christmas"],
           1,
           "“I have a fiver on it that the bird I ate is country bred.” There is no bet and there is no fiver. It is a story invented on the spot to give the man something to win."),
         V("How does the salesman answer the claim?",
           ["He refuses to discuss his birds at all",
            "He says he cannot tell one from the other",
            "He says the birds were town bred, and he would know",
            "He says the Alpha’s birds came from the country"],
           2,
           "“All those birds that went to the ‘Alpha’ were town bred.” He has handled fowls since he was a lad, and being doubted about it is more than he can stand."),
         V("What does Holmes do when the salesman insists?",
           ["Says he is satisfied and drops the matter",
            "Offers to bet him a sovereign on it",
            "Asks to see the birds that are left",
            "Says he will ask at another stall instead"],
           1,
           "“But I’ll bet you a sovereign, just to teach you not to be stubborn.” The insult is part of the offer. He is making sure the man cannot walk away from it."),
         V("Why does Holmes argue about where the birds were bred rather than asking about them again?",
           ["Because he genuinely wanted to know their breed",
            "Because the breed would prove who had the goose",
            "Because the salesman had refused the real question",
            "Because the salesman had offered to bet first"],
           2,
           "Straight asking got “I shan’t tell you.” So he stops asking and starts disagreeing, and lets the man prove him wrong — which cannot be done without opening the books."),
         V("The bet is a trick. What does it rely on to work?",
           ["The salesman’s need for the money",
            "The salesman’s pride in knowing his own trade",
            "The salesman’s wish to be rid of them quickly",
            "The salesman’s fear of the police"],
           1,
           "Not greed — a sovereign is nothing to a man with five hundred geese coming in the morning. It is that he has handled fowls since he was a lad and will not be told he is wrong about them."),
         ),

    item("books", ["Bring me the books, Bill", "a great greasy-backed one",
                   "this other page in red ink",
                   "Mrs. Oakshott, 117 Brixton Road – 249"],
         V("What does the salesman call for, to settle the bet?",
           ["The boy who had carried the birds",
            "His books",
            "The last of the geese on the stall",
            "The landlord of the Alpha"],
           1,
           "“Bring me the books, Bill.” He is going to prove it, and proving it means showing Holmes exactly what Holmes came for."),
         V("What are the two books the boy brings?",
           ["A ledger and a book of receipts",
            "A thin volume and a great greasy-backed ledger",
            "A day book and a long list of the club members",
            "Two ledgers, one for each year"],
           1,
           "A small thin volume of suppliers and a great greasy-backed ledger of accounts, laid out under the hanging lamp. The detail of the greasy backing is the sort of thing that makes a scene real."),
         V("How is the thin book arranged?",
           ["By the date each supplier was first used",
            "Alphabetically, with the amounts owed",
            "Country folk on one page, town suppliers in red ink",
            "By the number of birds each supplier had sent him"],
           2,
           "Two lists, and the red ink is for town suppliers. The salesman turns to the red page to prove his point — which is to say, to the half of the book Holmes needed."),
         V("Whose name does Holmes read out, and from where?",
           ["Mr. Windigate, of the Alpha",
            "Mr. Breckinridge, of Covent Garden",
            "Mrs. Oakshott, 117 Brixton Road",
            "Mr. Henry Baker, of the goose club"],
           2,
           "Third name on the red-ink page, with the number 249 pointing into the big ledger: “Mrs. Oakshott, 117 Brixton Road – 249.” An address, which is the next place to go."),
         V("What does the ledger entry under that number say?",
           ["That twelve geese were bought in November",
            "That the account had not been settled",
            "That twenty-four geese went to Mr. Windigate on December 22",
            "That the geese had all been sold on to the Alpha’s goose club"],
           2,
           "“December 22. Twenty-four geese. Sold to Mr. Windigate of the Alpha.” The chain now runs unbroken from Mrs. Oakshott to Henry Baker, and it was handed over by a man who thought he was winning an argument."),
         ),
]
