# -*- coding: utf-8 -*-
"""Sections 1 and 2: pages 137 to 138, and 138 to 140.

Twelve questions over the whole reading, three to a section, five versions of
each. A version is the whole question -- its wording, its own four options and
its own explanation -- so a second run asks the same thing from a different
direction rather than asking the same sentence again.

Section 2 is a newspaper report, which is the most useful kind of passage in the
book for a reader: it is somebody's account of something, and the questions ask
what it actually establishes as against what it only reports.
"""


def V(q, opts, a, why):
    return {"q": q, "opts": opts, "a": a, "why": why}


def item(p, hi, *vs):
    return {"type": "pick", "p": p, "hi": hi, "vs": list(vs)}


# ====================================================================== 1
S1 = [

    item("stone", ["found in its throat", "a brilliant blue stone",
                   "smaller than a bean in size", "It’s the precious stone"],
         V("What does Peterson bring to Baker Street, and where did it come from?",
           ["A card from the goose’s leg, found by his wife",
            "A blue stone, found in the goose’s throat",
            "A ring, found in the pocket of the hat",
            "A letter, found pushed under his door"],
           1,
           "His wife found it while preparing the bird. The goose Holmes gave away to be eaten turns out to have been carrying the thing the whole story is about."),
         V("How does the reader describe the stone itself?",
           ["As large and heavy, about the size of a walnut and dull",
            "As dull until it was cleaned",
            "As smaller than a bean, twinkling like an electric point",
            "As a deep ruby red, cut into facets"],
           2,
           "“Smaller than a bean in size, but of such purity and radiance that it twinkled like an electric point.” An electric point was a new and startling kind of brightness in 1890 — the comparison is doing real work."),
         V("Peterson says, “A diamond, sir! A precious stone!” What does Holmes correct him with?",
           ["That it is coloured glass, and worth nothing at all",
            "That it is a ruby rather than a diamond",
            "That it is not a diamond but a carbuncle",
            "That it is not a precious stone but the precious stone"],
           3,
           "“It’s more than a precious stone. It’s the precious stone.” One word of difference, and it turns a lucky find into the thing every newspaper in London has been writing about."),
         V("Who names the stone, and what does that tell you about him?",
           ["Watson — he has been following the case in the papers",
            "Holmes — he had recognised it at once by its shape",
            "Peterson — his wife had read about it",
            "Nobody — Holmes has to send for a jeweller"],
           0,
           "“Not the Countess of Morcar’s blue carbuncle?” I blurted. Watson gets there first, out loud, and is right. He is a better detective than he was given credit for two pages earlier."),
         V("Five pages ago Holmes said there was no crime in this business. What has changed?",
           ["Nothing — losing a goose is still not a crime",
            "A stranger has turned out to be a thief",
            "The object of a famous robbery has turned up in the evidence",
            "Peterson has admitted that he kept the bird on purpose"],
           2,
           "The hat and the goose were a puzzle about an unknown gentleman. One stone on a commissionaire’s palm turns the same facts into evidence in a robbery with a man already awaiting trial."),
         ),

    item("worth", ["a thousand pounds", "not within a twentieth part of the market price",
                   "half her fortune", "read about it in The Times"],
         V("What reward has been offered for the stone?",
           ["A hundred pounds",
            "A thousand pounds",
            "Half the Countess’s fortune",
            "No reward has been offered at all"],
           1,
           "A thousand pounds — and Holmes points out at once that it is “not within a twentieth part of the market price,” so the stone is worth more than twenty thousand. In 1890 that is a fortune."),
         V("What does Holmes say about the reward compared with what the stone is worth?",
           ["The reward is more than the stone could ever fetch",
            "The reward is about what the stone is worth",
            "The reward is less than a twentieth of its value",
            "Nobody can say, because it has never been valued"],
           2,
           "Which tells you something about the Countess as well as the stone: she is offering a very large sum and still getting a bargain, because no honest buyer could be found for a stolen carbuncle anyway."),
         V("How does Holmes come to know the stone’s size and shape without having seen it?",
           ["He had read about it in The Times every day lately",
            "He had been consulted by the Countess herself",
            "He had seen it in a jeweller’s window in London",
            "Inspector Bradstreet had described it to him"],
           0,
           "He has read about it in the paper every day. The crumpled newspapers beside his couch on the first page of the story turn out not to be idleness."),
         V("Besides money, what reason does Holmes give for the Countess wanting the stone back?",
           ["She needs it to settle a debt",
            "She has promised it to a museum",
            "There are sentimental considerations",
            "She means to sell it and leave England"],
           2,
           "“Sentimental considerations that would induce the Countess to part with half her fortune if she could recover the gem.” The stone matters to her for a reason that has nothing to do with its price."),
         V("How does Peterson react to the figure of a thousand pounds?",
           ["He asks Holmes whether he may claim it",
            "He drops into a chair and stares at them",
            "He laughs and says it cannot be true",
            "He offers to take the stone to the police himself"],
           1,
           "“Great Lord of mercy!” and he plumps down into a chair. He is an honest man who has just been told that the bird he took home was carrying a year’s wages many times over."),
         ),

    item("accused", ["Hotel Cosmopolitan", "just five days ago",
                     "John Horner, a plumber", "referred to the Superior Court"],
         V("Where and when was the carbuncle lost?",
           ["At the Alpha Inn, on Christmas morning",
            "At the Hotel Cosmopolitan, five days ago",
            "At the Countess’s own house, a week ago",
            "In Goodge Street, on the night of the row"],
           1,
           "The Hotel Cosmopolitan, five days before. Count forward: the robbery, then Christmas morning in Tottenham Court Road, then the second morning after Christmas in Baker Street. The dates matter."),
         V("Who has been accused of the robbery?",
           ["James Ryder, an attendant at the hotel",
            "Catherine Cusack, the Countess’s maid",
            "Henry Baker, who lost the goose",
            "John Horner, a plumber"],
           3,
           "John Horner, 26, a plumber, who had been working in the Countess’s dressing room that day. Hold on to the fact that he is a workman called in, and the only person in the room who did not belong to the hotel."),
         V("How far has the case against Horner already gone?",
           ["He has been questioned and released",
            "He has been charged, but has not yet been arrested at all",
            "The evidence was strong enough to send it to the Superior Court",
            "He has already been tried and sentenced"],
           2,
           "The magistrate would not deal with it himself and referred it on. Which means a trial is coming, and the clock is running on whatever Holmes is going to do about it."),
         V("What does Holmes do when Watson mentions the Hotel Cosmopolitan?",
           ["Sends out for the morning’s papers",
            "Writes at once to Inspector Bradstreet",
            "Finds the newspaper report among his own papers",
            "Says he has heard nothing at all about the case"],
           2,
           "He rummages among the papers he has been lying in all morning until he finds the paragraph, and reads it out. Everything he needs is already in the room."),
         V("Why does it matter that a man is already awaiting trial for this robbery?",
           ["It means the police will not listen to Holmes",
            "It means that the stone must have been stolen twice over",
            "It means Holmes’s puzzle now has somebody’s freedom in it",
            "It means the Countess will withdraw her reward"],
           2,
           "The hat was an exercise. Now the same chain of facts leads to a man in a cell who fainted in court, and the question of whether he put the stone where it was found."),
         ),
]


# ====================================================================== 2
S2 = [

    item("ryder", ["James Ryder, upper attendant at the hotel",
                   "solder the grate, which was loose", "finally been called away",
                   "lying empty on the table"],
         V("Why was Horner in the Countess’s dressing room at all?",
           ["He had been sent up with a message",
            "He had been shown up to solder a loose grate",
            "He was there to clean the chimney",
            "He had come to the hotel to deliver the jewel case"],
           1,
           "A plumber, shown up to mend a loose grate. He had a reason to be in the room and somebody else put him there — which is a strange way to begin a robbery."),
         V("Who showed Horner up to the room?",
           ["Catherine Cusack, the Countess’s maid",
            "The Countess of Morcar herself",
            "James Ryder, the upper attendant",
            "Nobody — he went up on his own"],
           2,
           "James Ryder, upper attendant at the hotel. Notice how much of this story is Ryder’s: he takes Horner up, he is the one who leaves, he is the one who comes back, and he is the one who raises the alarm."),
         V("According to Ryder, what happened while he was out of the room?",
           ["Horner disappeared, the bureau was forced, the casket left empty",
            "Horner finished the grate and went away quietly",
            "The Countess came in and took the jewel herself",
            "Cusack found Horner standing at the bureau, and called out"],
           0,
           "That is Ryder’s account of it. Read it again as what it is — testimony — rather than as what happened, because the only person who says the room was emptied while he was away is the person who was away."),
         V("Who raised the alarm?",
           ["Horner, when he found the casket empty",
            "Ryder, the moment he came back",
            "Catherine Cusack, from the passage",
            "The Countess, on returning to dress"],
           1,
           "“Ryder instantly gave the alarm.” Instantly. He is quick, and he is helpful, and everything the police know about the robbery begins with him."),
         V("Horner was arrested that same evening. What was never found?",
           ["The tools he had been working with",
            "The casket the jewel had been kept in",
            "The stone",
            "The grate he had been sent up to mend"],
           2,
           "“But the stone could not be found.” A man is going to trial for taking a stone nobody could find on him — and it turns up days later in a goose’s throat on the other side of London."),
         ),

    item("court", ["hearing Ryder’s cry of dismay", "struggled frantically, and protested his innocence",
                   "a previous conviction for robbery", "fainted away at the conclusion"],
         V("What does Catherine Cusack’s evidence actually add?",
           ["That she saw Horner at the bureau",
            "That she heard Ryder’s cry and found things as he described",
            "That the Countess had shown her the jewel that morning",
            "That Horner had asked her about the jewel case"],
           1,
           "Read it carefully: she heard Ryder shout, and she arrived to find matters as Ryder described. She is a witness to Ryder’s discovery, not to the robbery. Nobody saw the stone taken."),
         V("How did Horner behave when he was arrested?",
           ["He confessed at once and asked for mercy",
            "He went quietly, saying nothing at all",
            "He struggled frantically and protested his innocence",
            "He ran for it, and had to be caught in the street outside"],
           2,
           "Inspector Bradstreet’s evidence. A man fighting and shouting that he is innocent looks guilty to a court, and looks exactly the same whether he is or not."),
         V("What piece of evidence weighed heaviest against Horner?",
           ["That he was found with hotel property on him",
            "That he could not say where he had gone",
            "That he had been convicted of robbery before",
            "That Ryder had seen him open the bureau"],
           2,
           "“Evidence of a previous conviction for robbery.” It is why the magistrate sent the case up. Notice that it is not evidence about this robbery at all — it is evidence about who he is."),
         V("How did Horner take the proceedings?",
           ["He showed no feeling throughout",
            "He laughed at the magistrate",
            "He showed intense emotion and fainted at the end",
            "He asked to give evidence himself and was refused"],
           2,
           "“Fainted away at the conclusion, and was carried out of court.” The reader is given this and then nothing more about him for pages, which is part of what makes the case urgent."),
         V("Three people gave evidence. What does none of it establish?",
           ["That the stone was missing from the casket",
            "That Horner had been in the room",
            "That Horner was ever seen taking the stone",
            "That Ryder had left the room for a time"],
           2,
           "The casket was empty, Horner had been there and was gone, Ryder shouted and Cusack came running. Not one witness describes the theft. The whole case is what people found afterwards."),
         ),

    item("chain", ["So much for the police court",
                   "a burglarized jewel case at one end to the throat of a goose at the other",
                   "a less innocent aspect", "the goose came from Mr. Henry Baker"],
         V("How does Holmes describe the problem now in front of them?",
           ["Deciding whether Horner is guilty or not",
            "Returning the stone to the Countess as quickly as possible",
            "The sequence of events from a jewel case to a goose’s throat",
            "Finding out which of the hotel servants could have been bribed"],
           2,
           "It is a beautiful way to put a problem: two ends that are known, and the whole middle missing. Everything he does for the rest of the story is filling in that middle."),
         V("What does Holmes mean by “our little deductions have suddenly assumed a less innocent aspect”?",
           ["That he no longer trusts what the hat told him",
            "That the hat reasoning was a waste of time after all",
            "That the same conclusions now bear on a crime",
            "That Watson was right to call it a waste of energy"],
           2,
           "Nothing he worked out about the hat has changed or been withdrawn. What has changed is what it is for: a portrait of a shabby gentleman is now a description of a man the police will want to talk to."),
         V("What is the chain Holmes lays out, in order?",
           ["Baker, then the goose, then the stone, then the hotel",
            "The stone came from the goose, the goose from Henry Baker",
            "The hotel, then Horner, then Peterson, then the hat",
            "The goose came from the hotel, and the stone from Horner"],
           1,
           "He works backwards from what he is holding: stone, goose, Baker. That is why finding Baker is the next job and not, say, going to the hotel — Baker is the nearest unknown link."),
         V("What does Holmes decide to do first?",
           ["Call on the Countess of Morcar",
            "Visit Horner in his cell",
            "Go down to the Hotel Cosmopolitan himself",
            "Set himself seriously to finding Henry Baker"],
           3,
           "“So now we must set ourselves very seriously to finding this gentleman.” Very seriously — the same man whose hat was a morning’s amusement is now the only lead there is."),
         V("Why is Henry Baker the right person to look for next, rather than anyone at the hotel?",
           ["The police are already working on the hotel",
            "He is the last person known to have had the goose",
            "He is the only suspect Holmes has",
            "He lives nearer to Baker Street than the others"],
           1,
           "The chain is broken between the hotel and the goose, and Baker is standing at the near end of the gap. Work from what you have towards what you do not — and nobody has suggested Baker is a suspect."),
         ),
]
