# -*- coding: utf-8 -*-
"""Sections 3 and 4: pages 140 to 142, and 143 to 146.

Section 4 is the best piece of character work in the reading: Holmes sets a trap
that is not a trap at all, and an innocent man walks straight through it without
noticing. The questions are built around what the test actually tests, because
that is a thing worth being able to see.

The reading ends partway through the Alpha Inn, so nothing here names where the
geese came from. Page 146 stops on "I was speaking half an hour ago to Mr." and
the landlord answers on 147.
"""
from carb2_q12 import V, item


# ====================================================================== 3
S3 = [

    item("advert", ["the simplest means first", "corner of Goodge Street",
                    "221b Baker Street", "to a poor man, the loss was a heavy one"],
         V("What is the “simplest means” Holmes tries first?",
           ["Calling at every hat shop in London",
            "An advertisement in all the evening papers",
            "Asking the police to circulate a description",
            "Waiting for Baker to come and ask for the hat"],
           1,
           "An advertisement. Before anything clever, the obvious thing — and it works, which is why he tried it first."),
         V("What does the advertisement offer, and where?",
           ["A reward for news of a goose and a hat",
            "A goose and a black felt hat, back at 221b Baker Street",
            "The return of a lost hat, at the Alpha Inn",
            "A thousand pounds for the stone, at Scotland Yard"],
           1,
           "“Found at the corner of Goodge Street, a goose and a black felt hat… at six-thirty this evening at 221b Baker Street.” Notice what it does not say: nothing about a stone, and nothing about the police."),
         V("Watson asks whether Baker will even see the advertisement. Why is Holmes sure he will?",
           ["Baker is a man of learning who reads everything",
            "The advertisement is to appear in every paper in London",
            "To a poor man, losing a Christmas goose is a heavy loss",
            "Baker lives close enough to see it posted in the street"],
           2,
           "He is reasoning from the man, not from the newspaper. A poor man who has lost his Christmas dinner will be watching the papers — which is the same reasoning he did off the hat, used forwards."),
         V("What errand does Holmes add for Peterson besides the advertisement?",
           ["To fetch Inspector Bradstreet to Baker Street",
            "To buy another goose and leave it there",
            "To say nothing to his wife about the stone",
            "To take the stone to the Countess at once"],
           1,
           "“We must have one to give to this gentleman in place of the one your family is devouring.” A small courtesy — and the second goose turns out to be the whole of the test he sets Baker."),
         V("The advertisement mentions Goodge Street but not the stone. Why would Holmes leave that out?",
           ["Because the stone is not Baker’s to be given back",
            "Because the police had asked him to keep it quiet",
            "Because a guilty man would be warned off by it",
            "Because the Countess had not yet been told it was found"],
           2,
           "If Baker put the stone in the goose, an advertisement naming it is a warning to stay away. Mentioning only a hat and a bird is what makes the invitation safe to accept — and makes who turns up worth knowing."),
         ),

    item("devil", ["a focus of crime", "the devil’s baits",
                   "blue, instead of ruby red",
                   "two murders, a suicide, and several robberies"],
         V("What does Holmes call every good stone?",
           ["A fortune waiting for an owner",
            "A focus of crime, and the devil’s baits",
            "A thing more trouble than it is worth",
            "The one honest form of money"],
           1,
           "“Of course it is a focus of crime. Every good stone is. They are the devil’s baits.” Not this stone in particular — all of them. It is a remark about people rather than about jewels."),
         V("What makes this stone unusual as a carbuncle?",
           ["It is larger than any other known",
            "It was cut in China rather than in Europe",
            "It is blue instead of ruby red",
            "It is older than any other in England"],
           2,
           "“Every characteristic of the carbuncle, except that it is blue, instead of ruby red.” That is where the story gets its title, and why the stone cannot be sold or mistaken for another."),
         V("What history does the stone already have?",
           ["It has been lost and found three times before",
            "It has passed through six owners in twenty years",
            "Two murders, a suicide and several robberies",
            "It was taken from a temple and never recovered"],
           2,
           "And it is not twenty years old. Holmes lays this out immediately after calling it the devil’s baits — the sinister history is his evidence for the remark, not decoration."),
         V("What does Holmes do with the stone, and what does he do about the Countess?",
           ["Sends it to her at once by a messenger",
            "Locks it in his strongbox and writes to her",
            "Gives it to Peterson to take to the police",
            "Keeps it in his pocket until the case is done"],
           1,
           "Strongbox, and a line to say that they have it. He does not hand it over, because he still needs the goose it came out of to lead somewhere — but he will not leave her wondering either."),
         V("Why does Holmes talk about the stone’s history at all, just here?",
           ["To explain why it is worth so much money",
            "To show why it cannot be sold openly",
            "To explain why he intends to keep it safely locked up",
            "To say what such a stone does to the people near it"],
           3,
           "He has a man in a cell, a stranger with a bad hat, and a robbery nobody saw. The remark about the devil’s baits is him saying what kind of story this is likely to turn out to be."),
         ),

    item("innocent", ["I cannot tell", "an absolutely innocent man",
                      "more value than if it were made of gold",
                      "a very simple test"],
         V("Watson asks whether Horner is innocent. What does Holmes answer?",
           ["That he is certainly innocent",
            "That he is almost certainly guilty",
            "That he cannot tell",
            "That the court has already decided the matter"],
           2,
           "“I cannot tell.” Three words, and they are the most honest thing he says all evening. He has a stone and a goose and no idea yet how they met."),
         V("What does Holmes think about Henry Baker’s part in it?",
           ["That he is more likely an absolutely innocent man",
            "That he is the thief and the goose was his hiding place",
            "That he was paid by somebody else to carry the bird",
            "That he cannot say until he has seen the man"],
           0,
           "More likely innocent — a man with no idea “that the bird he was carrying was of more value than if it were made of gold.” A guess, offered as a guess, and he says how he means to check it."),
         V("How does Holmes say he will settle the question of Baker?",
           ["By questioning him closely about the goose",
            "By asking Bradstreet to look into his record",
            "By a very simple test",
            "By watching the house to see who comes with him"],
           2,
           "“A very simple test, if we have an answer to our advertisement.” Simple is the word to notice — what he actually does is offer the man a different goose and watch his face."),
         V("Holmes will not guess about Horner but will guess about Baker. What is the difference?",
           ["Baker has not been accused of anything",
            "He has a way to check the guess about Baker",
            "Horner has a previous conviction against him",
            "Baker is a poor man and Horner is not"],
           1,
           "A guess you can test is worth making; a guess you cannot is just an opinion. He has no way to test Horner, so he says “I cannot tell” and leaves it."),
         V("Watson says he will come back in the evening. What does that say about the state of the case?",
           ["Holmes has sent him away so he can work alone",
            "Holmes expects to have solved it by then",
            "There is nothing to be done until Baker answers",
            "Watson has lost interest in the business"],
           2,
           "“And you can do nothing until then?” “Nothing.” The whole investigation is waiting on one advertisement and one stranger choosing to turn up."),
         ),
]


# ====================================================================== 4
S4 = [

    item("baker", ["a soft woolen cap", "a man of learning who had had a run of bad luck",
                   "Money has not been so plentiful with me as it once was",
                   "a hopeless attempt at recovering them"],
         V("What is Henry Baker like when he finally appears?",
           ["A small nervous man who will not sit down",
            "A large man with a massive head and a grizzled beard",
            "A young man, well dressed and confident",
            "An elderly man who can hardly walk without help"],
           1,
           "Large, round-shouldered, massive head, broad intelligent face, grizzled brown beard. Hold it against the hat: a big head, greying hair, middle-aged. Holmes had him right."),
         V("Which of Holmes’s conclusions does Baker’s appearance bear out?",
           ["That he keeps no servant in the house",
            "That his wife has ceased to love him",
            "That he is out of shape entirely and goes out little",
            "That he had money three years ago and has none now"],
           3,
           "A rusty black coat buttoned to the chin, wrists out of the sleeves, and “the impression of a man of learning who had had a run of bad luck.” The decline Holmes read off the brim is standing in the room."),
         V("Why had Baker never advertised for his lost hat and goose?",
           ["He had not realised they were missing",
            "He thought the thugs had taken them, and could not afford to try",
            "He was ashamed of having broken the window",
            "He had been too ill to go out of doors since Christmas Day"],
           1,
           "“Money has not been so plentiful with me as it once was… I did not care to spend more money in a hopeless attempt at recovering them.” An advertisement costs money he has not got."),
         V("What does Baker’s reason for not advertising confirm?",
           ["That he had something to hide about the bird",
            "That he had come down in the world",
            "That he had not been in London at Christmas",
            "That he blamed Peterson for taking them"],
           1,
           "He gives it with “a rather shamefaced laugh,” which is the detail that makes it true. Nobody pretends to be too poor to place an advertisement."),
         V("How does the way Baker speaks fit what Holmes said about him?",
           ["He speaks roughly, so Holmes was wrong about his learning",
            "He says almost nothing, so nothing can be told",
            "He chooses his words, like an educated man fallen on hard times",
            "He talks too much, which Holmes had not predicted"],
           2,
           "“He spoke in a choppy fashion, choosing his words.” Holmes said highly intellectual on the strength of a hat size, which was bad reasoning — and he still turns out to have been right, which is a different thing from being right for a good reason."),
         ),

    item("test", ["we were compelled to eat it", "about the same weight and fresh",
                  "a sigh of relief", "relics of my adventure"],
         V("What does Holmes tell Baker about his goose?",
           ["That it is waiting for him downstairs",
            "That it had to be given away to a neighbour",
            "That they were compelled to eat it",
            "That it had spoiled and was thrown out"],
           2,
           "He says it straight out and then watches. The whole test is in what Baker does in the next few seconds."),
         V("How does Baker react when he hears the bird has been eaten?",
           ["He half rises from his chair in excitement",
            "He says it does not matter in the least",
            "He asks whether anything was found inside it",
            "He accuses Holmes of having stolen it"],
           0,
           "“To eat it!” Half out of his chair — and then entirely satisfied the moment another goose is offered. A man who knew what was in that bird would not be calmed by a fresh one."),
         V("What does Holmes offer him besides the fresh goose?",
           ["The feathers, legs and throat of the first bird",
            "The thousand pounds of reward the stone would earn",
            "A hat to replace the battered one",
            "Payment for the bird that was eaten"],
           0,
           "“The feathers, legs, throat, and so on of your bird.” Throat. Holmes puts the one part of the goose that matters in front of him, and Baker laughs it off as a relic."),
         V("What is Baker’s answer to that offer, and what does it prove?",
           ["He takes the remains, which shows he is looking for something",
            "He takes both, which shows nothing either way",
            "He refuses them and takes the fresh bird, so he knows nothing",
            "He asks to be left alone with them, which makes Holmes suspicious"],
           2,
           "He would rather have the good goose on the sideboard than the giblets of his own. Anybody who had hidden a stone in that throat would have taken the remains without hesitating."),
         V("Holmes glances at Watson with a shrug. What is he saying?",
           ["That he does not believe a word of it",
            "That Baker is not the man they want",
            "That Watson should keep quiet about the stone",
            "That the test has failed and must be tried again"],
           1,
           "The test is over and it is settled. No question was asked and no accusation made — Baker was offered two things and chose the one an innocent man would choose."),
         ),

    item("club", ["I am a fowl fancier", "the Alpha Inn near the museum",
                  "instituted a goose club", "he knows nothing whatever about the matter"],
         V("How does Holmes get Baker to say where the goose came from?",
           ["By telling him the bird may have been stolen",
            "By offering him money for the information",
            "By asking as one fowl fancier admiring a fine bird",
            "By asking him directly where he had bought it"],
           2,
           "“I am a fowl fancier, and I have seldom seen a better-grown goose.” A compliment, not a question — and Baker answers it happily on his way out of the door."),
         V("Where did Baker get his goose?",
           ["He bought it at a market on Christmas Eve",
            "From a goose club at the Alpha Inn",
            "It was a gift from his landlord",
            "From a shop near the museum, on Christmas Eve"],
           1,
           "A goose club run by Windigate, the host of the Alpha Inn: a few pence every week through the year and a bird at Christmas. That is how a poor man comes by a Christmas goose."),
         V("What is Holmes’s verdict on Henry Baker?",
           ["That he is hiding something after all",
            "That he may be worth watching for a while",
            "That he knows nothing whatever about the matter",
            "That he should be questioned again tomorrow"],
           2,
           "“So much for Mr. Henry Baker. It is certain that he knows nothing whatever about the matter.” Certain — a word he refused to use about Horner, and uses here because he has tested it."),
         V("What does Holmes decide to do instead of having dinner?",
           ["Write up his notes on the case so far",
            "Go to the police with what he has found",
            "Wait at Baker Street for news of Horner’s trial",
            "Turn dinner into supper and follow the clue at once"],
           3,
           "A bitter night, coats and scarves, and a quarter of an hour later they are at the Alpha Inn. He will not let the trail cool for the sake of a meal."),
         V("At the end of the reading, what has the investigation actually gained?",
           ["The name of the thief who took the stone",
            "A link from the stone back to where the goose came from",
            "Proof that John Horner is innocent",
            "The reward of a thousand pounds from the Countess"],
           1,
           "One more link, and no more: stone, goose, Baker, and now the place Baker got the bird. Horner is still in a cell and nobody knows who put the stone in the goose."),
         ),
]
