# -*- coding: utf-8 -*-
"""Chapters 3 and 4 of The Blue Carbuncle: pages 133 to 134, and 135 to 136.

Chapter 3 is Holmes showing his work, one conclusion at a time, in the order
Watson asks for it. So the questions here are mostly of one kind -- given this
mark on the hat, what does it let you say, and what does it not let you say --
which is the kind worth being able to do.

Chapter 4 ends the reading on Peterson bursting through the door. What is in the
goose's throat is on page 137, past tonight's pages, so nothing here asks for it.
What the last question does ask is what Watson has just said and why the timing
of the interruption is funny.
"""
from carb_q12 import V, item


# ====================================================================== 3
CH3 = [

    item("capacity", ["clapped the hat upon his head", "the bridge of his nose",
                      "a question of capacity", "so large a brain"],
         V("How does Holmes prove the man is intellectual?",
           ["By the careful way the hat has been mended",
            "By the quality of the hat he chose to buy",
            "By putting the hat on his own head",
            "By the books listed in the papers beside him"],
           2,
           "He claps it on and it settles on the bridge of his nose. No lens, no reasoning — he simply tries the hat on, and it is far too big for him."),
         V("“It is a question of capacity.” What does Holmes mean by capacity here?",
           ["How much the man could afford to spend on a hat",
            "How much the hat can hold — the size of the head",
            "How much the man is able to remember",
            "How well the hat has stood up to wear"],
           1,
           "Capacity as in volume. “A man with so large a brain must have something in it.” The joke is that he is measuring a mind with a hat, and saying so with a completely straight face."),
         V("Is this a good piece of reasoning?",
           ["Yes — head size is a reliable measure of intelligence",
            "No — a big hat only proves a big head",
            "Yes — because Holmes is never wrong about people",
            "No — because the hat may not be the man’s own"],
           1,
           "It is the weakest link in the chain and the story is not hiding it: Victorians believed a large skull meant a large intellect, and it does not. Holmes calls it “of course obvious,” which is what people say when they have not checked."),
         V("Why does the hat settling on the bridge of Holmes’s nose make the point so quickly?",
           ["It shows that Holmes has a small head",
            "It shows the hat was made for somebody else entirely",
            "It shows the hat is far too large for a normal head",
            "It shows the hat has lost its shape with age"],
           2,
           "Watson does not have to be told; he can see it. It is the one deduction in the chapter that is demonstrated rather than argued, which is why Holmes leads with it."),
         V("Of all the conclusions on Holmes’s list, which does this one rest on the least evidence?",
           ["This one — the size of the hat and nothing more",
            "The decline of his fortunes — the age of the hat",
            "The lime-cream — the smell of the lining",
            "The candle — the wax stains on the felt"],
           0,
           "The wax, the dust, the hair ends and the securer are all marks left by things the man actually did. The size of his head is just the size of his head, and everything else Holmes builds on it is guesswork."),
         ),

    item("threeyears", ["This hat is three years old", "flat brims curled at the edge",
                       "the very best quality", "gone down in the world"],
         V("How does Holmes know the hat is three years old?",
           ["A date is stamped inside the lining",
            "Its flat brim curled at the edge was the fashion three years ago",
            "Three years of dust have gathered in it",
            "The maker went out of business three years ago, as he recalls"],
           1,
           "“These flat brims curled at the edge came in fashion then.” He is dating an object by its style, the way you might date a photograph by the clothes in it."),
         V("What does Holmes say about the quality of the hat?",
           ["That it was cheap when new",
            "That it was of the very best quality",
            "That it was made to order rather than bought",
            "That it was good but not the best to be had"],
           1,
           "The very best quality. That is what makes the age of it mean something: an expensive hat, three years old, and nothing bought since."),
         V("Which two facts, put together, tell Holmes the man has come down in the world?",
           ["The broken elastic and the ink stains",
            "The dust indoors and the marks of moisture",
            "An expensive hat, three years old, and no hat since",
            "The red silk lining and the missing maker’s name"],
           2,
           "Either fact on its own says nothing. A man may buy a fine hat and keep it; a man may own one old hat and never have had money. Only both together show a fall."),
         V("Suppose the hat had been cheap and three years old. What could Holmes have concluded?",
           ["That the man had grown poorer still",
            "That the man had come up in the world",
            "Nothing about his fortunes either way",
            "That the man cared nothing for his appearance"],
           2,
           "A poor man with an old cheap hat is just a poor man. The deduction needs the gap between what he once could afford and what he has now, and a cheap hat leaves no gap to measure."),
         V("Watson calls this one “clear enough, certainly.” Why does he accept it so readily?",
           ["Because Holmes has proved it with the lens",
            "Because it follows from two things he can check himself",
            "Because he had already thought of it himself",
            "Because it is the least surprising thing on the list"],
           1,
           "He can feel the quality of the felt and he can be told the fashion. Compare the wife and the gas, which he fights every step of the way — Watson believes what he can verify."),
         ),

    item("securer", ["the little disc and loop of the hat-securer",
                     "never sold upon hats", "a distinct proof of a weakening nature",
                     "daubing them with ink"],
         V("What is a hat securer, and what is it for?",
           ["A band inside the hat to make it fit better",
            "A disc and loop with an elastic, to stop the hat blowing away",
            "A stiffener sewn into the brim to hold the hat in its shape",
            "A pin that fastens the hat to the hair"],
           1,
           "A little disc and loop with an elastic — “this precaution against the wind.” Holmes puts his finger on it and calls it the foresight, which is a lot to call a piece of elastic."),
         V("Why does the hat securer prove foresight?",
           ["Because hats are never sold with one, so he ordered it specially",
            "Because it was expensive to have fitted",
            "Because only a careful man would wear a hat in windy weather",
            "Because it had to be sewn on by the man himself"],
           0,
           "“They are never sold upon hats. If this man ordered one, it is a sign of foresight, since he went out of his way to take this precaution.” Somebody had to ask for it: that is the whole argument."),
         V("What does Holmes read into the broken elastic that was never replaced?",
           ["That the man lost the hat some time ago",
            "That the man has grown careless about his own appearance now",
            "That he has less foresight than he had, and a weakening nature",
            "That somebody else has been wearing the hat"],
           2,
           "The same small object twice over: ordering it showed foresight, not mending it shows the foresight going. “A distinct proof of a weakening nature.” Holmes gets a change over time out of a thing that does not move."),
         V("What does the ink daubed over the stains tell Holmes?",
           ["That the man had no money for a new hat",
            "That the man works with ink and got it on the felt",
            "That he minds how he looks, so keeps some self-respect",
            "That he tried to hide the hat’s age from his wife"],
           2,
           "“Which is a sign that he has not entirely lost his self-respect.” A man daubing ink on a stained hat is a man still hoping to look respectable, and it is the one point where Holmes gives him credit."),
         V("The securer and the ink point in opposite directions. What does Holmes do about that?",
           ["He decides the ink is the more reliable of the two",
            "He treats the contradiction as proof the hat had two owners",
            "He keeps both: a man slipping who has not given up",
            "He drops the securer and relies on the ink"],
           2,
           "“On the other hand” — he does not tidy the evidence into one story. The elastic says he is letting himself go; the ink says he is still trying. Holding both is what makes Henry Baker a person instead of a conclusion."),
         ),

    item("lining", ["the lower part of the lining",
                    "clean cut by the scissors of the barber",
                    "sticky", "a distinct odor of lime-cream"],
         V("Where does Holmes find the evidence about the man’s hair and age?",
           ["On the outside of the crown",
            "Under the band around the brim",
            "In the lower part of the lining",
            "On the disc of the hat securer"],
           2,
           "The lower part of the lining — the part that sits against the head. Four separate conclusions come out of one small area of red silk, which is why he asked Watson for the lens."),
         V("What tells Holmes the man’s hair was cut only a few days ago?",
           ["The lining is less worn than the rest of the hat",
            "The hair ends are clean cut by a barber’s scissors",
            "There is very little hair in the lining at all",
            "The grizzled hairs are shorter than the dark ones"],
           1,
           "Clean-cut ends, not broken or worn ones, and a large number of them. A barber’s scissors leave a flat edge; hair that has grown out does not. He needs the lens to see it."),
         V("What tells him the man uses lime-cream?",
           ["The lining is discoloured where it touched his head",
            "The hairs are sticky and there is a distinct odour of it",
            "The hat has kept the shape of oiled hair",
            "Marks of the cream are visible on the brim"],
           1,
           "Two senses at once — the hairs feel sticky and the lining smells of it. Holmes is not only looking at the hat; he has had his nose in it."),
         V("Holmes says the hair is grizzled, and that is how he knows the man is middle-aged. What kind of reasoning is that?",
           ["Proof — only middle-aged men have grey hair",
            "A guess with nothing behind it",
            "A fair inference, though grey hair can come early",
            "The same reasoning he used about the man’s brain"],
           2,
           "Greying hair usually means middle age and does not have to. It is one of the ones he called “at least probable” rather than distinct, and he is right to have graded it that way."),
         V("What is it about the hair ends that makes them evidence at all?",
           ["That there are so many of them in the lining",
            "That they are grey rather than dark",
            "That they carry the marks of what was done to them",
            "That they have stuck to the silk of the lining"],
           2,
           "A cut end is a record of a haircut; a sticky one is a record of the cream. The hat is useful to Holmes because everything that happened to the man’s head left a trace in it."),
         ),

    item("dust", ["not the gritty, grey dust of the street",
                  "the fluffy brown dust of the house",
                  "hung up indoors most of the time",
                  "perspired very freely"],
         V("What is the difference Holmes draws between two kinds of dust?",
           ["Fresh dust and dust that has been there for weeks",
            "Dust on the outside and dust on the lining",
            "Gritty grey street dust and fluffy brown house dust",
            "Dust from the road and dust from a workshop"],
           2,
           "Two dusts that look like one thing to anybody else. Knowing that they are different is not clever reasoning — it is simply knowing more about dust than other people do, which is most of what Holmes does."),
         V("What does the house dust prove about the hat?",
           ["That it has hung up indoors most of the time",
            "That the house it hung in was not often swept",
            "That the man had stopped going out to work",
            "That it had been kept in a cupboard for years"],
           0,
           "The dust is about where the hat was, and only then about the man. Holmes gets from one to the other in a single step — a hat that stays in is worn by a man who stays in."),
         V("What do the marks of moisture inside the hat show?",
           ["That the man had been caught in the rain",
            "That the hat had been washed at some point",
            "That the wearer perspired freely and was out of condition",
            "That the hat had been worn by more than one person in turn"],
           2,
           "“Could hardly be in the best of training.” A sweat-marked lining on a man who hardly goes out: the two conclusions support each other, which is why Holmes puts them in the same breath."),
         V("Which of Holmes’s conclusions rests on the dust?",
           ["That the man is middle-aged",
            "That the man leads a sedentary life and goes out little",
            "That the man has fallen on evil days",
            "That the man has entirely lost his wife’s affection"],
           1,
           "Sedentary, goes out little. Watson had already written down “exceedingly dusty” and left it there; the same dust, looked at properly, is a description of how the man spends his days."),
         V("Suppose the dust had been the gritty grey kind instead. What would Holmes have had to give up?",
           ["That the man was intellectual",
            "That the man was fairly well-to-do three years ago",
            "That the man leads an indoor, sedentary life",
            "That the man has not entirely lost his self-respect"],
           2,
           "Street dust would mean a hat that goes out, which is the opposite conclusion from the same object. The evidence points somewhere only because it could have pointed elsewhere."),
         ),
]


# ====================================================================== 4
CH4 = [

    item("brushed", ["has not been brushed for weeks",
                     "a week’s accumulation of dust upon your hat",
                     "lose your wife’s affection"],
         V("What is the evidence that the man’s wife has stopped loving him?",
           ["The card addressed to her rather than to him",
            "The hat has not been brushed for weeks",
            "The state of the lining and the hair cream",
            "That he was out alone at four in the morning"],
           1,
           "An unbrushed hat. That is the whole of it — and Holmes told Watson at the start that some of his inferences were only probable. This is the boldest one in the story."),
         V("What is the assumption hiding inside that deduction?",
           ["That a man never brushes his own hat",
            "That a wife would let her husband go out dusty only if she no longer cared",
            "That the man cannot afford to have the hat properly cleaned and brushed",
            "That the hat had been hanging up for weeks unworn"],
           1,
           "Holmes needs it to be a wife’s business to brush her husband’s hat. In 1890 that assumption passed without comment; today the reasoning is the most dated thing in the story, and worth noticing as such."),
         V("How does Holmes make the point to Watson?",
           ["By reminding him of an earlier case",
            "By pointing out the dust with the lens",
            "By joking that a dusty hat on Watson would mean the same thing",
            "By asking Watson when his own hat was last brushed at home"],
           2,
           "“When I see you, my dear Watson, with a week’s accumulation of dust upon your hat… I shall fear that you also have been unfortunate enough to lose your wife’s affection.” He uses Watson’s own marriage as the worked example."),
         V("What does that joke tell you about the two men’s friendship?",
           ["That Holmes is careless of Watson’s feelings",
            "That Watson’s marriage is a sore subject between them",
            "That Holmes can tease him about his private life",
            "That Holmes envies Watson for being married"],
           2,
           "You can only make that joke to a close friend. Notice too what it assumes: that Watson’s hat is brushed, and that Holmes has noticed."),
         V("Is this the strongest or the weakest of Holmes’s conclusions?",
           ["The strongest — he calls it an obvious fact",
            "Among the weakest — an unbrushed hat has many explanations",
            "The strongest — nothing else explains the dust",
            "Among the weakest — because the man may not be married"],
           1,
           "He calls it “the obvious fact,” which is a good deal more confident than the evidence deserves. The man might live alone, or be ill, or have a wife with troubles of her own — and the story has Watson push back at once."),
         ),

    item("bachelor", ["he might be a bachelor", "a peace-offering to his wife",
                      "the card upon the bird’s leg"],
         V("What objection does Watson raise?",
           ["That the hat might not belong to the man at all",
            "That the man might be a bachelor",
            "That a servant might brush the hat instead",
            "That the dust might have come from the street"],
           1,
           "“But he might be a bachelor.” It is a good objection: everything about the wife falls apart if there is no wife, and Watson spots the weak joint straight away."),
         V("How does Holmes answer it?",
           ["By pointing to the initials H.B. in the lining",
            "By saying a bachelor would not own such a hat",
            "By reminding Watson of the card on the goose’s leg",
            "By admitting that he cannot be sure of it"],
           2,
           "“Remember the card upon the bird’s leg.” For Mrs. Henry Baker — which is not on the hat at all. He has stepped outside the hat to answer, and that is fair, because the card is evidence too."),
         V("What does Holmes call the goose, and what does that add?",
           ["A Christmas gift, showing the man still had money to spend",
            "A peace-offering to his wife, showing something needed mending",
            "A bribe, showing he was in trouble of some kind",
            "A dinner, showing he was expected home that night"],
           1,
           "A peace-offering. It is a small word with a lot in it: a man carrying home a goose to make peace is a man who knows things are not right between them — which fits the unbrushed hat rather neatly."),
         V("Watson’s objection is a good one. Why is it still worth making?",
           ["It shows Holmes had overlooked the card",
            "It forces Holmes to show which evidence each claim rests on",
            "It proves the man was married after all",
            "It shows Watson had already guessed the answer for himself"],
           1,
           "This is the job Watson does: he presses, and the reasoning gets shown. The wife rests on the card, not on the hat, and nobody would know that if Watson had simply nodded along."),
         V("“You have an answer to everything,” Watson says next. Is that agreement?",
           ["Yes — he is satisfied on every point now",
            "No — he is being sarcastic and is still unconvinced",
            "Not quite — he is impressed and still not persuaded",
            "No — he thinks Holmes is inventing answers as he goes"],
           2,
           "He says it and then immediately asks about the gas, so he is not finished. It is the tone of a man being won over against his better judgement, and two speeches later he still calls the whole thing a waste of energy."),
         ),

    item("wax", ["One wax stain, or even two, might come by chance",
                 "when I see five", "with his hat in one hand and a candle in the other",
                 "never got wax stains from a gas jet"],
         V("How many wax stains are on the hat, and why does the number matter?",
           ["Two — enough to show a pattern",
            "Five — too many to be accidents",
            "Five — one for each year the hat has been worn",
            "Several — Holmes does not trouble to count them"],
           1,
           "“One wax stain, or even two, might come by chance; but, when I see five…” The number is the argument. One mark is an accident; five is a habit."),
         V("What does Holmes picture the man doing?",
           ["Reading by candlelight with his hat on the table beside him at night",
            "Working in a room lit only by candles",
            "Walking upstairs at night, hat in one hand and candle in the other",
            "Lighting his pipe from a candle on the table"],
           2,
           "He builds a small scene out of five spots of wax: a man going up to bed at night with no light on the stairs. That is what makes the conclusion about the gas convincing rather than clever."),
         V("What is the actual conclusion, and what is it about?",
           ["That the man cannot afford candles",
            "That the man works at night rather than by day",
            "That the man’s house has no gas laid on",
            "That the man is careless with a light in his hand"],
           2,
           "“He never got wax stains from a gas jet.” It is a conclusion about the man’s house, not the man — and in 1890 a house without gas is a house without much money, which agrees with everything else."),
         V("Why does Holmes say a gas jet could not have made the marks?",
           ["Gas jets were fixed to the wall, out of reach of a hat",
            "A gas jet gives no wax to drip",
            "Gas was only used downstairs in most houses",
            "Gas jets were covered by a glass globe"],
           1,
           "Wax comes from a candle and nowhere else. The whole deduction hangs on knowing what a gas light is made of — which is the sort of ordinary knowledge Holmes keeps turning into evidence."),
         V("Of the deductions in the reading, why is this one the most solid?",
           ["Because Watson accepts it without argument",
            "Because five stains can be counted, and wax has one source",
            "Because it is the only one Holmes proves with the lens",
            "Because it agrees with the dust and the moisture marks"],
           1,
           "Compare it with the wife or the brain. Here the evidence can be counted, wax has exactly one source, and the number rules out chance. Holmes even asks “Are you satisfied?” — he knows this is his best one."),
         ),

    item("waste", ["no crime committed and no harm done except the loss of a goose",
                   "rather a waste of energy", "it is very ingenious"],
         V("What is Watson’s verdict on the whole performance?",
           ["That Holmes has proved his case completely",
            "That it is ingenious, but rather a waste of energy",
            "That Holmes has guessed too much from too little",
            "That they should go and look for Henry Baker at once"],
           1,
           "“Well, it is very ingenious,” said I; “but… all this seems to be rather a waste of energy.” He is convinced by the reasoning and unconvinced that it was worth doing, which are two different things."),
         V("What is Watson’s reason for calling it a waste?",
           ["Henry Baker will never be found in a city that size",
            "The goose has already been eaten",
            "No crime has been committed and nobody has been harmed",
            "Holmes has no client and will not be paid"],
           2,
           "“No crime committed and no harm done except the loss of a goose.” It is exactly what Holmes himself said at the start of the reading — Watson is agreeing with him and complaining at the same time."),
         V("Holmes said the same thing five pages earlier. Why does it sound different now?",
           ["Because Holmes has changed his mind since",
            "Because Holmes meant it as a reason to look and Watson as a reason not to",
            "Because Watson has proved there was no crime",
            "Because the goose has been eaten in the meantime and cannot be examined"],
           1,
           "“No crime” was Holmes’s invitation: a problem worth having for its own sake. In Watson’s mouth the same words mean there was nothing here to bother with. The two of them value the work differently."),
         V("Who has the better of this argument, on the evidence so far in the reading?",
           ["Holmes — he has read a stranger’s life off a hat",
            "Watson — nothing has come of it but a portrait nobody can use",
            "Neither — both are right about different things",
            "Holmes — because the hat will lead him to Henry Baker"],
           2,
           "Holmes has done something remarkable; Watson is right that it has changed nothing. Both positions stand up — which is why the story puts the interruption exactly here."),
         V("Why does the story give Watson the last word before the interruption?",
           ["To show that Watson is usually right",
            "To make Holmes look foolish for once",
            "To set up the worst possible moment to be proved wrong",
            "To bring the chapter to a close on a quieter note"],
           2,
           "Watson says it is all a waste of energy. Holmes opens his mouth to reply and does not get a word out, because the door flies open. The timing is the joke."),
         ),

    item("burst", ["had opened his mouth to reply", "the door flew open",
                   "dazed with astonishment", "found in its throat"],
         V("What happens as Holmes is about to answer Watson?",
           ["Peterson sends a message round to Baker Street",
            "The door flies open and Peterson rushes in",
            "Henry Baker himself knocks at the door",
            "A telegram arrives from the police"],
           1,
           "“Sherlock Holmes had opened his mouth to reply, when the door flew open.” He is interrupted mid-argument, and the interruption settles the argument better than any reply could."),
         V("How does Peterson look when he comes in?",
           ["Frightened, as though he had been followed",
            "Angry about the goose he was given",
            "Like a man dazed with astonishment",
            "Out of breath from running all the way"],
           2,
           "“With the face of a man who is dazed with astonishment.” Not frightened, not hurt — astonished. Whatever has happened is a surprise rather than a disaster, and the reading stops there."),
         V("Who found the thing Peterson has come about?",
           ["Peterson himself, as he prepared the bird",
            "Holmes, before he sent the goose away",
            "Peterson’s wife",
            "Mrs. Henry Baker, who claimed the goose"],
           2,
           "The picture on page 136 has it: “See what my wife found in its throat!” The goose went home to be eaten, and the person cooking it is the person who found something."),
         V("Where was it found?",
           ["In the throat of the goose",
            "Tied to the card on the bird’s leg",
            "Sewn into the lining of the hat",
            "In the street where the hat was dropped"],
           0,
           "In the goose’s throat. Tonight’s reading stops before you are told what it is — which is the point at which a chapter ending earns its keep."),
         V("Peterson bursting in the instant Watson says “no crime” is a trick of the storyteller. What is it for?",
           ["To show that Peterson is an unreliable witness",
            "To hide the fact that Holmes had no answer ready",
            "To turn a hat nobody wanted into the start of a case",
            "To remind the reader that the goose had been eaten"],
           2,
           "For five pages this has been an exercise about an old hat, with both men agreeing there is no crime in it. One opened door turns all of that reasoning into the opening of something much larger — and every word of it still counts."),
         ),
]
