# -*- coding: utf-8 -*-
"""Chapters 3 and 4: pages 113 to 117, and 118 to 120.

Same shape as chapters 1 and 2 -- five versions of every question, each with its
own options and its own explanation.

One thing is deliberately left alone. The answer to Bradstreet's circle is on
page 121, one page past tonight's reading, so nothing here asks for it. What the
last question does ask is what can already be worked out from the pages he has
read: the horse was fresh, and he woke up beside the station. That is enough to
know the search is being pointed the wrong way, without being told why.
"""
from eng3_q12 import V, item


# ====================================================================== 3
CH3 = [

    item("ceiling", ["the swish of the leaking cylinder", "shapeless pulp",
                     "drowned my cries", "a gush of hope"],
         V("What does Hatherley hear through the locked door?",
           ["Ferguson arguing with the Colonel outside",
            "The clank of the levers and the swish of the leaking cylinder",
            "The woman calling his name from the stairs",
            "A carriage being brought round to the front door of the house"],
           1,
           "He hears the machine start, and he knows that sound: the swish is the leak he found himself half an hour before. The fault he was hired to diagnose is how he learns he is about to be killed."),
         V("Why is Hatherley, of all people, in the worst position to hope the ceiling will stop?",
           ["He is too weak from the journey to climb",
            "He has no lamp and cannot see it coming",
            "He had examined the press and knows its force",
            "He is standing on the metal floor in the dark"],
           2,
           "“As none knew better than myself, with a force that must grind me to a shapeless pulp.” He had put his hands on the piston. There is no comforting himself with not knowing."),
         V("Why does shouting for help do him no good?",
           ["The house is too far from any other building",
            "The clanking of the levers drowns his cries",
            "The Colonel had already left the house",
            "The door is too thick for sound to pass through"],
           1,
           "“The remorseless clanking of the levers drowned my cries.” The machine that is killing him is also the reason nobody can hear him — and the Colonel is the one working the levers."),
         V("What is Hatherley thinking about while the ceiling comes down?",
           ["Whether the panel in the wall will open",
            "How he might jam the levers from inside",
            "Which way to lie so that dying hurts less",
            "Whether the woman will fetch help in time"],
           2,
           "It is the most frightening paragraph in the story, and what makes it frightening is how practical he is: on his face the weight would come on his spine, and he shudders at “that dreadful snap.”"),
         V("The last sentence of the scene says his eye caught something that brought “a gush of hope” back. What had he seen?",
           ["The key still turning in the lock",
            "A light between two of the wooden boards",
            "The lamp burning where he had set it down",
            "The levers moving on the far side of the wall"],
           1,
           "A thin line of yellow light between two boards — which is to say, a gap. He is saved by noticing something small at the exact moment he can no longer stand up straight."),
         ),

    item("panel", ["the floor and ceiling were of iron, the walls were of wood",
                   "a thin line of yellow light", "the clang of the two slabs of metal"],
         V("What saves Hatherley’s life?",
           ["The machine jamming before the ceiling reached him",
            "The wooden walls, which had a panel in them",
            "The woman stopping the engine from outside",
            "The lamp setting fire to the boards"],
           1,
           "“Though the floor and ceiling were of iron, the walls were of wood.” The part of the press that was not built to hold pressure is the part he gets out through."),
         V("Why does the difference between iron and wood matter so much here?",
           ["Wood muffles sound, so nobody heard him",
            "Iron rusts, and the floor had worn thin",
            "Wood burns, and he could have set it alight",
            "Iron cannot be got through; wood can hide a door"],
           3,
           "The floor and ceiling are the working faces of the press and they are iron. The sides only have to stand there, so they are boards — and a board can be pushed aside."),
         V("What tells Hatherley how close the escape had been?",
           ["The clang of the two slabs of metal behind him",
            "The lamp going out as the panel closed",
            "The sudden silence after the levers stopped",
            "The pain in his hand as he fell through"],
           0,
           "The panel shuts and he hears iron meet iron on the other side of it. He is lying half fainting in the corridor while the press closes on the space he was standing in."),
         V("Who pushed the panel open?",
           ["Ferguson, who had thought better of it",
            "Nobody — the pressure forced the boards apart",
            "Somebody outside the press, in the corridor",
            "Hatherley himself, with the last of his strength"],
           2,
           "The line of light “broadened as a small panel was pushed backwards” — pushed from the other side. He finds out who a moment later, when a hand plucks at his wrist."),
         V("Think about the machine as its owners built it. Why would a press like that have a panel in its wall at all?",
           ["So the men working it could get in and out quickly",
            "So the piston could be reached for oiling and repair",
            "So the room could be aired between uses",
            "So water could be drained from the trough"],
           0,
           "It is a workroom, not a trap — they used it every day to press metal, and a way in and out is ordinary. Stark locked the door and forgot what the men who work the machine rely on."),
         ),

    item("elise", ["a frantic plucking at my wrist", "the same friend whose warning I had so foolishly rejected",
                   "This time, I did not scorn her advice"],
         V("Who is bending over Hatherley when he comes to himself in the corridor?",
           ["Ferguson, holding a lantern",
            "The woman who had warned him twice",
            "The porter from the station at Eyford",
            "A servant he had not seen before"],
           1,
           "“It was the same friend whose warning I had so foolishly rejected.” She had every reason to leave him to it, and she came back — which is the whole point of the scene."),
         V("How does Hatherley describe his own earlier behaviour now?",
           ["As foolish — he had rejected her warning",
            "As reasonable, given what he had been told",
            "As brave, and worth doing again",
            "As unlucky rather than mistaken"],
           0,
           "“So foolishly rejected.” He is telling the story afterwards and he does not dress it up. Watch the sentence that follows: “This time, I did not scorn her advice.”"),
         V("What is she carrying, and what does that tell you about the house?",
           ["A lamp — the one from the hall",
            "A lantern taken from the Colonel",
            "A candle, because the house has no proper light",
            "Nothing at all — she found him lying there in the dark"],
           2,
           "A candle in her right hand while she tugs at him with her left. It fits everything else about the place: no carpets, no furniture, no light — a house being used rather than lived in."),
         V("What is the hurry, in her own words?",
           ["The Colonel is coming up the stairs behind her",
            "They will see that he is not there",
            "The engine cannot be stopped once it is running",
            "The carriage is waiting only a few minutes"],
           1,
           "“They will be here in a moment. They will see that you are not there.” The moment the press comes up empty, they will start searching — and she knows it before he does."),
         V("“This time, I did not scorn her advice.” Why does the story bother to say so?",
           ["To show he has lost his nerve completely",
            "To show that the danger is now over",
            "To mark the moment he starts learning from his mistake",
            "To show that he now trusts her more than he trusts Holmes"],
           2,
           "It is a short sentence doing a lot of work. The headstrong man who stayed twice for his fifty guineas is the same man who now runs when she says run, and he says so himself."),
         ),

    item("window", ["It is high, but it may be that you can jump it",
                    "a butcher’s cleaver", "not be more than thirty feet down",
                    "I was determined to go back to her assistance"],
         V("What is the only way out she can offer him?",
           ["The kitchen door at the back of the house",
            "A bedroom window he may be able to jump from",
            "The stairs down to the hall, while they search above",
            "The panel he has just come through"],
           1,
           "“It is your only chance. It is high, but it may be that you can jump it.” Running feet above them and below them: there is no other route left in the house."),
         V("What is Colonel Lysander Stark carrying when he appears at the end of the passage?",
           ["A revolver and a dark lantern",
            "A lamp and the key to the press",
            "A lantern in one hand and a butcher’s cleaver in the other",
            "The cleaver alone, having left the lantern on the stairs"],
           2,
           "A butcher’s cleaver. The word “butcher’s” is doing the work — it is not a weapon he has gone to fetch, it is a tool out of the kitchen, and that is worse."),
         V("Hatherley climbs out onto the sill and then hesitates instead of jumping. Why?",
           ["The drop looked further than thirty feet",
            "He wanted to hear what passed between her and Stark",
            "He had lost too much blood to trust his grip",
            "He was waiting for the moon to go behind a cloud"],
           1,
           "“I hesitated to jump, so I could hear what passed between my savior and the ruffian who pursued me.” He is halfway to safety and he stops to listen for her."),
         V("What had he decided to do if she were ill-used?",
           ["Shout for Ferguson to come and help her",
            "Jump, and fetch the police from Eyford",
            "Go back to her assistance at any risk",
            "Give himself up so that she would be left alone"],
           2,
           "“If she were ill-used, then at any risk I was determined to go back to her assistance.” He has been foolish all evening; here the same stubbornness looks like something else entirely."),
         V("Two details sit side by side: the moonlit garden looks “quiet and sweet and wholesome,” and a man is coming down the passage with a cleaver. Why put them together?",
           ["To show how far he still has to travel",
            "To show that the night is nearly over",
            "To show how near safety is while the danger is nearest",
            "To suggest that he is imagining the whole thing by now"],
           2,
           "Thirty feet of air between the worst moment of his life and an ordinary garden. The story lets him see exactly what he is reaching for at the moment he is most likely not to reach it."),
         ),

    item("fritz", ["remember your promise after the last time", "He will be silent",
                   "You are mad, Elise", "my thumb had been cut off"],
         V("Elise cries, “remember your promise after the last time. You said it would not happen again.” What does that tell you?",
           ["That Stark had promised to give up the machine",
            "That something like this has happened before",
            "That she had helped a prisoner escape once already",
            "That Stark had promised her a share of the money"],
           1,
           "There was a last time. She is not guessing what Stark will do — she has seen him do it, and she got a promise out of him afterwards. Holmes produces the proof a few pages later."),
         V("What reason does Stark give for not letting Hatherley go?",
           ["That he cannot be trusted to keep a promise",
            "That the police are already looking for him",
            "That he has seen too much",
            "That he knows the way back to the station"],
           2,
           "“You will be the ruin of us. He has seen too much.” It is the plainest thing Stark says all night, and it is the only true one."),
         V("What is the name Elise calls him by, and why is it worth noticing?",
           ["Lysander — so the rank is invented",
            "Fritz — so Colonel Lysander Stark is not his real name",
            "Ferguson — so the two men are brothers",
            "Jeremiah — so he has taken a dead man’s name for himself"],
           1,
           "She calls him Fritz, in English, in front of a stranger. “Colonel Lysander Stark” is a costume — which is exactly why the porter at Eyford has never heard the name."),
         V("Where was Hatherley when the blow fell?",
           ["Standing on the sill with his back to the room",
            "Hanging by his hands from the sill",
            "Already falling towards the garden",
            "Halfway across the bedroom floor"],
           1,
           "“I was hanging with my hands across the sill when his blow fell.” His hands were the only part of him left in the room — which is how the story gets its title."),
         V("When does Hatherley discover that his thumb has gone?",
           ["At the moment the cleaver struck",
            "Not until the doctor in town dressed the wound for him",
            "Only when he woke in the morning",
            "While running through the bushes, when the dizziness came"],
           3,
           "“For the first time, saw that my thumb had been cut off.” He felt a dull pain, fell, got up and ran; it took a fit of dizziness to make him look at his own hand. Fear does that, and Doyle knows it."),
         ),
]


# ====================================================================== 4
CH4 = [

    item("hedge", ["neither house nor garden were to be seen",
                   "the very train station at which I had arrived",
                   "drenched with blood"],
         V("Where does Hatherley find himself when he wakes?",
           ["In a field some miles from any road",
            "In the garden he had jumped down into the night before",
            "In the hedge beside the road, close to the station",
            "In a bedroom at the inn at Eyford"],
           2,
           "“Just a little lower down was the very train station at which I had arrived the previous night.” Of everything in this chapter, remember this: he wakes up next to the station he started from."),
         V("What has become of the house and garden by morning?",
           ["They are locked up and deserted",
            "They are not to be seen at all",
            "They are burning, and the gang have gone",
            "They are full of police from Reading"],
           1,
           "“To my astonishment, neither house nor garden were to be seen.” He did not walk away from the house — he was carried away from it, and that is a strange amount of trouble for the gang to take."),
         V("He fainted in the bushes of a garden and woke in a hedge by the road. What must have happened in between?",
           ["He walked there himself without remembering",
            "The woman dragged him clear of the house",
            "He was carried there while unconscious",
            "The garden was beside the road all along"],
           2,
           "Bradstreet asks about it on the train, and Hatherley admits “a confused memory of being lifted and conveyed somewhere.” Somebody moved him — and did not kill him."),
         V("What condition is he in when he comes to himself?",
           ["Unhurt except for the missing thumb",
            "Wet with dew, his coat-sleeve drenched with blood",
            "Bandaged already, with his hand properly dressed",
            "Too weak to stand or move at all"],
           1,
           "Dew on his clothes tells you how long he lay there; the sleeve tells you how much he had bled. He had been out for most of the night in the open."),
         V("Waking next to the station is the most useful fact in the chapter. Why?",
           ["It shows the gang wanted him to be found",
            "It proves the house cannot have been far from Eyford",
            "It means he can catch the first train to London",
            "It shows the police station was closer than he thought"],
           1,
           "They carried an unconscious man back to the station. Nobody carries a body twelve miles. Put this beside the horse that was still fresh and glossy, and the “hour’s drive” starts to look like a performance."),
         ),

    item("porter", ["The name was strange to him", "police station",
                    "about three miles off", "one to Reading in less than an hour"],
         V("What happens when Hatherley asks the porter about Colonel Lysander Stark?",
           ["The porter says he left on the early train",
            "The porter has never heard the name",
            "The porter points out the road to the house",
            "The porter says he is well known thereabouts"],
           1,
           "“The name was strange to him.” A porter at a small country station knows the local gentry. If he has not heard of Colonel Lysander Stark, there is no such person to have heard of."),
         V("Why does Hatherley not go to the police straight away?",
           ["He was afraid that they would not believe his story",
            "He had promised Stark to say nothing",
            "The station was three miles from the nearest one",
            "He wanted Holmes to hear the story first"],
           2,
           "The police station is three miles off and he is too weak to walk it. So he decides to wait until he is back in town — which is how a case that should have gone to the Reading police arrives in Baker Street instead."),
         V("Which train does Hatherley take from Eyford?",
           ["The first up train to London",
            "One to Reading, in less than an hour",
            "The same last train he had come out on",
            "A goods train, since no other was running"],
           1,
           "“There would be one to Reading in less than an hour.” Reading is where the inspector says they had traced the gang to before and could get no further — the story keeps circling the same few miles of country."),
         V("The porter’s answer is a small moment. What does it actually establish?",
           ["That the gang have already left the district",
            "That “Colonel Lysander Stark” is not a real local name",
            "That the station is not the one he arrived at",
            "That the house is a good deal further off than he thought"],
           1,
           "It is the first outside confirmation of anything. Everything up to now is Hatherley’s word; this is somebody else telling him that the man who hired him does not exist under that name."),
         V("Put the porter’s answer beside what Elise shouted at the window. What do the two together tell you?",
           ["That Stark was once a soldier in Germany",
            "That the gang have bribed the station staff",
            "That Stark and Fritz are two different men",
            "That “Colonel Lysander Stark” is an assumed name"],
           3,
           "She called him Fritz; the porter has never heard of a Colonel Lysander Stark. Two facts from two people who have never met, pointing at one conclusion. That is how a case gets built."),
         ),

    item("advert", ["Jeremiah Hayling",
                    "has not been heard of since",
                    "the last time the Colonel needed his machine overhauled",
                    "Then that explains what the girl said"],
         V("What does Holmes take down from the shelf?",
           ["A railway timetable for the Reading line",
            "A book of newspaper cuttings",
            "A map of the country round Eyford",
            "His index of London criminals"],
           1,
           "One of the books in which he places his newspaper cuttings. Holmes’s filing is a kind of memory: he has been keeping this page for a year without knowing what it was for."),
         V("Who was Jeremiah Hayling?",
           ["A porter who vanished from Eyford station",
            "A hydraulic engineer, aged 26, who disappeared",
            "A clerk who once worked for the Colonel in London",
            "The owner of the house before the gang took it"],
           1,
           "“Lost on the 9th inst., Mr. Jeremiah Hayling, aged 26, a hydraulic engineer.” The same trade as Hatherley, and about the same age. The advertisement is a year old."),
         V("What does Holmes say the advertisement represents?",
           ["A rival gang working the same district",
            "The reason the Colonel had to leave London in a hurry",
            "The last time the Colonel needed his machine overhauled",
            "The first crime the gang ever committed"],
           2,
           "“That represents the last time the Colonel needed his machine overhauled, I fancy.” Said lightly, and it means that the last engineer who went out to mend the press never came back."),
         V("Hatherley cries, “Then that explains what the girl said.” What had she said?",
           ["That he should get away before it was too late",
            "That the Colonel was not who he claimed to be",
            "That there was no good for him to do there",
            "Remember your promise after the last time"],
           3,
           "Her promise makes sense the moment Hayling does. There had been a last time; she had made Stark swear it would not happen again; and Hatherley is standing in the place of a man who is still missing."),
         V("Why is it so bad for Hatherley that the advertisement is a whole year old?",
           ["It means the trail has gone cold since then",
            "It means the police never managed to solve the first case",
            "It means the gang have used the machine for years",
            "It means the gang have done this before and got away with it"],
           3,
           "A year has passed and nobody has found Jeremiah Hayling. Whatever happened to him, it worked — which is what Stark was counting on when he turned the levers."),
         ),

    item("circle", ["a radius of ten miles", "somewhere near that line",
                    "compass drawing a circle with Eyford for its center",
                    "Inspector Bradstreet of Scotland Yard"],
         V("How is Inspector Bradstreet trying to find the house?",
           ["By asking at every station on the Reading line",
            "By drawing a ten-mile circle round Eyford on a map",
            "By searching the villages one after another",
            "By tracing the carriage that met the train"],
           1,
           "A map spread on the seat and a compass. It is a sensible method and it rests entirely on one number, which came from a man who could not see out of the carriage."),
         V("Where does Bradstreet expect the house to be?",
           ["Somewhere near the line of his circle",
            "Anywhere inside the circle he has drawn",
            "At one of the villages west of Eyford",
            "Within three miles of the police station"],
           0,
           "“The place we want must be somewhere near that line.” Near the line — ten miles out. Hold that against the fact that Hatherley woke up beside the station."),
         V("Whose evidence is Bradstreet’s circle built on?",
           ["Holmes’s reading of the newspaper advertisement",
            "The porter’s account of the carriage",
            "Hatherley’s guess at how far he had been driven",
            "The timetable of the last train to Eyford"],
           2,
           "“You said ten miles, I think, sir?” Every mile of that circle comes from a guess made in a dark carriage. The inspector is not careless — he simply trusts the witness further than the witness can be trusted."),
         V("Who is on the train down to Eyford?",
           ["Holmes, Watson and Hatherley only",
            "Holmes, Hatherley, Bradstreet, a plain-clothes officer and Watson",
            "Holmes, Watson and two officers from Reading",
            "Holmes, Bradstreet, Watson and the doctor who dressed the wound"],
           1,
           "Five of them, and Watson lists them all. Scotland Yard is taking this seriously: an inspector and a plain-clothes man for a house nobody can find."),
         V("What is the weakness in a method that starts by drawing a circle?",
           ["A circle is too large an area to search on foot",
            "The map may not show every house in the district",
            "Eyford may not be the right village to start from",
            "It can only be as good as the distance it is drawn from"],
           3,
           "The compass is exact; the number it is set to is a guess. Being precise about an uncertain figure does not make the figure any better — which is the mistake Holmes is about to point out."),
         ),

    item("guesses", ["You are all wrong", "I could lay my finger on it",
                     "no hills there", "the country is more deserted there"],
         V("Each of the four men picks a direction. What does Holmes say to all four?",
           ["That two of them may be right",
            "That the south is the likeliest of them",
            "That they are all wrong",
            "That the map is too old to be trusted"],
           2,
           "“You are all wrong.” “But we can’t all be.” “Oh, yes, you can.” They are arguing about which point on the circle to search; Holmes is telling them the circle itself is the mistake."),
         V("What is Watson’s reason for guessing north?",
           ["The roads are better that way",
            "There are no hills, and the carriage went up none",
            "There are quiet little villages up there",
            "The country is more deserted in that direction"],
           1,
           "Watson is reasoning from the evidence, and reasoning well — Hatherley never noticed the carriage climbing. It is a good argument built on the same bad number as everyone else’s."),
         V("Bradstreet says south, Watson north, the plain-clothes man west, Hatherley east. What do all four guesses have in common?",
           ["They all ignore what the porter said",
            "They all assume the house is about ten miles out",
            "They all rely on Bradstreet’s map being accurate",
            "They all place the house near a village"],
           1,
           "Four different directions and one shared assumption. Nobody questions the ten miles, so nobody can be right, whichever way they point."),
         V("Holmes says quietly that he could lay his finger on the place. What has he been working from?",
           ["The advertisement about Jeremiah Hayling",
            "The map Bradstreet spread on the seat",
            "Details in Hatherley’s own account",
            "Information sent down from Scotland Yard"],
           2,
           "He has been to no houses and interviewed nobody. Everything he has is what Hatherley told him in Baker Street — including the two things Hatherley did not know were important."),
         V("You have read the same pages Holmes has. Which two facts should make you doubt the ten miles?",
           ["The frosted windows, and the hour of the drive",
            "The German books, and the empty upper rooms",
            "The fresh horse, and waking up beside the station",
            "The porter’s answer, and the cleaver in the passage"],
           2,
           "A horse that had done twelve miles of heavy road would not be fresh and glossy, and nobody carries an unconscious man twelve miles to leave him by a station. Both facts are in your reading. Holmes has not been told anything you have not."),
         ),
]
