# -*- coding: utf-8 -*-
"""Chapters 1 and 2: pages 103 to 107, and 108 to 111.

Five versions of every question. A version is the whole question -- the wording,
its own four options, and its own explanation -- so running the quiz again is
not a memory test on where the right answer sat last time.

The five versions of one question are deliberately five different angles on the
same fact, not five rewordings of one sentence: what happened, what it
contradicts, what it tells you about the person, what would follow if it had
gone the other way. If he can answer all five he knows the thing itself.
"""


def V(q, opts, a, why):
    return {"q": q, "opts": opts, "a": a, "why": why}


def item(p, hi, *vs):
    return {"type": "pick", "p": p, "hi": hi, "vs": list(vs)}


# ====================================================================== 1
CH1 = [

    item("horse", ["fresh and glossy", "as hard as the horse could go"],
         V("Holmes interrupts the story to ask the horse’s colour and whether it looked tired. Why is that worth interrupting for?",
           ["A horse fresh and glossy cannot just have done a long drive",
            "A chestnut horse would be easy for the police to trace",
            "It shows which stable in Eyford the carriage was hired from",
            "One horse means the household could not afford a second"],
           0,
           "Holmes is not making conversation. Hatherley believes he was driven a long way; a horse that comes back fresh and glossy has not been driven a long way. It is the first crack in the story, and Holmes finds it before Hatherley has finished telling it."),
         V("Hatherley says the horse was a chestnut, fresh and glossy. What does that quietly contradict?",
           ["The Colonel’s claim to be short of ready money",
            "The hour at which the train reached Eyford",
            "The length of the drive he had just been taken on",
            "The direction in which the carriage set off"],
           2,
           "The drive is the thing it contradicts. Hatherley thinks he went nearer twelve miles; the horse says otherwise. Notice that Hatherley reports the fact without seeing what it means — he is a good witness and Holmes is a good listener."),
         V("Of everything so far, Holmes stops him only to ask about the horse. What does that show about the way Holmes listens?",
           ["He is more interested in horses than in the machine",
            "He picks out the one detail that can be checked against another",
            "He wants Hatherley to slow down so that Watson can take notes",
            "He always asks about whatever came first in a story"],
           1,
           "A story can be argued with; a tired horse cannot. Holmes reaches for the detail that can be tested against something else in the account, and lets the rest of the tale run on."),
         V("Which of Hatherley’s answers is the one Holmes was really fishing for?",
           ["That there was only one horse",
            "That the horse was a chestnut",
            "That they went as hard as the horse could go",
            "That the horse was fresh and glossy"],
           3,
           "The colour and the number are ordinary questions that make the last one sound ordinary too. Fresh and glossy is the answer that matters, and it is the one Holmes asks for last."),
         V("Suppose the horse had come back tired and lathered instead. What would Holmes have learned?",
           ["That the Colonel had borrowed the horse for the night",
            "That the drive really had been long, and the house really far off",
            "That the roads around Eyford were in poor repair",
            "That the carriage must have stopped somewhere along the road"],
           1,
           "Turn the clue round and you can see what it is worth. A tired horse would have supported Hatherley’s twelve miles. A fresh one denies it, and that is why Holmes asked."),
         ),

    item("drive", ["nearer twelve", "frosted glass", "answered only in grunts"],
         V("Stark had said the house was seven miles from the station. What did the drive actually feel like to Hatherley?",
           ["Rather less than seven miles, taken slowly",
            "About seven miles, just as he had been told",
            "At least an hour, and nearer twelve miles",
            "Two hours or more, over very steep ground"],
           2,
           "“We drove for at least an hour. Colonel Stark had said that it was only seven miles, but I think that it must have been nearer twelve.” Remember it: this estimate is the one thing everybody later builds on, and it is a guess made in the dark."),
         V("Why could Hatherley not see where he was being driven?",
           ["The windows were made of frosted glass",
            "The Colonel had made him promise to keep his eyes shut",
            "A blanket had been thrown over the carriage windows",
            "It was too dark outside to make out anything at all"],
           0,
           "Frosted glass — so he could see “nothing except an occasional blur of passing light.” It is not simply that the night was dark: the carriage was built so that a passenger could not look out of it."),
         V("How does the Colonel behave during the hour in the carriage?",
           ["He questions Hatherley closely about his family",
            "He talks cheerfully to keep his guest at ease",
            "He falls asleep almost as soon as they set off",
            "He says almost nothing, and watches Hatherley closely"],
           3,
           "He sat in silence, looking at Hatherley “with great intensity,” and answered attempts at conversation “only in grunts.” A man taking an engineer to a job does not need to watch him for an hour."),
         V("Hatherley’s guess of nearly twelve miles turns out to matter a great deal later. Why should you treat it carefully?",
           ["He was counting the miles aloud to himself as they drove along",
            "The Colonel told him the distance twice over",
            "It is a guess made in the dark with nothing to check it against",
            "He had travelled the same road earlier that day"],
           2,
           "He could not see out, he did not know the roads, and he was jolted about for an hour. Everything he says about the distance rests on how long it felt — which is exactly the sort of evidence Holmes does not trust."),
         V("Put the two facts together: an hour of jolting, and nothing to see. What was the drive designed to do?",
           ["Tire Hatherley out before he had to work",
            "Leave him with no idea where the house was",
            "Give the household time to hide the machine",
            "Keep him from being seen by anyone on the road"],
           1,
           "Frosted windows, an hour of silence and a driver going as hard as the horse could go. Whatever else the drive achieved, it made sure the passenger could never find the place again — or lead anyone back to it."),
         ),

    item("porch", ["failed to catch even the most fleeting glance", "pitch dark in the house"],
         V("When the carriage stopped, what did Hatherley manage to see of the house?",
           ["The front door and the windows on either side of it",
            "Nothing of the front of it at all",
            "A long low building with a lamp burning upstairs",
            "Only the porch, because the rest lay in shadow"],
           1,
           "Stark pulled him straight from the carriage onto the porch and into the hall, “so that I failed to catch even the most fleeting glance of the front of the house.” Not one glimpse — and that cannot be an accident twice in one night."),
         V("Hatherley cannot describe the outside of the house afterwards. Whose doing is that?",
           ["His own — he was too tired to look about him",
            "Nobody’s — the night was simply too dark",
            "The driver’s, who set him down at the wrong door",
            "Stark’s — he was hurried in before he could look"],
           3,
           "“As I followed, pulled me swiftly on a porch in front of us.” Being hurried is the point. First the frosted windows, then the porch: two separate arrangements with the same purpose."),
         V("What happens the instant Hatherley is across the threshold?",
           ["The door slams and the carriage drives away",
            "A lamp is lit and the Colonel introduces his wife",
            "He is asked to hand over his hat and coat",
            "The Colonel locks the door and pockets the key"],
           0,
           "“The door slammed heavily behind us, and I heard faintly the rattle of the wheels as the carriage drove away.” His way home leaves without him, and he notices it — but still thinks about his fee."),
         V("What is the first thing Hatherley notices about the inside of the house?",
           ["A strong smell of oil and hot metal",
            "That it was pitch dark",
            "German voices somewhere above him",
            "That there was no carpet on the floor"],
           1,
           "“It was pitch dark in the house.” The Colonel then has to fumble about for matches — in his own house, at the hour he himself chose. Nobody was waiting up, and nothing had been made ready."),
         V("A man is fetched to a house at midnight and cannot afterwards say what the house looks like. What has the story achieved by this point?",
           ["He has been paid handsomely for very little work",
            "He has been brought somewhere he could never find again",
            "He has been frightened into keeping the secret",
            "He has been kept from meeting anyone else in the house"],
           1,
           "Add it up: a station with no other passengers, frosted windows, an hour of silence, a porch he was pulled across. Every step of the journey removes something he could later tell the police."),
         ),

    item("books", ["several German books were scattered", "an oak shutter was folded across it",
                   "a foreign tongue"],
         V("What does Hatherley notice about the books on the round table?",
           ["They were account books, and all in one hand",
            "They were German — two on science, one poetry",
            "They were engineering manuals, and much used",
            "They were all printed in the same year"],
           1,
           "“In spite of my ignorance of German, I could see that two of them were treatises on science, the other being poetry.” He cannot read them and reports them anyway, which is what makes him worth listening to."),
         V("The woman with the lamp speaks, and the Colonel answers. What does Hatherley learn from that exchange?",
           ["That she is a servant rather than a member of the family",
            "That she had been expecting a different visitor",
            "That the household speaks a language that is not English",
            "That the Colonel is angry with her for coming down"],
           2,
           "“She spoke a few words in a foreign tongue.” Between that, the German books and the name Fritz that Elise uses later, the household is plainly German — which is why Hatherley starts asking himself who these people are."),
         V("He crosses to the window hoping to see the countryside. What stops him?",
           ["An oak shutter folded across it",
            "The glass was frosted, as in the carriage",
            "The window looked out onto a blank wall",
            "Heavy curtains that he could not draw back"],
           0,
           "An oak shutter — the third thing that night arranged so that he cannot see out. By now the pattern is unmistakable, and he notices the uneasiness before he works out the reason for it."),
         V("What made the woman start so violently that the lamp nearly fell from her hand?",
           ["The Colonel’s gruff answer to her question",
            "Catching sight of a stranger in the hall",
            "Hearing footsteps on the stairs behind her",
            "The door slamming shut in the wind"],
           0,
           "She asked something and “my companion answered gruffly” — and that answer was enough to shake her. Hatherley does not know what was said; he only sees what it did to her."),
         V("Three details in this room point the same way: German books, a foreign tongue, an oak shutter. What is Hatherley beginning to feel?",
           ["That he has been brought to the wrong house",
            "That he is uneasy, without yet knowing why",
            "That the fee is not going to be paid after all",
            "That the family are hiding from the police"],
           1,
           "“An uneasiness began to steal over me.” He is an honest narrator: he reports the feeling first and the reasons afterwards, and he still does not leave."),
         ),

    item("warn", ["There is no good for you to do", "no one hinders",
                  "sick with fear", "ten miles or so from Eyford"],
         V("The woman comes to the door of his room. What does she tell him to do?",
           ["To go, because there is no good for him to do there",
            "To hide until the Colonel has gone to bed",
            "To take the lamp and look at the upstairs rooms",
            "To say nothing about having seen her at all"],
           0,
           "“I would go... There is no good for you to do.” She says it in broken English, looking back into the dark behind her, shaking. She is risking a great deal to say it."),
         V("She adds, “You can pass through the door; no one hinders.” Why does she bother to say that?",
           ["To prove she has not locked him in herself",
            "To show him she knows the house better than he does",
            "To tell him the way out is open now and may not stay open",
            "To make him think the Colonel has gone out"],
           2,
           "She is not describing the door, she is offering him a chance. Nobody is watching the hall yet. In a few minutes the newcomers arrive on the stairs, and it is too late."),
         V("What does Hatherley notice about the woman herself as she speaks?",
           ["That she was angry with him for coming",
            "That she was sick with fear",
            "That she was dressed to leave the house",
            "That she had been crying before she came in"],
           1,
           "“I could see that she was sick with fear, and the sight sent a chill to my own heart.” The warning is frightening because of the state of the person giving it, and he feels that — then stays anyway."),
         V("He asks himself where he is. What is the only answer he can give?",
           ["Somewhere south of Reading",
            "About seven miles from Eyford",
            "Ten miles or so from Eyford, and nothing more",
            "Within an hour’s walk of the police station"],
           2,
           "“I was ten miles or so from Eyford, that was all I knew.” Hold on to that sentence. Every search later in the story is built on this one shaky guess of his."),
         V("She warns him at real risk to herself, and he stays. What does that tell you about him?",
           ["He does not believe a word she says",
            "He thinks the Colonel will protect him",
            "He is brave, and stubborn about finishing what he took on",
            "He has not understood a single word of her broken English"],
           2,
           "He understood her perfectly — he calls himself “somewhat headstrong” a page later and admits he rejected her warning foolishly. It is courage and obstinacy at once, and it nearly kills him."),
         ),
]


# ====================================================================== 2
CH2 = [

    item("plea", ["For the love of Heaven", "somewhat headstrong by nature",
                  "my fifty-guinea fee"],
         V("She asks a second time, with her hands together: “get away before it is too late!” What does Hatherley do?",
           ["Promises to go as soon as he has seen the machine",
            "Declares that he intends to stay where he is",
            "Asks her to explain what the danger is",
            "Goes out to the hall to look for the front door"],
           1,
           "“With a stout bearing, therefore, I declared my intention of remaining where I was.” Not a moment of doubt on the outside — though he has just listed to himself all the reasons he is staying."),
         V("What reasons does Hatherley give himself for staying?",
           ["That the Colonel would come after him if he ran",
            "That he had promised the doctor he would finish the job",
            "That he could not find his way back in the dark",
            "His fee, his long journey, and the work he had taken on"],
           3,
           "“I thought of my fifty-guinea fee, of my wearisome journey, and the unpleasant night that seemed to be before me. Was it all for nothing?” The money is first on the list — he is honest about that."),
         V("How does Hatherley describe his own character at this moment?",
           ["As somewhat headstrong by nature",
            "As slow to take fright",
            "As a poor judge of people",
            "As too polite to argue with a lady"],
           0,
           "“But I am somewhat headstrong by nature.” He is telling this to Holmes after the event, so he already knows how it turned out, and he does not excuse himself."),
         V("What interrupts the woman before she can plead with him again?",
           ["A door slams and footsteps come up the stairs",
            "The Colonel calls her name from the hall",
            "The lamp on the table goes out",
            "Someone begins knocking at the front door"],
           0,
           "“A door slammed, and the sound of several footsteps was heard upon the stairs.” She listens, throws up her hands “with a despairing gesture,” and is gone. The chance she offered him closes in that instant."),
         V("Twice now she has told him to go, and twice he has refused. What is the story doing by repeating it?",
           ["Showing that she is not to be trusted",
            "Making it clear that what happens next is his own choice",
            "Hinting that she wants the fee for herself",
            "Suggesting that she is only trying to delay him a little"],
           1,
           "He is not tricked into the danger and he is not dragged into it. He is warned, plainly, twice, and walks in — which is why he calls his own advice-rejecting “foolish” when he looks back on it."),
         ),

    item("door", ["I left this door shut", "I opened the door myself",
                  "suspicious glances"],
         V("Stark says he thought he had left the door shut, and hopes Hatherley has not felt the draught. What is he really doing?",
           ["Apologising for leaving a guest in a cold room",
            "Finding out whether somebody has been in to see him",
            "Explaining why the lamp had gone out",
            "Making conversation while Ferguson catches up"],
           1,
           "The remark sounds like politeness and is a test. An open door means a visitor. Hatherley answers that he opened it himself — and whether or not he meant to, he covers for the woman who warned him."),
         V("How does Hatherley answer the remark about the door?",
           ["He says a servant must have opened it",
            "He says he had not noticed the door at all",
            "He says he opened it himself, feeling the room close",
            "He says the woman with the lamp must have left it open"],
           2,
           "“On the contrary, I opened the door myself, because I felt the room to be a little close.” It is the most useful thing he does all evening, and there is no sign he knows it."),
         V("What does Stark do immediately after that answer?",
           ["Laughs, and says the house is always draughty",
            "Shoots one of his suspicious glances at him",
            "Sends Ferguson downstairs to check the hall",
            "Asks whether he has seen anybody in the passage"],
           1,
           "“He shot one of his suspicious glances at me.” The answer did not satisfy him. That look, and the words “one of,” tell you this is a man who has been watching Hatherley all evening."),
         V("Who is the short thick man with the beard growing out of his double chin?",
           ["Mr. Ferguson, the Colonel’s secretary and manager",
            "Mr. Hayling, a hydraulic engineer",
            "Inspector Bradstreet, who came down from Scotland Yard",
            "The porter from the station at Eyford"],
           0,
           "“This is my secretary and manager,” said the Colonel. Ferguson matters for one reason Hatherley notices at once: from the little he says, he is an Englishman, and everyone else in the house is not."),
         V("Hatherley says he opened the door himself, which is true. What does that answer do for the woman?",
           ["It puts the blame for the draught on her",
            "It gives the Colonel no reason to suspect her",
            "It makes the Colonel send her out of the house",
            "It proves to the Colonel that she cannot be trusted"],
           1,
           "An open door needed explaining, and he explained it without mentioning her. She is still free to come back for him later — which is the only reason he survives the night."),
         ),

    item("house", ["you dig fuller’s earth in the house", "only where we compress it",
                   "no signs of any furniture above the ground floor"],
         V("Hatherley offers to fetch his hat. Why is the Colonel’s answer strange?",
           ["It means the machine is inside the house",
            "It means they will not be going out until morning",
            "It means the hat has already been taken away",
            "It means the walk is shorter than he expected"],
           0,
           "“Oh no, it is in the house.” Hatherley catches it at once: “What, you dig fuller’s earth in the house?” A clay pit is outdoors. Whatever is upstairs, it is not a mine."),
         V("How does the Colonel explain a hydraulic press being indoors?",
           ["That the machine is too valuable to leave outside",
            "That the pit is in the cellar beneath the house",
            "That the house is only where they compress the earth",
            "That the neighbours must not see the machine at work"],
           2,
           "“No, no. This is only where we compress it.” Then straight on: “But never mind that!” Every time Hatherley’s question lands, the Colonel answers quickly and changes the subject."),
         V("What does Hatherley notice as they climb the stairs?",
           ["Fresh paint on the walls and a new carpet on all the staircases",
            "No carpets, no furniture above the ground floor, plaster peeling",
            "Rooms full of packing cases and machinery",
            "Doors standing open onto empty bedrooms"],
           1,
           "A house with nothing in it above the ground floor is not a home. People are not living there — they are using it, and they are ready to leave it."),
         V("What one thing does Hatherley find reassuring about Ferguson?",
           ["That he is a gloomy, silent man",
            "That he stays outside the little room",
            "That he is a fellow Englishman",
            "That he asks practical questions about the machine"],
           2,
           "“I could see from the little he said that he was at least a fellow Englishman.” It reassures Hatherley and it should not. Ferguson is on the wrong side of the door when it is locked."),
         V("An engineer is brought to mend a clay-works machine and finds an empty house with the machine upstairs. What should he conclude?",
           ["That the business is a good deal smaller than he was told",
            "That the pit must be some distance away",
            "That the story he was told does not fit what he can see",
            "That the family have only just moved in"],
           2,
           "He does conclude it, a page later, in so many words: “the story of the fuller’s earth was a fabrication.” The evidence for that is here, in the hall and on the stairs, before he ever sees the press."),
         ),

    item("inside", ["actually within the hydraulic press", "the end of the descending piston",
                    "a slight leakage", "had shrunk so as not quite to fill the socket"],
         V("Where is Hatherley standing while the Colonel explains the machine?",
           ["In a gallery looking down on it",
            "Inside the hydraulic press itself",
            "In the corridor outside the little room",
            "On a platform above the metal floor"],
           1,
           "“We are now actually within the hydraulic press.” The room is the machine. Stark even says it would be “particularly unpleasant for us if anyone were to turn it on” — and twenty minutes later he turns it on himself."),
         V("What is the ceiling of the little room?",
           ["A trap door to the floor above",
            "The end of the descending piston",
            "A sheet of iron holding up the water tank",
            "The underside of the main water columns"],
           1,
           "“The ceiling of this small chamber is really the end of the descending piston, and it comes down with the force of many tons upon this metal floor.” Hatherley is told exactly how he is meant to die, as a piece of engineering."),
         V("How does Hatherley first know something is wrong with the machine?",
           ["A whishing sound when he pressed down the levers",
            "The piston came down more slowly than it should",
            "Water was standing on the metal floor",
            "The levers would not move at all"],
           0,
           "He hears it before he sees it — “I knew at once by the whishing sound that there was a slight leakage.” That leak comes back later: it is the swish he hears through the door when the engine is set at work."),
         V("What exactly had gone wrong with the press?",
           ["A driving-rod had bent out of true",
            "The metal floor had cracked somewhere under the pressure",
            "One of the water columns had sprung a leak",
            "A rubber band had shrunk and no longer filled its socket"],
           3,
           "“One of the rubber bands around the end of a driving-rod had shrunk so as not quite to fill the socket along which it worked.” A small fault, found in minutes. He really was worth his fee, which is part of what makes the evening so ugly."),
         V("Stark says it would be unpleasant for them if anyone turned the machine on while they stood in it. Why does that line matter so much later?",
           ["Because Ferguson is the one who works the levers",
            "Because it is exactly what Stark does to him",
            "Because it explains why the room is so small",
            "Because it warns Hatherley to keep away from the levers"],
           1,
           "It is said as a joke about their own safety. Within the hour Stark locks that door and sets the engine going with Hatherley inside — and Hatherley, who has just examined it, knows better than anyone what is coming down."),
         ),

    item("trough", ["a crust of metallic deposit", "was a fabrication",
                    "if I knew what the exact purpose was",
                    "turned the key in the lock"],
         V("What convinces Hatherley that the fuller’s earth story is untrue?",
           ["The house had no clay anywhere in it",
            "Ferguson admitted there was no pit",
            "So powerful an engine could not be for so small a purpose",
            "The Colonel could not say where the clay pit actually was"],
           2,
           "“It would be absurd to suppose that so powerful an engine could be designed for so small a purpose.” He reasons it out from the machine itself, as an engineer would, and he is right."),
         V("What does he find on the floor of the machine?",
           ["A large iron trough with a crust of metallic deposit",
            "Several pounds of pale clay, freshly dug",
            "Scratches where something heavy had been dragged",
            "A pool of oil leaking from the driving-rod"],
           0,
           "Metal, not clay. He is scraping at the crust to see what it is when the Colonel appears above him — and the crust is the real answer to what the machine is for."),
         V("What does Hatherley say to the Colonel that he instantly regrets?",
           ["That the story about the fuller’s earth was a lie",
            "That he would advise better if he knew the machine’s real purpose",
            "That he intended to tell the police all about it in the morning",
            "That the woman downstairs had warned him to leave"],
           1,
           "He phrases it as an engineer being helpful and it is an accusation, and both men know it. “The instant that I uttered the words I regretted the rashness of my speech.”"),
         V("How does the Colonel answer that question?",
           ["By offering him double the fee in return for his silence",
            "By calling Ferguson to take him downstairs",
            "By telling him the truth about the machine",
            "By saying he shall know all about it — and locking him in"],
           3,
           "“Very well, you shall know all about the machine.” It is a promise and a sentence at the same time. Then: a step backward, the door slammed, the key turned."),
         V("Hatherley cannot help asking his question, even though he knows he should not. What does that say about him?",
           ["He has no idea how much danger he is in",
            "He is more frightened of being thought a fool than of Stark",
            "He would rather understand a thing than be safe",
            "He believes the Colonel will not dare to hurt him"],
           2,
           "He has just been warned twice, he has seen the empty house and the metal crust, and he asks anyway, because the machine does not make sense and he wants it to. It is the same trait that brought him there for fifty guineas."),
         ),
]
