/* Worked examples, one per skill, opened when a question is missed.
 *
 * Ten of these were written for the Lesson 7 review and are the same text,
 * kept in one place rather than copied. Each carries the lesson's own method
 * underneath it in the lesson's own words, and a `book` line saying where the
 * same kind is worked, so there is somewhere further to go than what we wrote.
 *
 * Generated by scratchpad/mk_ex.js.py from the Lesson 7 spec plus the seven
 * skills that review did not touch. Nothing from the book is reproduced.
 */
(function (root) {
  "use strict";
  var EX = {
 "angles": {
  "book": "Lesson 7 names every one of these and works six examples, including naming the angles in a figure and finding a missing segment length. Saxon Course 2, Lesson 7, pages 47-50.",
  "cite": "Saxon Math Course 2, Lesson 7",
  "text": [
   "An angle is made by two rays from a common endpoint, called the vertex. Angles are sorted by size: a right angle is exactly 90° and is marked with a small square, an acute angle is smaller than that, an obtuse angle is bigger than a right angle but less than a straight line, and a straight angle is exactly 180°.",
   "Two lines in the same plane either cross once or never cross. If they never cross they stay the same distance apart and are parallel, written ∥. If they cross and make square corners they are perpendicular, written ⊥ — and that makes four right angles, not one. If they cross at any other angle they are oblique.",
   "Lines in different planes that never meet are skew, which is not the same as parallel: parallel lines have to be in the same plane.",
   "When a point B lies between A and C on a line, the two short segments make the long one: AB + BC = AC. So if AB is 3 cm and AC is 7 cm, then BC is 4 cm."
  ],
  "title": "Lines, angles and the words for them",
  "vocab": [
   [
    "vertex",
    "noun",
    "the common endpoint where the two rays of an angle meet"
   ],
   [
    "ray",
    "noun",
    "part of a line with one endpoint, going on forever the other way"
   ],
   [
    "segment",
    "noun",
    "part of a line with two endpoints, so it has a length"
   ],
   [
    "perpendicular",
    "adjective",
    "crossing at right angles, written with the ⊥ symbol"
   ],
   [
    "parallel",
    "adjective",
    "in the same plane and never crossing, written with the ∥ symbol"
   ]
  ]
 },
 "backwards": {
  "book": "The lesson works an unknown subtrahend in Example 2 and an unknown divisor in Example 4, each one alongside the easier form, so the difference between them is on the same page. Saxon Course 2, Lesson 3, pages 22–23.",
  "cite": "Saxon Math Course 2, Lesson 3",
  "text": [
   "Two forms need a moment's thought, because the variable is not the thing being changed — it is the thing doing the changing.",
   "50 − n = 18. Read it as a story: 50, take away n, leaves 18. When the variable is the part being taken away, the answer is the difference: n = 50 − 18 = 32. Check: 50 − 32 = 18. True.",
   "60 ÷ n = 12. Read it the same way: 60 shared into n groups puts 12 in each group. When the variable is underneath, ask how many of the answer fit into the top: n = 60 ÷ 12 = 5. Check: 60 ÷ 5 = 12. True.",
   "In both, the move is the same operation as the one in the equation, not the opposite. That is what makes them different from the other four forms — and it is why naming the position is worth the trouble."
  ],
  "title": "When the variable is underneath, or is the part taken away",
  "vocab": [
   [
    "subtrahend",
    "the part taken away",
    "The unknown in 50 − n = 18. To find an unknown subtrahend, subtract the difference from the minuend."
   ],
   [
    "divisor",
    "how many it is shared into",
    "The unknown in 60 ÷ n = 12. To find an unknown divisor, divide the dividend by the quotient."
   ]
  ]
 },
 "check": {
  "book": "Every worked example in the lesson is followed by a check written out underneath it — the book treats the check as part of the answer rather than as optional. Saxon Course 2, Lesson 3, pages 21–23.",
  "cite": "Saxon Math Course 2, Lesson 3",
  "text": [
   "Every one of these can be checked in a few seconds, and the check is worth more than it costs.",
   "Put the value back into the original equation and see whether it comes out true. Not into the equation you rearranged — into the one you were given. That way a wrong move shows up instead of being repeated.",
   "Solve 15n = 195, and suppose the answer written down is 13. Check: 15 × 13 = 195. True, so it is right.",
   "Suppose instead the answer written down was 180, from subtracting 15 rather than dividing. Check: 15 × 180 = 2700, not 195. The check finds it, and it takes one line."
  ],
  "title": "Checking the answer",
  "vocab": [
   [
    "check",
    "the second half of the answer",
    "Substitute the value into the original equation. If both sides come out equal, the answer is right."
   ]
  ]
 },
 "column": {
  "book": "Lesson 1 works addition, subtraction, multiplication and division of whole numbers and money across five examples. Saxon Course 2, Lesson 1, pages 8-10.",
  "cite": "Saxon Math Course 2, Lesson 1",
  "text": [
   "Line the numbers up by place value — ones under ones, tens under tens — and work right to left. With money that means the decimal points sit in a straight line, and everything else follows from that.",
   "Adding: 4,175 + 2,968. Ones: 5 + 8 = 13, so write 3 and carry 1. Tens: 7 + 6 + 1 = 14, write 4 carry 1. Hundreds: 1 + 9 + 1 = 11, write 1 carry 1. Thousands: 4 + 2 + 1 = 7. The answer is 7,143.",
   "Subtracting: $80.00 − $72.45. There is nothing to take 5 from, so borrow across: $80.00 becomes 79 dollars and 100 cents. 100 − 45 = 55 cents, and 79 − 72 = 7 dollars. The answer is $7.55.",
   "Multiplying by a two-digit number takes two rows: multiply by the ones digit, then by the tens digit shifted one place left, then add the rows. 164 × 23 is 164 × 3 = 492, plus 164 × 20 = 3,280, which comes to 3,772.",
   "Every one of these can be checked by working backwards — add the difference to the smaller number, or divide the product by one factor."
  ],
  "title": "Working down the columns",
  "vocab": [
   [
    "sum",
    "addition",
    "the answer when numbers are added; the numbers added are addends"
   ],
   [
    "difference",
    "subtraction",
    "the answer when one number is taken from another"
   ],
   [
    "product",
    "multiplication",
    "the answer when numbers are multiplied; the numbers multiplied are factors"
   ],
   [
    "quotient",
    "division",
    "the answer when one number is divided by another"
   ]
  ]
 },
 "common": {
  "book": "The lesson works a greatest common factor in Example 3, listing both sets of factors and circling the ones they share. Saxon Course 2, Lesson 6, page 41.",
  "cite": "Saxon Math Course 2, Lesson 6",
  "text": [
   "A common factor divides both numbers. Finding them takes two steps, and the second one is easy to forget.",
   "Step one: list the factors of each number separately. Factors of 12: 1, 2, 3, 4, 6, 12. Factors of 20: 1, 2, 4, 5, 10, 20.",
   "Step two: compare the two lists. The common factors are the ones that appear on both lists — here, 1, 2 and 4. The greatest common factor is the largest of those: 4. Two correct lists side by side are not the answer yet; the answer is what they share.",
   "The lesson's own trick is to write both lists out and circle the numbers that appear in both. The circles are step two made visible, so it is harder to stop after step one."
  ],
  "title": "Common factors and the greatest common factor",
  "vocab": [
   [
    "factor",
    "noun",
    "a whole number that divides another with no remainder"
   ],
   [
    "common factor",
    "noun",
    "a number that is a factor of both numbers"
   ],
   [
    "greatest common factor",
    "noun",
    "the largest of the common factors — often written GCF"
   ],
   [
    "divisibility",
    "noun",
    "whether one whole number divides another with no remainder"
   ]
  ]
 },
 "divide": {
  "book": "The lesson names all three positions and works an unknown dividend and an unknown divisor together in Example 4. Saxon Course 2, Lesson 3, page 23.",
  "cite": "Saxon Math Course 2, Lesson 3",
  "text": [
   "Solve n ÷ 12 = 30.",
   "Ask what was done to n. It was divided by 12. The variable was divided, so multiply to undo it.",
   "n ÷ 12 × 12 = 30 × 12, which leaves n = 360.",
   "Check: 360 ÷ 12 = 30. True.",
   "Dividing again is the tempting mistake, because the equation has a division sign in it. But the sign says what was already done, not what to do next. Dividing here would give 2.5, and 2.5 ÷ 12 is nowhere near 30 — the check catches it immediately."
  ],
  "title": "When the variable was divided",
  "vocab": [
   [
    "dividend",
    "the number being shared",
    "To find an unknown dividend, multiply the quotient by the divisor."
   ],
   [
    "divisor",
    "how many it is shared into",
    "To find an unknown divisor, divide the dividend by the quotient."
   ],
   [
    "quotient",
    "the answer",
    "To find an unknown quotient, divide the dividend by the divisor."
   ]
  ]
 },
 "evaluate": {
  "book": "Lesson 1 introduces variables and evaluation after the arithmetic, and Example 5 evaluates an expression for given values. Saxon Course 2, Lesson 1, pages 10-11.",
  "cite": "Saxon Math Course 2, Lesson 1",
  "text": [
   "A variable is a letter standing in for a number that has not been given. To evaluate an expression you put the number in and work it out.",
   "Evaluate ab when a = 30 and b = 4. Two letters written together means multiply, so ab is 30 × 4 = 120. It does not mean the two digits side by side.",
   "Evaluate b − a with the same numbers: 4 − 30 would be negative, so read the expression carefully — with a = 30 and b = 4 the answer really is −26. Order matters in subtraction and division, and does not in addition and multiplication.",
   "A word problem is the same job with the numbers hidden in a sentence. “The product of two one-digit numbers is 24” means two numbers that multiply to 24 — 3 and 8, or 4 and 6. The sentence then tells you which one it wants."
  ],
  "title": "Putting numbers in for letters",
  "vocab": [
   [
    "variable",
    "noun",
    "a letter used to stand for a number that is not given"
   ],
   [
    "evaluate",
    "verb",
    "put the given numbers in place of the letters and work it out"
   ],
   [
    "expression",
    "noun",
    "numbers and letters combined by operations, with no equals sign"
   ]
  ]
 },
 "fractions": {
  "book": "Lesson 9 works adding, subtracting and multiplying fractions and then reciprocals, keeping the rules side by side so the difference between them is on one page. Saxon Course 2, Lesson 9, pages 60-64.",
  "cite": "Saxon Math Course 2, Lesson 9",
  "text": [
   "Adding and subtracting need the same denominator; multiplying does not. That one sentence is most of the lesson, and mixing the two rules up is the usual mistake.",
   "Adding with the same denominator: add the numerators and leave the denominator alone. 3/8 + 2/8 = 5/8. The denominator says what size the pieces are, and adding pieces does not change their size.",
   "Multiplying: multiply the numerators together and the denominators together. 2/3 × 3/5 = 6/15, which reduces to 2/5. No common denominator is needed, and looking for one is wasted work.",
   "Reduce at the end. Divide the top and the bottom by their greatest common factor: 6/15 has a common factor of 3, so it becomes 2/5.",
   "The reciprocal of a fraction is that fraction turned upside down. The reciprocal of 3/4 is 4/3, and a number times its reciprocal is always 1."
  ],
  "title": "Adding, subtracting and multiplying fractions",
  "vocab": [
   [
    "common denominator",
    "phrase",
    "the same bottom number, which adding and subtracting need"
   ],
   [
    "reciprocal",
    "noun",
    "the fraction turned upside down; a number times its reciprocal is 1"
   ],
   [
    "reduce",
    "verb",
    "divide top and bottom by their greatest common factor"
   ]
  ]
 },
 "grouping": {
  "book": "Lesson 2 sets the properties out in a table and then uses them to make a multiplication easier to do in your head. Saxon Course 2, Lesson 2, pages 16–17.",
  "cite": "Saxon Math Course 2, Lesson 2",
  "text": [
   "Parentheses say which part to work out first. With addition and multiplication that turns out not to matter — this is the associative property.",
   "(3 + 8) + 5 = 11 + 5 = 16, and 3 + (8 + 5) = 3 + 13 = 16. Same answer. (2 × 3) × 4 = 6 × 4 = 24, and 2 × (3 × 4) = 2 × 12 = 24. Same answer.",
   "Subtraction and division are not associative. In division the parentheses change the answer, and often by a lot.",
   "100 ÷ (10 ÷ 2) = 100 ÷ 5 = 20, but (100 ÷ 10) ÷ 2 = 10 ÷ 2 = 5. Twenty against five, from the same three numbers in the same order. So with division, work out what is inside the parentheses first, and never assume you can move them."
  ],
  "title": "What the parentheses do",
  "vocab": [
   [
    "associative property",
    "noun",
    "the grouping can change without changing the answer — true for addition and multiplication, false for subtraction and division"
   ],
   [
    "commutative property",
    "noun",
    "the order can change without changing the answer — again true for addition and multiplication only"
   ],
   [
    "identity property",
    "noun",
    "adding 0, or multiplying by 1, leaves a number as it was"
   ]
  ]
 },
 "minus": {
  "book": "The lesson names all three positions and gives the rule for each, then works an unknown minuend and an unknown subtrahend side by side in Example 2. Saxon Course 2, Lesson 3, page 22.",
  "cite": "Saxon Math Course 2, Lesson 3",
  "text": [
   "Solve n − 26 = 71.",
   "Ask what was done to n. 26 was subtracted from it. Something was subtracted from the variable, so add it back — that is the move that undoes it.",
   "n − 26 + 26 = 71 + 26, which leaves n = 97.",
   "Check: 97 − 26 = 71. True, so 97 is right. If the check comes out false, the move was the wrong one — subtracting again instead of adding would have given 45, and 45 − 26 = 19, not 71."
  ],
  "title": "When something was subtracted",
  "vocab": [
   [
    "minuend",
    "the number you start from",
    "The unknown in n − 26 = 71. To find an unknown minuend, add the other two numbers."
   ],
   [
    "subtrahend",
    "the part taken away",
    "The unknown in 50 − x = 18. To find an unknown subtrahend, subtract."
   ],
   [
    "difference",
    "what is left",
    "To find an unknown difference, subtract."
   ]
  ]
 },
 "mixed": {
  "book": "Lesson 10 turns division answers into mixed numbers and converts both ways between mixed numbers and improper fractions. Saxon Course 2, Lesson 10, pages 66-69.",
  "cite": "Saxon Math Course 2, Lesson 10",
  "text": [
   "An improper fraction is a division waiting to happen. 17/5 means 17 ÷ 5, which is 3 with 2 left over, so 17/5 = 3 2/5.",
   "Going the other way, multiply the whole number by the denominator and add the numerator. 3 2/5 becomes 3 × 5 = 15, plus 2, which is 17 — so 17/5. The denominator never changes.",
   "That is also how a division with a remainder should usually be written. 38 ÷ 5 is 7 remainder 3, and the remainder goes over the divisor: 7 3/5. Writing “7 r3” is a step on the way, not the finished answer.",
   "Reduce the fraction part if it will go. 14 ÷ 4 is 3 remainder 2, which is 3 2/4 — and 2/4 reduces to 1/2, so the answer is 3 1/2."
  ],
  "title": "Mixed numbers and improper fractions",
  "vocab": [
   [
    "improper fraction",
    "noun",
    "a fraction whose numerator is bigger than its denominator"
   ],
   [
    "mixed number",
    "noun",
    "a whole number and a fraction written together"
   ],
   [
    "remainder",
    "noun",
    "what is left over after dividing; it becomes the numerator"
   ]
  ]
 },
 "percent": {
  "book": "Lesson 8 covers fractions, percents and the inch ruler together, because they are the same idea measured three ways. Saxon Course 2, Lesson 8, pages 53-58.",
  "cite": "Saxon Math Course 2, Lesson 8",
  "text": [
   "Percent means “per hundred”, so a percent is a fraction whose denominator is 100. That is the whole idea, and everything else is arithmetic.",
   "To turn a fraction into a percent, scale it so 100 is underneath. 3/4 = 75/100 = 75%. If the denominator does not go into 100 neatly, divide instead: 3 ÷ 4 = 0.75, and 0.75 × 100 = 75.",
   "To turn a percent into a fraction, put it over 100 and reduce. 40% = 40/100, and both parts divide by 20, so it is 2/5.",
   "Worth knowing by sight: 1/2 = 50%, 1/4 = 25%, 3/4 = 75%, 1/5 = 20%, 1/10 = 10%, 1/100 = 1%.",
   "An inch ruler is the same idea in wood. The longest marks are halves, then quarters, then eighths — so six marks past the start on an eighths ruler is 6/8, which reduces to 3/4 of an inch."
  ],
  "title": "Fractions and percents are the same thing",
  "vocab": [
   [
    "numerator",
    "top",
    "how many parts you have"
   ],
   [
    "denominator",
    "bottom",
    "how many parts the whole was cut into"
   ],
   [
    "percent",
    "noun",
    "a fraction with 100 underneath; the symbol is %"
   ],
   [
    "lowest terms",
    "phrase",
    "the numerator and denominator share no factor but 1"
   ]
  ]
 },
 "place": {
  "book": "Lesson 5 works through place value to hundred trillions and reading and writing whole numbers, in seven examples. Saxon Course 2, Lesson 5, pages 35-37.",
  "cite": "Saxon Math Course 2, Lesson 5",
  "text": [
   "A digit is worth different amounts depending on where it sits. Counting from the right: ones, tens, hundreds, thousands, ten thousands, hundred thousands, millions, and so on up through billions and trillions.",
   "In 47,308,000 the 7 sits six places from the right, which is the millions place, so it is worth 7,000,000. The 3 sits five places along, the hundred thousands, so it is worth 300,000.",
   "The commas are the shortcut. They mark off groups of three, and each group has its own name: thousands, millions, billions, trillions. So 90 million written in digits is 90,000,000 — nine, zero, then two more groups of three zeros.",
   "To compare two numbers with the same number of digits, go left to right and stop at the first place where they differ. That place decides it, and nothing to the right of it can change the answer."
  ],
  "title": "Which place a digit sits in",
  "vocab": [
   [
    "digit",
    "noun",
    "one of the ten symbols 0 through 9"
   ],
   [
    "place value",
    "noun",
    "what a digit is worth because of where it sits"
   ],
   [
    "period",
    "noun",
    "a group of three places marked off by commas"
   ]
  ]
 },
 "plus": {
  "book": "The lesson works three unknown addends in Example 1, including one with four addends where the known ones are added together first. Saxon Course 2, Lesson 3, page 21.",
  "cite": "Saxon Math Course 2, Lesson 3",
  "text": [
   "Solve n + 34 = 90.",
   "Ask what was done to n. 34 was added to it. Something was added to the variable, so subtract it.",
   "n + 34 − 34 = 90 − 34, which leaves n = 56.",
   "Check: 56 + 34 = 90. True.",
   "If several numbers are being added — 5 + 9 + n + 4 = 30 — add all the known ones first, then subtract that total from the sum: 5 + 9 + 4 = 18, and 30 − 18 = 12."
  ],
  "title": "When something was added",
  "vocab": [
   [
    "addend",
    "a number being added",
    "To find an unknown addend, subtract the known addend from the sum."
   ],
   [
    "sum",
    "the total",
    "To find an unknown sum, add the addends."
   ]
  ]
 },
 "single": {
  "book": "The lesson works this kind twice: Example 4 asks which whole numbers from 1 to 10 divide a four-digit number, and the practice set asks for the single-digit divisors of another. Saxon Course 2, Lesson 6, pages 41–42.",
  "cite": "Saxon Math Course 2, Lesson 6",
  "text": [
   "A factor of a number divides it with nothing left over. To find every factor, work up from 1 in pairs: 1 × 60, 2 × 30, 3 × 20, 4 × 15, 5 × 12, 6 × 10. Once the pairs start repeating you have them all, so the factors of 60 are 1, 2, 3, 4, 5, 6, 10, 12, 15, 20, 30 and 60.",
   "Now read the question again. If it asks for the single-digit factors, only the ones below 10 belong in the answer: 1, 2, 3, 4, 5 and 6. The question asks for the single-digit factors, so the list stops at 9. The rest are still factors — they were just not what was asked for.",
   "For a single-digit question there is a quicker route than listing every pair: test 1 through 9 with the divisibility tests below. 1 always divides, and the number itself belongs on the list only if it happens to be a single digit."
  ],
  "title": "Single-digit factors",
  "vocab": [
   [
    "divisible by 2",
    "test",
    "the last digit is even"
   ],
   [
    "divisible by 3",
    "test",
    "the digits add up to a multiple of 3"
   ],
   [
    "divisible by 4",
    "test",
    "the last two digits divide by 4"
   ],
   [
    "divisible by 5",
    "test",
    "the last digit is 0 or 5"
   ],
   [
    "divisible by 6",
    "test",
    "it passes both the test for 2 and the test for 3"
   ],
   [
    "divisible by 8",
    "test",
    "the last three digits divide by 8"
   ],
   [
    "divisible by 9",
    "test",
    "the digits add up to a multiple of 9"
   ],
   [
    "divisible by 10",
    "test",
    "the last digit is 0"
   ],
   [
    "7",
    "no test",
    "there is no quick test for 7 — divide and see"
   ]
  ]
 },
 "squares": {
  "book": "Lesson 4 is where sequences are introduced, working the rule out from the first few terms across eight examples. Saxon Course 2, Lesson 4, pages 26–31.",
  "cite": "Saxon Math Course 2, Lesson 4",
  "text": [
   "A perfect square is a whole number multiplied by itself. They are called squares because that many tiles will make a square: nine tiles make a three-by-three square, sixteen make a four-by-four.",
   "The first fifteen are 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196 and 225 — that is 1 × 1 up to 15 × 15. Worth knowing by sight, because they turn up constantly.",
   "The gaps between them grow: 3, 5, 7, 9, 11. So a run of perfect squares is never a sequence where the same number is added each time, which is one way to recognise one.",
   "Not every sequence is squares. Plenty count up by the same amount every time — 4, 11, 18, 25 adds seven at each step. Find the step by subtracting one term from the next, then keep adding it. If the gaps are all equal it is that kind; if the gaps grow, look for squares.",
   "A number that is not on the list is not a perfect square. 50 is not, because it sits between 49 and 64 — you would need something between 7 and 8 to make it, and that is not a whole number."
  ],
  "title": "Perfect squares",
  "vocab": [
   [
    "sequence",
    "noun",
    "a list of numbers that follows a rule"
   ],
   [
    "term",
    "noun",
    "one of the numbers in a sequence"
   ],
   [
    "perfect square",
    "noun",
    "a whole number multiplied by itself"
   ]
  ]
 },
 "times": {
  "book": "The lesson works two unknown factors in Example 3, and writes the check underneath each as a multiplication. Saxon Course 2, Lesson 3, pages 22–23.",
  "cite": "Saxon Math Course 2, Lesson 3",
  "text": [
   "Solve 7n = 168.",
   "7n means 7 × n. The variable was multiplied, so divide to undo it.",
   "7n ÷ 7 = 168 ÷ 7, which leaves n = 24.",
   "Check: 7 × 24 = 168. True.",
   "If there is more than one number on that side — 2 · 3 · n = 168, say — multiply them together first. 2 · 3 · n is 6n, and then one division finishes it: n = 28."
  ],
  "title": "When the variable was multiplied",
  "vocab": [
   [
    "factor",
    "a number being multiplied",
    "To find an unknown factor, divide the product by the known factor."
   ],
   [
    "product",
    "the result",
    "To find an unknown product, multiply the factors."
   ]
  ]
 }
};
  if (typeof module === "object" && module.exports) module.exports = EX;
  else root.MATHEX = EX;
})(typeof window !== "undefined" ? window : this);
